### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by PurpleHel** [SilentChaos512/Silent-Gear#1]
Since it's just a preview mod I made no attempt to figure out why it's crashing, just disabled it, but here, have a crash report if you want it. Full list of 200+ mods at the end of the report. https://pastebin.com/8UajP4kq

**Comment by SilentChaos512** [comment]
Thanks for reporting, that never would have crashed on my machine.

**Comment by PurpleHel** [comment]
Yeah, running a ridiculous amount of mods makes things interesting! :)
