### ISSUE TITLE
client crashes on using multiblock tool

### ISSUE THREAD

**Issue by ItsBonezey** [SilentChaos512/Silent-Gear#100]
https://pastebin.com/
the mod author for Project MMO has made a workaround, but claims the problem is ultimately on your end.

**Comment by SilentChaos512** [comment]
Link is invalid

**Comment by ItsBonezey** [comment]
whoops, I'll fix that
sorry for the delay.
https://pastebin.com/QTPtgC0Q

**Comment by SilentChaos512** [comment]
Most likely needs to be fixed by whatever the other mod is, the `harmonised.pmmo` (Project MMO?) at the top of the stacktrace.
