### ISSUE TITLE
Feature Request: Better tool rod customization

### ISSUE THREAD

**Issue by cysabi** [SilentChaos512/Silent-Gear#101]
## What Should Be Added or Changed?
Currently, there are only 4 types of (completely static) tool rods.

Treat tool rods in a way like the "main part".
Allow mixed materials, traits, everything that's supported when you create a main part.

## Why Should This Be Done?
It gives the player a lot more creativity when it comes to their tools.
Currently, only the main part actually has any comprehensive customization to it.

**Comment by cysabi** [comment]
## More reasons
This part may require a lot more overhaul to the currently code base, but it will be for a good use.

Currently, there's no real reason to craft a "head" of any tool because you can simply add a tool rod to the recipe.

However, if you treat tool rods as a separate part, you replace each blueprint with just a head version. (Pickaxe head blueprint, tool rod blueprint)

~~The tool rod blueprint will act very similar to any other blueprint, The intake will be 2 materials.~~

**Comment by SilentChaos512** [comment]
Just want to clarify, are you proposing that rods be crafted with main parts, or stick with the same items and allow multiple per tool?

Allowing multiple per tool comes with it's own set of problems. The main issue is that the rods currently give multipliers or flat bonuses to stats, which is very different from the AVG (average) modifiers that main parts typically have. At the very least the existing values would need to be reduced to keep them reasonable.

There also wouldn't need to be any additional blueprints. The rod blueprint could be re-purposed. And the final recipe could still be tool head + rod -> tool. The blueprints exist to prevent recipe conflicts.

**Comment by cysabi** [comment]
I'm proposing that rods be crafted in the same way that you craft main parts, (e.g. Crimson Iron Tool Rod)

I'm not proposing multiple per tool, just like you cannot have multiple main parts per tool.

**Comment by cysabi** [comment]
Perhaps this can also extend to tips and grips.

**Comment by SilentChaos512** [comment]
Still thinking about how exactly to handle this. Probably going to wait until 1.16 since this will be such a big overhaul of the current code. Might even have to break compatibility with older versions and data packs.

**Comment by SilentChaos512** [comment]
Feature is mostly implemented at this point, so I'm closing this issue.
