### ISSUE TITLE
Shearing

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#103]
## What Should Be Added or Changed?
Perhaps one or more of the current tools could be allowed to function as shears with right click? I'm thinking the dagger would work well for this.

## Why Should This Be Done?
Repairable shears and the ability to shear before having gathered iron in the event of packs where that is far down the progression track compared to vanilla. Maybe make it configurable to a minimum tier of material too but default to tier 1.

**Comment by SilentChaos512** [comment]
Was going to just add shears, but it looks like support for custom shears isn't possible right now. Forge will need to make some changes first.
