### ISSUE TITLE
Magmatic Trait Does Not Work

### ISSUE THREAD

**Issue by SPL17SCR33N** [SilentChaos512/Silent-Gear#109]
Netherrack axe does not turn logs into charcoal, pickaxe does not smelt ores or turn cobble into stone, shovel does not turn sand to glass, etc.

**Comment by SilentChaos512** [comment]
As far as I'm aware this is unfixable until Forge adds the `HarvestDropsEvent` back in. Someone correct me if I'm wrong, but I don't see any way to add functions to existing loot tables either. You can only add new pools or get existing ones by name.

**Comment by SilentChaos512** [comment]
Found a solution thanks to someone on my Discord server. Will upload a new version later today.
