### ISSUE TITLE
Server Crash on Startup (1.15.2)

### ISSUE THREAD

**Issue by nikoptune** [SilentChaos512/Silent-Gear#112]
## Versions

- **Silent Gear**: 1.5.7+82
- **Silent's Gems**: 3.5.1+84 
- **Silent Lib**: 4.6.0+48
- **Forge**: 31.1.44
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Server is expected to launch

## Actual Behavior
Server crashes with error `net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [Silent Gear (silentgear) has failed to load correctly`

Mod loads fine on Client, however.

## Links/Images
[Crash Log](https://pastebin.com/uPZicX8D)

## Steps to Reproduce the Problem

1. Launch server w/ Silent Gear enabled

**Comment by SilentChaos512** [comment]
Need a full log file, the crash report isn't showing anything useful for whatever reason.

**Comment by Ninja-Recai** [comment]
Hi there,
I've got the exact same problem, so here are my full logs: https://pastebin.com/PFNTyD3g

**Comment by SilentChaos512** [comment]
Oof, OK I see the problem. Sided-ness issue with the new command in e6a39419249d778a7efca55f541b281732fd8339. Thanks, Ninja-Recai. Will try to fix this when I get home from work. Downgrading to 1.5.6 should resolve the crash for now.

**Comment by nikoptune** [comment]
Damn, sorry about the lack of info in the log. Glad someone else had the problem & a log available. 
🎉
