### ISSUE TITLE
Re-add Shields / Paxels

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#114]
## What Should Be Added or Changed?

Re-add Shields and Paxels from Silent's Gems. Shields should just offer more durability over vanilla shields. Paxels should have a slight harvest speed nerf. (90%?)

## Why Should This Be Done?

This would less confuse players moving from 1.12, offers a good alternative for vanilla shields that don't poof into nonexistence, and good alternative for static paxels from other mods, like mekanism.

**Comment by SilentChaos512** [comment]
Paxels should be working correctly in 1.6.1. Shields have been enabled and crafting recipes added, but the model currently has some issues.
