### ISSUE TITLE
Repairs costing only 1 resource

### ISSUE THREAD

**Issue by GigaAkuma** [SilentChaos512/Silent-Gear#123]
## Versions

- **Silent Gear**: SilentGear-1.15.2-1.6.4+90
- **Silent's Gems**: N/A
- **Silent Lib**: SilentLib-1.15.2-4.6.1+49
- **Forge**: 31.1.63
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior
Repairs costing the appropriate amount of resources

## Actual Behavior
You can repair any silent gear armor using just one resource of the same tier as the ones used to create it, so you could use just 1 emerald to fully repair an armor piece made entirely out of diamonds

## Links/Images
![awdwa](https://user-images.githubusercontent.com/65485787/82141400-d441eb80-9835-11ea-8459-13113a8962ee.jpg)

**Comment by SilentChaos512** [comment]
Thank you. Looks like I just need to rebalance repairs for armor.
