### ISSUE TITLE
Hammer Excavator and Shovel cant break blocks anymore

### ISSUE THREAD

**Issue by f0kx** [SilentChaos512/Silent-Gear#127]
Minecraft Version 1.15.2

- **Silent Gear**: 1.7.0+93
- **Silent's Gems**:-
- **Silent Lib**: 4.6.1+49
- **Forge**: 31.2.0
- **Modpack**: Valhalla²
- **Optifine Installed**: YES

Hey i update your Mod and whenever i try to use my old tools (hammer excavator or shovel) they cant break the blocks they should be (cobble dirt) but when i use it on ores or other stone like slate from embellish craft it works fine! also not working on your ores like zinc etc!

**Comment by SilentChaos512** [comment]
Seems to be working normally for me. Maybe some more information will help:

1. Can you see anything in the items' tooltips that seems out of place? For example, warnings about invalid parts, missing stats, or stats with a value of zero.
2. Any error messages in the log file? If you could share your log file, that may be helpful.
3. Do newly crafted items work correctly?

**Comment by f0kx** [comment]
I give you the stats first
https://imgur.com/a/kNyy4Su (hammer)
https://imgur.com/a/5wKmsyj (excavator)
https://imgur.com/a/F5HNfzY (shovel)

**Comment by f0kx** [comment]
okay i think i found the bug in tooltip it deosnt show me you broke it only when i hover over the tool belt there is the message

https://imgur.com/a/IMrfgAA
