### ISSUE TITLE
Error when disabling common materials

### ISSUE THREAD

**Issue by MineWitherMC** [SilentChaos512/Silent-Gear#13]
Disabling materials with
```json
{"availability":{"enabled":false}}
```
doesn't work and has to be done with something like
```json
{
    "type": "main",
    "stats": [],
    "traits": [],
    "crafting_items": {},
    "display": {
        "hidden": true
    },
    "availability": {
        "enabled": false
    },
    "tier": -1
}
```
otherwise the material is not removed. This is caused by [this](https://github.com/SilentChaos512/Silent-Gear/blob/10e444d/src/main/java/net/silentchaos512/gear/api/parts/ItemPart.java#L369) method yielding NullPointerException when `stats`, `display`, etc are not present.
Also related: if material is not hidden, it is shown in example recipes. This also is true for *disabled* materials.

### Versions
- **Silent Gear**: `0.3.0`, `0.3.1` and older
- **Silent Lib**: `3.0.8-158`
- **Forge**: `14.23.4.2759`

**Comment by SilentChaos512** [comment]
Fixed in version 0.4.0
