### ISSUE TITLE
Borked interaction with Quark

### ISSUE THREAD

**Issue by JaxckLl** [SilentChaos512/Silent-Gear#131]
## Versions

- **Silent Gear**: x.x.x
- **Silent's Gems**: x.x.x 
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

Quark's sort button is sitting in the middle of Silent Gear's special crafting grid.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by Partonetrain** [comment]
This is a Quark issue that can be solved by putting `"net.silentchaos512.gear.block.craftingstation.CraftingStationScreen"` into the Ignored Screens array in Quark's config.

I'm not Silent, but please use the issue template

**Comment by JaxckLl** [comment]
Thanks man!
