### ISSUE TITLE
Silky trait appears to be missing?

### ISSUE THREAD

**Issue by JakeMoe** [SilentChaos512/Silent-Gear#132]
## Versions

- **Silent Gear**: 1.7.0+93
- **Silent's Gems**: N/A
- **Silent Lib**: 4.6.1+49
- **Forge**: 31.2.5
- **Modpack**: Valhelsia 2 and by itself
- **Optifine Installed**: No

## Expected Behavior
Silky trait to show up in JEI like Malleable does

## Actual Behavior
No material(s) found with silky trait

## Links/Images
N/A

## Steps to Reproduce the Problem
Create MultiMC instance selecting only Forge, SIlent Lib, Silent's Gems, and JEI. Create new world.  Search JEI for Traits; "Silky" appears to be missing.

Since the wiki doesn't tell me what might give the Silky trait, I don't know what to add to my tool to see if it get Silky.

**Comment by SilentChaos512** [comment]
There are no parts in base Silent Gear that have Silky. Silent's Gems adds at least one, agate. I try not to put enchantment traits on parts right now because they have some minor issues. You're welcome to add the trait to whatever you want with a data pack.

**Comment by JakeMoe** [comment]
Ah, ok then, hadn't realized an extra mod or data pack would be needed for that trait.  That explains that then; Valhelsia 2 seems to add Silent Gear and Mechanisms, but not Gems.  No Silky for me then.  Cheers.
