### ISSUE TITLE
Add stat display for the new Material format

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#136]
## What Should Be Added or Changed?

- The new material system is great, especially with the ability to make rods that have synergy, but you get no idication on the stats for the materials until you use them. I understand that they are very new and in development, but using it in survival we have literally no idea what their stats are. It could even be a simple command to dump stats in chat, as long as we have a way to see it.

## Why Should This Be Done?

- This should be done because in survival mode, stats become trial and error to figure out. Alongside that, datapack makers can't tell when they've made a typo when they're updating to the new format.

Love your mod, by the way

**Comment by SilentChaos512** [comment]
Still considering how to best handle this. For now, you can use the `/sgear_mats dump` command to create a spreadsheet of available materials. You can also add a `false` argument at the end of the command to exclude the "child" materials, which usually have the same stats and traits as their parent (wood, wool, etc.)

In version 1.7.4, you can click the file name in chat to open it, just like screenshots. Any spreadsheet program should work.
