### ISSUE TITLE
Harvestcraft items display as viable items for blueprints in JEI

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#141]
## Versions

- **Silent Gear**: v1.7.4+104
- **Silent's Gems**: v3.5.5+88
- **Silent Lib**: v4.6.3+55
- **JEI**: v6.0.0.4
- [**Pam's HC Food Core**: v1.0.3](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
- **Forge**: v31.2.19

## Expected Behavior

Pam's Harvestcraft items should not display as a viable input for blueprints in JEI.

## Actual Behavior

Multiple Pam's Harvestcraft items display as a viable input for blueprints in JEI, even though they cannot be used in a recipe.

## Links/Images
 
![2020-06-15_19 53 15](https://user-images.githubusercontent.com/12000593/84720807-ad65fa80-af44-11ea-8f4c-68bcbcd147a1.png)
![2020-06-15_19 53 23](https://user-images.githubusercontent.com/12000593/84720809-adfe9100-af44-11ea-86f3-55b4dcdc92d7.png)

## Steps to Reproduce the Problem

1. Install required mods
2. View the uses for the sauce pan, juicer, etc.

**Comment by SilentChaos512** [comment]
Interesting. Reminds me of #74. Could be the same type of bug.

**Comment by WenXin20** [comment]
And it doesn't seem to be limited to Harvestcraft items, it's showing items that can craft grips from mods such as Endergetic, Savage & Ravage, End Reborn.

**Comment by SilentChaos512** [comment]
Does disconnecting and reconnecting to the server (without restarting) fix the issue? If so, pretty sure I know how to fix it.

**Comment by WenXin20** [comment]
I'll give it a try soon

**Comment by WenXin20** [comment]
Reconnecting to the server doesn't work. 
The item does have the tooltip `SGear Material` and `Material ID: silentgear:wool` on it, if that provides any clues. Only the Grip blueprint/template seems to be affected.

**Comment by SilentChaos512** [comment]
Has this been fixed in 1.7.5 or higher?

**Comment by WenXin20** [comment]
Yup, seems to be fixed. :)
