### ISSUE TITLE
Make JEI plugin show multiple materials in gear crafting

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#142]
## What Should Be Added or Changed?

- I think you should visually show the JEI recipe using multiple materials (of the same tier).

## Why Should This Be Done?

- After watching a few let's plays with modpacks that have sgear in it, I haven't seen a single let's play actually use material mixing. I think that having the JEI recipe show multiple materials per recipe would give a good hint for people that mixing materials would work.

**Comment by SilentChaos512** [comment]
Looks like I can shift over each list of ingredients so they are staggered. Not sure how much that will help, but worth a try!
