### ISSUE TITLE
Fluffy Puff & Banana changes

### ISSUE THREAD

**Issue by McKitten** [SilentChaos512/Silent-Gear#145]
## What Should Be Added or Changed?
- Fluffy Puff moved from gems to gear
- Nether banana moved from gear to gems.
- Seeds need to have more uses.

- (Description)

## Why Should This Be Done?
- The banana is not really needed unless dealing with chaos mechanics
- Fluffy puff recipes are just awesome.
- Because biofuel (mechanisms?) & creatures could get rid of the excess (cereal blend or chickens?)

**Comment by SilentChaos512** [comment]
I'm considering moving the fluffy puffs to SGear. But I will keep the banana in SGear as well.

**Comment by LlubNek** [comment]
while you're at it, maybe add botany pots support for fluffy puffs (you already have it for flax).

**Comment by SilentChaos512** [comment]
Fluffy puffs moved to Silent Gear. Nether trees/bananas are staying. Not really sure what to do with seeds. Seems making chickens eat them would require either a Forge change or a coremod (thanks as always, Mojang...)

Fluffy puff related commits: cd71edc4d8387fcd057b2aa89462d6d62d6846f1, b038f6011fba5f5b87d20c2d77e1d82b180582ef, e92b069ea61d3712d105fa4737ee6ce1b57bdf19
