### ISSUE TITLE
Add Rod Blueprint to Blueprint Package

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#146]
## What Should Be Added or Changed?

- When using the Blueprint Package to get your first blueprints, a Rod Blueprint should be given too.

## Why Should This Be Done?

- Having a rod blueprint at the start would be useful, as the new compound rods are super useful to have, and it would spare the player having to make one on their own.

**Comment by SilentChaos512** [comment]
Was added by 54fe49d7083f09bf9e660f1395c9ecdd6c5969fb. I forget the exact version, but should be included in 1.8.1.
