### ISSUE TITLE
Unavoidable NullPointerException thrown when a weapon is given a tip upgrade in LAN

### ISSUE THREAD

**Issue by Pyrocake** [SilentChaos512/Silent-Gear#148]
## Versions

- **Silent Gear**: 1.7.5
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.6.3
- **Forge**: 31.2.21
- **Modpack**: Valhelsia 2 
- **Optifine Installed**: No 

## Expected Behavior

I am able to apply a tip upgrade to a tool or weapon
## Actual Behavior

My client instantly disconnects upon confirming the upgrade, kicking me out of LAN (I am not hosting the LAN). Any attempt to rejoin will be futile, as it will always throw a NullPointerException while loading terrain. I will never be able to rejoin that world afterward

Grips function exactly as expected, tip upgrades do not.

## Links/Images

- https://pastebin.com/MdhDmSdF Log from the last attempt at running where the error was confirmed to be due to this mod at least partially

## Steps to Reproduce the Problem

1. Join someone's LAN world
2. Take a SilentGear tool
3. Apply a tip upgrade such as Lapis Lazuli tip
4. It has now force closed the connection

**Comment by SilentChaos512** [comment]
Probably the same issue as #143, especially if lapis coated upgrade is
involved. Try updating to Silent Gear 1.8.0.
