### ISSUE TITLE
Crafting pebbles voids hammer

### ISSUE THREAD

**Issue by Chinthor** [SilentChaos512/Silent-Gear#149]
## Versions

- **Silent Gear**: 1.7.5-106
- **Silent's Gems**: na
- **Silent Lib**: 4.6.3-55
- **Forge**: 31.02.21
- **Modpack**: Valhelsia 2  v2.2.3
- **Optifine Installed**: No 

## Expected Behavior

Craft a modular hammer with a piece of cobblestone and get back pebbles. In inventory or in crafting table. Hammer looses some durability. Play "tool break" sound if this craft exceeds hammer durability. Get back damaged or broken hammer with the pebbles.

## Actual Behavior

If made from all stone with wooden handle, hammer is voided, output gets pebbles as expected. Iron hammer or Iron hammer with some stone parts both give expected results. All stone hammer vanishes. Sound of tool breaking does not play.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Craft stone hammer using blueprint, stick, and 6 cobblestone.
2. Place stone hammer in any crafting grid at any durability along with one cobblestone.
3. Choose the output "pebbles" instead of choosing to repair hammer with the stone. 
4. Get pebbles, lose hammer.

**Comment by SilentChaos512** [comment]
Probably another manifestation of the issue described in #147. The quick repair recipe conflicts with the pebbles recipe.

**Comment by Chinthor** [comment]
Could be. Though I find it odd that it still happens when you are given a choice of output. The "same recipe, multiple outputs" feature seems to be working. This seems more a function of using a crafting item's durability and leaving it in the table. The pebble recipe isn't in this case.

**Comment by SilentChaos512** [comment]
Should be resolved with the addition of repair kits in 1.8.1 (c35557982f8b63f75945e71a7982510c979cd9a5).
