### ISSUE TITLE
Ender crystal drops nothing?

### ISSUE THREAD

**Issue by WispIV** [SilentChaos512/Silent-Gear#153]
No matter what pickaxe I try it doesn't drop anything unless I'm doing something wrong somehow.

- **Silent Gear**: SilentGear-1.15.2-1.7.5+106.jar
- **Silent's Gems**: 1.15.2-3.5.5+88.jar 
- **Silent Lib**: SilentLib-1.15.2-4.6.4+56.jar

- **Forge**: forge-1.15.2-31.2.0
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior
Ender crystal to drop similar to chaos crystal

## Actual Behavior
Just nothing drops

## Links/Images

I have yet to get a different outcome sadly

1.
2.
3.

**Comment by SilentChaos512** [comment]
You need a pickaxe with harvest level of 4. Try crimson steel or
supercharged diamonds. Also, wrong repo. I'll move the issue if you can
confirm this is a bug.

**Comment by WispIV** [comment]
I'm really sorry about that, yeah it was the harvest level.
I did try to google it but finding info was difficult so I thought it might have been a bug.. Sorry again and thank you
