### ISSUE TITLE
1.15.2-1.8.2+109 - new materials can't be used as main parts.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [SilentChaos512/Silent-Gear#154]
## Versions

- **Silent Gear**: 1.15.2-1.8.2+109
- **Silent Lib**: 1.15.2-4.6.4+56
- **Forge**: 31.2.30
- **Modpack**: private
- **Optifine Installed**: yes

## Expected Behavior

materials to use the main part stats assigned to them in the related material file. e.g. Bismuth brass has stats in the file for use as a main part or rod.

## Actual Behavior

Bismuth brass has stats in the file for use as a main part or rod, but these stats are ignored in game leaving the bismuth brass only usable as a stat-less rod. no tools or other parts can be made.
part grading works but yields no stats after.

(Description here)

## Links/Images
N/A

## Steps to Reproduce the Problem

1.install both Gear and Mechanisms.
2.get some bismuth brass, grade it(or not) and try to make a pick.
3.see an empty output.
4. don't profit :(

**Comment by SilentChaos512** [comment]
Yep, not usable as main parts yet. Hoping to get the new material system fully integrated sometime next week.

**Comment by ArMoReDfUrY** [comment]
No worries, i'll keep using the data packs til it's ready.

keeping this open for now, will close when the new system is integrated.

loving the look of it so far :)

**Comment by LlubNek** [comment]
Probably related:
using SilentGear-1.15.2-1.9.1+120.jar
no Silent Gear related datapacks installed 
The following items are labelled "SGear Material" but have no stats or traits, despite having a related materials .json in the mod jar:
leaves
sandstone
red sandstone
terracotta (and coloured terracottas)
redstone
string
feather
glowstone
lapis_lazuli
quartz
aluminum
titanium
nickel
copper
zinc
silver
tin
osmium
platinum
lead
bismuth
uranium
zinc
brass
electrum
steel
osmium
bronze
blaze_gold
sinew
flax
invar
bismuth_brass
aluminum_steel
bismuth steel
signalum
lumium
enderium

I would guess that an entry is needed under silentgear_parts\main (or similar) for these to work.

Note that using https://github.com/SilentChaos512/SGear-Basic-Metals with newer versions of SGear does not work well.  The stats you get when you craft an item won't match what you see when looking at the materials.
edit:  actually, even without basic metals "Stellar I" keeps showing up on tools crafted from refined iron, though refined iron ingots show only "Malleable V".

**Comment by SilentChaos512** [comment]
I just coded the tooltips for new materials. Will be fixed in 1.9.2.
