### ISSUE TITLE
Lumberaxe crashes game

### ISSUE THREAD

**Issue by 3dguru** [SilentChaos512/Silent-Gear#156]
## Versions

- **Silent Gear**: 1.15.2-1.7.5+106
- **Silent's Gems**: 1.15.2-3.5.5+86
- **Silent Lib**: 1.15.2 - 4.6.4+56
- **Forge**: 31.2.30
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Using lumberaxe to chop down trees instead crashes game when breaking the first log

(Description here)

## Actual Behavior
Using lumberaxe to chop down trees instead crashes game when breaking the first log

(Description here)

## Links/Images
https://pastebin.com/RyGevK3E

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Was this also reported to Project MMO? May need to be fixed on their end.

**Comment by grandogarndo** [comment]
I have been getting this issue, and pattymorestuff lumber axes work fine.  crash log:https://pastebin.com/GCTDMKc8
