### ISSUE TITLE
Suggestion: Rename Tool

### ISSUE THREAD

**Issue by FirstBitStudios** [SilentChaos512/Silent-Gear#158]
Something that I really enjoyed from Tinkers was the ability to name your created/customized tool. It really helped since my friends and I would have the same kinds of tools usually and the naming would help identify which belonged to whom after death or drops. It would be nice to see that kind of feature available here.

**Comment by SilentChaos512** [comment]
Should still be possible to rename items in the anvil, is that not the case?
