### ISSUE TITLE
flax plant duplicating seeds

### ISSUE THREAD

**Issue by ZarikTH** [SilentChaos512/Silent-Gear#159]
## Versions

- **Silent Gear**: SilentGear-1.15.2-1.8.2+109.jar
- **Silent's Gems**: na 
- **Silent Lib**: SilentLib-1.15.2-4.6.4+56.jar
- **Forge**:  forge-31.2.30
- **Modpack**: valhelsia 2 2.2.4 
- **Optifine Installed**: yes (problem exists with it and w/o it) 

## Expected Behavior

_wild_ flax plant shouldnt be able to drop unlimited seeds

## Actual Behavior
wild flax plant drops unlimited seeds when you right click it

## Steps to Reproduce the Problem

1. right click the flax plant
2. unlimited seeds pop out
3. rinse & repeat
(also put this on valhesia issue tracker but i believe ive gotten this on multiple modpacks as well so it might just be silents mod itself)

**Comment by SilentChaos512** [comment]
Likely the same issue as #82. Should be a relatively simple fix, just need to rewrite wild flax to not behave like crops.
