### ISSUE TITLE
Chaos nodes causing chaotic inventory behavior

### ISSUE THREAD

**Issue by justastranger** [SilentChaos512/Silent-Gear#16]
### Versions

- **Silent Gems**:  SilentsGems-1.12.2-2.8.5-299.jar is the last version released before ATM 3.0.2 came out
- **Silent Lib**:  SilentLib-1.12.2-3.0.6-154.jar
- **Forge**:  1.12.2.2760
- **Modpack** (if applicable): All The Mods 3: Lite v3.0.2

Standing near a chaos node causes weird things to happen with the inventory. After receiving a packet from the node, sorting the inventory with Inventory Tweaks scrambles the hotbar. It also freezes items in place, attempting to move items causes them to rebound back to their original places after breaking a block or sorting the inventory. It works properly when a non-inventory GUI is open (chest, iron backpack, refined storage grid, etc.) I believe it is related to chaos nodes repairing items but I haven't yet attempted to isolate it to that particular behavior. I do not believe anything is generated in the log when the issue occurs.

### Steps to reproduce the problem

1. Have damaged armor equipped
2. Stand near chaos node with items in inventory
3. Attempt to move items around between hotbar and inventory

(I apologize if it isn't too terribly helpful, I'm reporting this on a phone away from my computer. I'll improve the accuracy once I get back to my computer and can confirm details.)

**Comment by SilentChaos512** [comment]
Wrong repo, this is Silent Gear.
