### ISSUE TITLE
Alternative to Dagger or Templates

### ISSUE THREAD

**Issue by medtryx** [SilentChaos512/Silent-Gear#160]
An alternative recipe for Template Boards or Templates.

With the new update, a dagger is required to create those items, however a dagger requires those or a blueprint to be crafted in the first place. The templates always seemed to be an early step, prior to blueprints, but are now limited by the same need of paper blueprints have, making them somewhat redundant. Early paper can also be scarce in some types of world gen, such as TerraForged due to the decreased water and sugar cane spawn. 

Also as the Template Boards are required to create the basic level of repair kits eliminating the major quality of life improvement Silent Gear has over vanilla tools.

**Comment by SilentChaos512** [comment]
Daggers can be crafted without blueprints or templates now. One main + a rough rod.

Admittedly, this does need to be described in detail somewhere.

**Comment by medtryx** [comment]
> 
> 
> Daggers can be crafted without blueprints or templates now. One main + a rough rod.
> 
> Admittedly, this does need to be described in detail somewhere.

Wow, completely missed that, I had tried to craft with just a stick, and just assumed it was a glitch in the recipe. I am glad you thought of that ahead of time! This completely eliminates the issue. Thanks for the quick reply.

**Comment by SilentChaos512** [comment]
No problem. I'll leave this issue open until I update the documentation.
