### ISSUE TITLE
client Crash on loadup. (Registry Object not present: silentgear:custom_tipped_upgrade)

### ISSUE THREAD

**Issue by Wissi** [SilentChaos512/Silent-Gear#162]
Awesome mod, we love your work, thanks for all your hard work.
We are trying to upgrade our modpack and keeps crashing with:

**java.lang.NullPointerException: Registry Object not present: silentgear:custom_tipped_upgrade**

Full crash log [here](https://gist.github.com/Wissi/446959968823e7c40feef1a1764e1541).

Using either : 
*SilentGear-1.15.2-1.8.1+108.jar*  or  *SilentGear-1.15.2-1.8.2+109.jar*
(works fine with SilentGear-1.15.2-1.8.2+107.jar)
Forge: 31.2.30

Full modpack information [here](https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack).

**Comment by SilentChaos512** [comment]
You would post this right after I merged a bunch of experimental changes into the main branch XD

I'm not sure why this happens, but I think one of the changes I made recently will prevent the crash, at the cost of breaking item colors. It seems like some other mod is responsible for this somehow. The only way I could see this crashing is if somehow the color handlers event is being fired _before_ items are registered, which Forge allegedly fixed a while ago.

Anyway, I uploaded an alpha build [here](https://www.curseforge.com/minecraft/mc-mods/silent-gear/files/3000521). If you can identify what mod is causing this, please update me.
