### ISSUE TITLE
[1.15.2] Crafting Station Inventory Bug (item deletion)

### ISSUE THREAD

**Issue by stop-x13** [SilentChaos512/Silent-Gear#164]
## Versions
- **Silent Gear**: 1.15.2-1.9.1+120
- **Silent's Gems**: 1.15.2-3.5.6+89
- **Silent Lib**: 1.15.2-4.6.5+58
- **Forge**: 31.2.30
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Crafting station has an inventory. When in creative and JEI’s cheat mode, it should still able to insert item inside.

## Actual Behavior
Click on an item and hover over said inventory, it shows the text “Click to delete”, which is the same text shown when hovering over the JEI tab on the right. Attempt to click on the inventory will delete the item instead of inserting the item in said inventory. Shift click works fine, and without JEI’s cheat mode works fine.

## Steps to Reproduce the Problem

1. Install this mod, install JEI
2. Enter JEI’s cheat mode (for easy access to items)
3. Try to put items inside the left hand side inventory of the crafting station, using mouse click.
4. “click to delete” is shown and if clicked, the item is deleted

**Comment by WenXin20** [comment]
This probably happens because of JEI's favorites list, which is on the left-hand side, items are added to it by pressing 'a' while the mouse is over an item. The Crafting Station probably isn't checking for it.
