### ISSUE TITLE
Katana not reflecting ghast fireballs

### ISSUE THREAD

**Issue by ArchangelAnguris** [SilentChaos512/Silent-Gear#165]
## Versions

- **Silent Gear**: 1.7.5
- **Silent's Gems**: N/A
- **Silent Lib**: 4.6.4
- **Forge**: 13.2.30
- **Modpack**: HR:New Beginnings
- **Optifine Installed**: Yes 

## Expected Behavior

When I left click in the direction of a ghast fireball to reflect it, it should fire back at the direction pointed as with a normal sword

## Actual Behavior

The ghast fireballs hit me instead of being reflected.

## Links/Images
Unable to take pictures or videos
## Steps to Reproduce the Problem

1.Go into the nether wielding a katana (mine is just a steel katana)
2.Find a ghast and have it start firing at you
3.Try to reflect it (and it fails)
4. (side note) I managed to do it no problem with a stone pickaxe from the same mod, so I'm not sure whats up with that.

**Comment by ArchangelAnguris** [comment]
I've only been playing this mod pack for 2 days or so, and I tried many times to reflect the fireball and it worked perfectly fine with my pick from the same mod which is very odd. Haven't tried any of the other weapons yet but I was also using the shield from the same mod; not sure if that changes anything or not.
I also haven't added or removed any mods from the pack aside from preview version of 1.15.2 optifine, dunno if that matters or not.

**Comment by SilentChaos512** [comment]
Tried this and was able to successfully reflect Ghast fireballs with a katana and other items. Maybe it was slightly more difficult, hard to say. I see no reason why the item in the player's hand would have an effect, unless a reach distance modifier is screwing with things somehow.

**Comment by ArchangelAnguris** [comment]
Dunno. I updated to the latest versions of your mods since the pack wasn't
properly updated regularly. So that might have changed things. I'll try
later today and see if it happens again.
