### ISSUE TITLE
Repair kit Dupe Bug

### ISSUE THREAD

**Issue by ExoFrece** [SilentChaos512/Silent-Gear#166]
SilentGear-1.15.2-1.9.3+122
SilentGems-1.15.2-3.5.6+89
SilentLib-1.15.2-4.6.6+59
Forge 31.2.5

The repair kit can be duplicated

Example:
Put 8 repair kit and material of choice into the workbench and 8 repair kits with the material come back and 7 repair kits are still in the workbench.

**Comment by SilentChaos512** [comment]
Fixed in version 1.9.4 by 95d74f45cf78a4dc202457fa4219a224a243bfdf
