### ISSUE TITLE
Repair kit not working

### ISSUE THREAD

**Issue by tomverberkt** [SilentChaos512/Silent-Gear#167]
I'm new to the mod so I might be doing it wrong. But I fill a crude repair kit with iron, which is also the material I used for my pick. When I put them together, the repair kit doesn't repair my pickaxe. 
Am I doing something wrong?

**Comment by SilentChaos512** [comment]
Please include proper version information. There was a bug fixed in version 1.9.4 which might be the issue you are seeing. Also, was iron the only material in the tool head? Tier of the repair material needs to match the highest tier in the tool head.
