### ISSUE TITLE
[Wiki Enhancement] Add full list of available traits

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#17]
As the title states, it would be nice to have a concise list of the available traits for making custom material files.

**Comment by mathgeniuszach** [comment]
@SilentChaos512 I've created an updated Markdown post for 1.4.3 you can copy and paste to the wiki if you want:
https://pastebin.com/BEj6saY6

Some of the ids I didn't know, so I just put [UNKNOWN](W) for them. You can delete these if you want.
