### ISSUE TITLE
Supercharging not working correctly with graded Material

### ISSUE THREAD

**Issue by ExoFrece** [SilentChaos512/Silent-Gear#171]
- SilentGems-1.15.2-3.5.8+91
- SilentGear-1.15.2-1.9.6+130
- SilentLib-1.15.2-4.6.6+59
- Forge 31.2.5

same issues as SilentChaos512/SilentGems#472 but with graded material
I don't know if it should or not, I'll just report it

- (Link)
https://github.com/SilentChaos512/SilentGems/issues/472
https://i.imgur.com/N2KeiRM.png

**Comment by SilentChaos512** [comment]
Not sure what version this was fixed in, but the fix is in version 1.11.2
