### ISSUE TITLE
Part swapping with compound tips not working

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/Silent-Gear#172]
## Versions

- **Silent Gear**: 1.10.0
- **Silent's Gems**: N/A
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.69
- **Modpack**: N/A
- **Optifine Installed**: hell naw

Reproduced in 1.16.1, but most likely affects 1.15.2 as well.

## Expected Behavior

Crafting a tool with a tip upgrade to apply the upgrade

## Actual Behavior

No result when attempting to craft

**Comment by LlubNek** [comment]
can confirm this affects 1.15.2
![image](https://user-images.githubusercontent.com/313762/88066076-594dc780-cb3b-11ea-8989-2e9037ea145f.png)
(that's lapis and diamond)

SilentGear-1.15.2-1.10.0+131.jar
SilentLib-1.15.2-4.6.6+59.jar
SilentGems-1.15.2-3.6.0+93.jar
forge-31.2.31

**Comment by LlubNek** [comment]
Also affects tips made with a single material and a blueprint

**Comment by revdave33** [comment]
Confirm with single material and tip upgrade via blueprint. 
1.16.2  Forge 32.0.75
SilentGear-1.16.1-1.10.1+135
SilentLib-1.16.1-4.7.0+58
SilentGems-1.16.1-3.6.0+94
