### ISSUE TITLE
Silent's Mechanisms materials not recognized as accepted tool parts.

### ISSUE THREAD

**Issue by DH3499** [SilentChaos512/Silent-Gear#174]
## Versions

- **Silent Gear**: 1.8.2
- **Silent's Gems**: 3.5.5
- **Silent Lib**: 4.6.6
- **Forge**: 31.2.31
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior
Item should be created using selected Mechanisms metal. My experience was with Brass and Bismuth Steel.

## Actual Behavior
End result ends up being blank. The recipe isnt recognized, while vanilla materials and Silents Gem materials are.

(Description here)

## Links/Images

https://pastebin.com/TQz183ir

## Steps to Reproduce the Problem

1. Attempt to make tool/tool head out of Mechanisms metals.

**Comment by SilentChaos512** [comment]
Not seeing any obvious errors in the log file. By the way, those are not the latest versions. Both mods have more recent beta builds.
