### ISSUE TITLE
Blueprint Armor, Gear, Tools don't craftable

### ISSUE THREAD

**Issue by ExoFrece** [SilentChaos512/Silent-Gear#175]
SilentGems-1.15.2-3.5.8+91
SilentGear-1.15.2-1.10.0+131
SilentLib-1.15.2-4.6.6+59
Forge 31.2.5

## Links/Images
https://i.imgur.com/7QhlCZV.png

**Comment by SilentChaos512** [comment]
Possibly a symptom of #176? You should really provide a log file whenever a crash report is not available.

**Comment by ExoFrece** [comment]
Maybe, but I didn't have a error message in the chat but
SilentGems-1.15.2-3.5.8+91-hotfix-479 fixed it thanks
next time i will remember to attach a log 
to make sure you mean the last log?

**Comment by SilentChaos512** [comment]
`latest.log` or `debug.log`. Glad to hear the hotfix fixed the issue.
