### ISSUE TITLE
Rods delete synergy bonus from tool

### ISSUE THREAD

**Issue by ExoFrece** [SilentChaos512/Silent-Gear#177]
- SilentGear-1.15.2-1.10.0+131
- SilentGems-1.15.2-3.5.8+91-hotfix-479
- SilentLib-1.15.2-4.6.6+59
- Forge 31.2.5

## Links/Images
https://i.imgur.com/7QTfFNB.png
https://pastebin.com/XUw7GmPa - debug
https://pastebin.com/4aRBpUVk - log

## Steps to Reproduce the Problem
add rod to tool head

**Comment by ExoFrece** [comment]
Tipped Upgrade does it too, on tools and armor

**Comment by SilentChaos512** [comment]
Removed synergy display value from tools, since it's meaningless in more recent versions.
