### ISSUE TITLE
1.16 Iron Pickaxe Magnetic pushes instead of pulls

### ISSUE THREAD

**Issue by Swiftpaws** [SilentChaos512/Silent-Gear#179]
Magnetic Trait on Iron Pickaxes seems to push items away instead of pulling.

Modlist

- Abnormals-Core-1.16.1-v2.0.0.jar
- AppleSkin-mc1.16.1-forge-1.0.14.jar
- BetterBurning-1.16.1-2.0.2.jar
- BetterCaves-1.16.1-1.0.jar
- BetterMineshaftsForge-1.16.1-1.2.jar
- Buzzier-Bees-1.16.1-2.0.0.jar
- byg-1.0.10.jar
- citadel-1.2.0.jar
- creeperconfetti-3.1.jar
- ExpOreMod-1.16.1-1.0.jar
- FastLeafDecay-v23.jar
- forgemod_VoxelMap-1.10.6b_for_1.16.1.jar
- gravestone-1.16.1-1.0.3.jar
- guardvillagers-1.16.1-1.1.1.jar
- InventoryHud_1.16.1.forge-3.0.1.jar
- invtweaks-1.16.1-1.0.5.jar
- ironchest-1.16.1-11.0.1.jar
- jei-1.16.1-7.0.0.6.jar
- JustEnoughResources-1.16.1-0.11.0.79.jar
- mcw-bridges-1.0.4-mc1.16.1.jar
- mining-helmet-1.16.1-1.0.8.jar
- MouseTweaks-2.13-mc1.16.1.jar
- OptiFine_1.16.1_HD_U_G2_pre4_MOD.jar
- packedup-1.0.15-mc1.16.jar
- Placebo-1.16.1-4.0.1.jar
- prefab-1.6.0.0.jar
- rats-6.0.4-1.16.1.jar
- SilentGear-1.16.1-1.10.0+133.jar
- SilentLib-1.16.1-4.7.0+58.jar
- StorageDrawers-1.16.1-8.0.0.jar
- theoneprobe-1.16-3.0.1-beta.jar
- ToolBelt-1.16.1-1.14.2.jar
- TrashSlot_1.16.1-12.0.1.jar
- travellersboots-1.16.1-1.4.0.jar
- u_team_core-1.16.1-3.1.1.163-SNAPSHOT.jar
- valhelsia_structures-16.0.1.jar
- VanillaTweaks-1.16.1-1.5.29.jar

**Comment by Swiftpaws** [comment]
Might be related to the change here: 
![image](https://user-images.githubusercontent.com/18440081/88102112-5258a080-cb9f-11ea-94b1-f485a893c91a.png)

**Comment by SilentChaos512** [comment]
Yep, called the wrong obfuscated method on the entity.
