### ISSUE TITLE
[Compat] Base Metals

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#18]
Would it be possible to see material support for Base Metals Fantasy materials? They have special effects in their default form you can craft in the normal vanilla style that it would be nice to see in some similar form when used with this mod. I could always make a material pack for them myself... but I cannot add traits.

The materials in question (as listed on their mod page):

Fantasy Metals

Aquarium: Aquarium is a magical alloy of copper, zinc, and prismarine crystals (2:1:3 ratio). Aquarium is _**highly enchantable**_ and tools made of aquarium _**deal extra damage to aquatic mobs**_. Wearing a full suit of aquarium armor allows you to _**breath under water**_.

Cold-Iron (found in the Nether): Cold-Iron is a magical metal that is as _**strong as iron**_. Tools made from Cold Iron are _**extra effective against denizens of the Nether and any creature that is immune to fire**_.

Adamantine (found in the Nether): Adamantine is a rare magical metal that is as _**strong as diamond, maybe even stronger**_. Armor made from Adamantine grants _**resistance to damage**_ and tools made from adamantine are _**extra effective against monsters that have more than 10 hearts of health**_.

Mithril: Mithril is an alloy of alloy of silver, mercury, and cold-iron (2:1:1 ratio). It is as _**strong as steel**_ and Mithral weapons are _**extra effective against undead**_.

Star-Steel (found in the End): Armor made from Star Steel reduces the weight of the wearer, allowing the wearer to _**jump higher and fall slower**_. Star-Steel tools _**slowly repair themselves while held**_.

**Comment by SilentChaos512** [comment]
Added the traits, they are: aquatic, chilled, adamant, holy (this one already existed), and stellar.
