### ISSUE TITLE
[1.15.2] Crafting Station UI Modded Buttons Compatibility

### ISSUE THREAD

**Issue by katubug** [SilentChaos512/Silent-Gear#181]
## What Should Be Added or Changed?
It would be nice if the UI functioned with, or at least did not conflict with, these mod-added UI enhancements. Note: I am not 100% certain those are Quark's inventory management buttons? But I couldn't find what else they might be from.

Here are some screenshots - 

A vanilla chest with Quark's inventory buttons:
![2020-07-21_16 29 28](https://user-images.githubusercontent.com/20935286/88109295-ddba3d80-cb6f-11ea-9da6-2975f2ac150f.png)

A vanilla crafting table with CraftingTweaks' buttons:
![2020-07-21_16 29 24](https://user-images.githubusercontent.com/20935286/88109330-ea3e9600-cb6f-11ea-8a48-99880212f20f.png)

The Crafting Station UI with both mods installed - 
![2020-07-21_16 27 52](https://user-images.githubusercontent.com/20935286/88108929-46ed8100-cb6f-11ea-8327-a4e0aed27a51.png)

## Why Should This Be Done?
It would make the Crafting Station a little more consistent with other crafting/storage UIs. It would be nice to be able to clear the crafting grid easily with Crafting Tweaks, and to easily be able to transfer items into and out of the Station.

However, at the very least, it would be nice if the Quark inventory management buttons weren't overlapping the middle of the crafting grid. Their config *does* have an option to exclude certain UIs using "Print Screen Classnames" ~~but I have no idea what that is, how it works, or if it's even added to the 1.15 version.~~ (I figured it out - it was a config option, the classnames appear in the log) :P So it would be nice if they were compatible out-of-the-box.

Thanks for your time!

**Comment by makkidon** [comment]
Hi! Unrelated but what mod are those gems in your screenshot?

Also, where in the quark config is the exclusion of certain UIs? I can't seem to locate it in the .toml file.

**Comment by katubug** [comment]
Hi! The gems are from this mod: https://www.curseforge.com/minecraft/mc-mods/gems-jewels (also I know, aren't those textures amazing?)

And the option to exclude them is:
```
#A list of screens that don't play well with quark's buttons. Use "Print Screen Classnames" to find the names of any others you'd want to add.
	"Ignored Screens" = ["com.tfar.craftingstation.client.CraftingStationScreen", "com.raoulvdberge.refinedstorage.screen.grid.GridScreen", "com.raoulvdberge.refinedstorage.screen.DiskManipulatorScreen", "com.raoulvdberge.refinedstorage.screen.InterfaceScreen", "net.silentchaos512.gear.block.craftingstation.CraftingStationScreen"]
```
which is on line 14. The Print Screen Classnames option is line 7.

**Comment by makkidon** [comment]
Thanks a lot! They really do look very lovely :)
