### ISSUE TITLE
Crash in net.silentchaos512.equiptooltips.EquipmentStats.getMeleeDamage(EquipmentStats.java:134)

### ISSUE THREAD

**Issue by homosapien97** [SilentChaos512/Silent-Gear#182]
## Versions

- **OS**: Ubuntu 18.04
- **Launcher**: MultiMC
- **Silent Gear**: 1.15.2-1.7.1+94
- **Silent's Gems**: N/A
- **Silent Lib**: 1.15.2-4.6.1+49
- **Forge**: 31.2.5
- **Modpack**: Factory Builder
- **Optifine Installed**: No

## Expected Behavior
Not crashing

## Actual Behavior
Occasionally when hovering over items in JEI (presumably that have Silent Gear stats associated with them) my game will crash. Has only happened a couple times to me, not all the time.

## Links/Images
- https://pastebin.com/RXNTXDib

## Steps to Reproduce the Problem

1. Hover over items with stat annotations for Silent Gear in JEI
2. Keep mousing over different items until you crash

**Comment by SilentChaos512** [comment]
Update Equipment Tooltips to a more recent version
