### ISSUE TITLE
[1.16.1] Reload command '/reload' not working (Reload Failed.) (On a server.) 

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#184]
## Versions
- **Silent Gear**: 1.10.1+135
- **Silent Lib**: 4.7.0+58
- **Forge**: 32.0.75
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3
- **Optifine Installed**: No

## Expected Behavior
That the '/reload' command works as normal.

## Actual Behavior
I was trying to use the command '/reload' while playing but it appears it won't work for whatever reason.

## Links to Logs
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/4968105/latest.log)
[debug.log](https://github.com/SilentChaos512/Silent-Gear/files/4968106/debug.log)

## Steps to Reproduce the Problem (i have no idea really.)
(I have no idea really.)
1. Have SilentGear + SilentLib installed
2. Enter a World / Server
3. Use /reload.
4. ``Reload Failed``

**Comment by SilentChaos512** [comment]
Is this fixed in more recent updates?
