### ISSUE TITLE
[1.12.2] - JEI low fps with Silent Gear

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/Silent-Gear#19]
### Versions
- **Silent Gear**: 1.12.2-0.5.0-60
- **Silent Lib**: 1.12.2-3.0.10-161
- **Forge**: 14.23.5.2796
- **JEI**: 4.14.4.259 and earlier
- **Modpack** (if applicable): Custom

### Expected behavior
fps remains unchanged or less impacted when browsing JEI

### Actual behaviour
When Silent Gear items are visible in JEI, game drops to ~5fps.
Viewing items from other mods doesn't drop fps anywhere near as much. For example, having every animated enchantment book on screen only drops to ~80fps.
All Nuclearcraft fluids ~90fps
Decocraft ~120fps

Using JEI's hide mode, I've narrowed it down to the items highlighted in red in the below image. When any of those items are visible, it causes fps to drop significantly.

When those items are hidden and only the non-highlighted SG items visible, fps sits ~300fps. So it's the tool parts causing the drop.

### Links/Images
https://i.imgur.com/PQs6C9F.jpg

### Steps to reproduce the problem
1. Monitor FPS with either F3 or whatever method
2. Type @ gear or similar in JEI to show Silent Gear items
3. Profit from all the fps you don't have

**Comment by SilentChaos512** [comment]
Hmm, tools should have a much bigger impact than tool heads. Maybe I broke something in the last update. Unfortunately they will hurt FPS no matter what I do, but it shouldn't be _that_ bad.

**Comment by GamertechAU** [comment]
Tested again with 0.5.2+63. Still hits fps hard when I display the tool heads, but drops to around 56fps instead of 5. So something you've done's helped it a fair bit.
