### ISSUE TITLE
Dupe from Salvager block.

### ISSUE THREAD

**Issue by Farza07** [SilentChaos512/Silent-Gear#191]
## Version
SilentGear-1.16.1-1.10.1+135       (idk if its in older or newer versions.)

- **Silent Gear**: SilentGear-1.16.1-1.10.1+135
- **Silent's Gems**: no
- **Silent Lib**: the .70 one i dont remember the exact.
- **Forge**: (couldnt find)
- **Modpack**: ATM 6 (0.18)
- **Optifine Installed**: No

## Expected Behavior
to give 1 ingot and make the recipe not give 4 rods.

## Actual Behavior
It gives 2 ingots per rod and the rod takes 2 ingots to make but the recipe gives 4 rods so you get 4x the stuff. (same issue with grips made with 2 materials)

## Links/Images
https://imgur.com/a/LyqbjVf

## Steps to Reproduce the Problem

1.Make a tool rod
2.Salvage it
3.Repeat

**Comment by SilentChaos512** [comment]
As a temporary fix, I'll make all compound parts except tool heads unsalvageable. The part will just be returned, rather than breaking it down into materials. I'll try to come up with a better solution later.

**Comment by tails1974seeyounextgame** [comment]
yes i do believe this fix totally borked the rest of your mod

**Comment by SilentChaos512** [comment]
@gunmaker How? Need an explanation.

**Comment by Farza07** [comment]
I think it should be 1 ingot for a rod and it gives the 1 ingot back via salvaging also for grips it should take 2 of leather/wool for 1 to avoid duplication.

**Comment by SilentChaos512** [comment]
The solution I came up with is to add fragment items. 8 fragments can craft into the full material item. It will respect the actual amount of material for newly crafted items, but older items may return incorrect amounts if the recipes were modified. Of course, recipes can still be freely modified. There are still a couple of minor issues to work out, but it solves the dupe issue already.
