### ISSUE TITLE
Armor color doesn't match item color

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/Silent-Gear#192]
## Versions

- **Silent Gear**: 2.0.0
- **Silent's Gems**: 3.6.1
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.75

## Issue

Armor model color doesn't match the item color. Item models are also incorrect when overridden with custom textures.

![2020-07-26_18 59 12](https://user-images.githubusercontent.com/5721949/88492716-64a55680-cf72-11ea-8277-c656c36a1ff2.png)

**Comment by ZoMadeStuff** [comment]
Had the same issue in 1.16.4
