### ISSUE TITLE
repair kit recipe arduous long and expensive

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [SilentChaos512/Silent-Gear#195]
basically wishing that the repair kit was more straight forward, had more tiers, and wasnt currently broken being uncraftable cause we cant make daggers as there made only of "compound" in the recipe

**Comment by SilentChaos512** [comment]
Closing this as you're basically just whining about #194. If you have other issues with repair kits, you should be willing to provide more detailed explanations.
