### ISSUE TITLE
[1.16.1] Crossbow doesn't show loaded arrows or update tray icon

### ISSUE THREAD

**Issue by Wiccat** [SilentChaos512/Silent-Gear#196]
## Versions
- **Silent Gear**: 1.16.1-2.0.2+148
- **Silent's Gems**: 1.16.1-3.6.1+96
- **Silent Lib**: 1.16.1-4.7.0+5
- **Forge**: 3.0.72
- **Modpack**: N/A
- **Optifine Installed**: No
- **Resource Pack(s) Installed**: GemsFix.zip

## Expected Behavior
When arrow loads - tray icon shows string pulling back to loaded position, crossbow when loaded shows arrowhead at tip and crossbow icon in tray shows string back and arrow loaded.

## Actual Behavior
Crossbow jiggles a bit - no tray animation, no string change or arrow presented.  Crossbow when aimed show no arrowhead

## Links/Images
- https://www.wiccat.net/files/mc/Unloaded_XBows.jpg
- https://www.wiccat.net/files/mc/Loaded_SGear_XBow.jpg
- https://www.wiccat.net/files/mc/Loaded_Vanilla_XBow.jpg

## Steps to Reproduce the Problem
1. Craft SGear Crossbow (this particular example is one hardened stone, one aluminum steel, one green sapphire, a flax bowstring, and an iron tool rod)
2. Equip crossbow 
3. Load arrow into crossbow (only indication loading is completed is pull "jiggling" stops - no other clue crossbow is ready)

**Comment by SilentChaos512** [comment]
The animation issue is easy enough to fix, and should only exist in 1.16.1.

The bowstring rendering under the body/rod probably exists in 1.15.2 as well. Tried crafting a crossbow and it seems to render in whatever order the parts where placed into the grid (with the exception of the limbs, which are stored first by default due some legacy code).
