### ISSUE TITLE
Game crashing with fix texturepack for gems

### ISSUE THREAD

**Issue by perecnicek** [SilentChaos512/Silent-Gear#198]
## Versions

- **Silent Gear**: x.x.x SilentGear-1.15.2-1.11.0+147
- **Silent's Gems**: x.x.x  SilentGems-1.15.2-3.5.5+88
- **Silent Lib**: x.x.x SilentLib-1.15.2-4.6.6+59
- **Forge**: x.x.x forge-1.15.2-31.2.31
- **Modpack**: N/A 
- **Optifine Installed**: No  no

## Expected Behavior
 

(Description here)

## Actual Behavior

(Description here)
The game randomly crash
## Links/Images

- (Link)
Link to crashlog
https://gist.github.com/perecnicek/df09f1eef73610f9105d810e9aec6ec5
## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Any crashes on version 1.11.2?
