### ISSUE TITLE
Silent shears do no work/collect on vanilla hives

### ISSUE THREAD

**Issue by burshaz** [SilentChaos512/Silent-Gear#200]
## Versions

- **Silent Gear**: 2.0.2
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.98
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Use shears on bee hive to collect

(Description here)

## Actual Behavior
Nothing happens
(Description here)

## Steps to Reproduce the Problem

1. Find vanilla hive ready to collect.
2. Right click with shears(silent gear)
3. Nothing happens

**Comment by SilentChaos512** [comment]
I think I can code a temporary workaround, but it would be better if Forge fixed this.

**Comment by stephen-smith** [comment]
Also seeing this in ATM 6, Forget 32.0.108, Silent Gear 2.1.0+161, Silent Lib 4.7.0+58.

In fact, when I right click a vanilla hive that's ready to collect with my compound shears, it deletes the hive, and the bees and honey within.  (The dripping honey "particle" effect stay around until the end of the animation cycle, then goes away.)

---

Should we open an issue against https://github.com/MinecraftForge/MinecraftForge or one of the other Forge repositories?

**Comment by cech12** [comment]
I think it is a similar issue to that one: https://github.com/MinecraftForge/MinecraftForge/issues/6409
Maybe it will not be fixed in MinecraftForge.

**Comment by stephen-smith** [comment]
Doesn't look like forge is interested in fixing shears+dispenser.  Even if they did, it's unclear that would address the interaction with hives.
