### ISSUE TITLE
[1.15.2] Repair kits cannot be filled.

### ISSUE THREAD

**Issue by ConnCraft** [SilentChaos512/Silent-Gear#202]
## Versions

- **Silent Gear**: 1.8.2+ 109
- **Silent's Gems**: 3.5.5+ 88
- **Silent Lib**: 4.6.6+ 59
- **Forge**: 31.2.33
- **Optifine Installed**: No 

## Expected Behavior
Crafting a repair kit with gems fills the repair kit, similar to photos on the wiki.

## Actual Behavior
The repair kit shows no durability increase. Doing the craft results in voided gems, and the repair kit does not provide repair. Doing so with a tool in the inventory repairs the tool as normal.

## Links/Images
- https://imgur.com/lua9bHa

## Steps to Reproduce the Problem

1. Attempt to fill a repair kit.
2. Fail

**Comment by SilentChaos512** [comment]
Try with a more recent version

**Comment by ConnCraft** [comment]
Updated:
SilentGear 1.11.2+ 153
SilentGems 3.6.2+ 98
Problem fixed. Did not see fix noted in any changelogs.
