### ISSUE TITLE
1.15 part gui still exists 1.16+

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#203]
## Versions

- **Silent Gear**: 2.0.5
- **Silent's Gems**: 3.6.2 
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.70
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

/sg_parts show_gui should be removed as part materials are gone

## Actual Behavior

/sg_parts show_gui still exists and can be used, it pauses the game and lets you move your mouse

## Links/Images

- https://imgur.com/a/wfpzNwW

## Steps to Reproduce the Problem

1. Enter a game
2. Type /sg_parts show_gui
3. Be confused after pressing enter

**Comment by SilentChaos512** [comment]
Definitely need to take a close look at the parts command and all its subcommands. I know it's impossible to build gear with commands due to the recent changes.

**Comment by SilentChaos512** [comment]
Fixed by 7a7763b71246bea8bf3b46db0ec1d6854caddea0
