### ISSUE TITLE
Insta crash when trying to put a tip on my katana

### ISSUE THREAD

**Issue by Gayanfalor** [SilentChaos512/Silent-Gear#206]
## Versions

- **Silent Gear**: SilentGear-1.16.1-2.0.5+155
- **Silent's Gems**: x.x.x 
- **Silent Lib**:SilentLib-1.16.1-4.7.0+58
- **Forge**: 32.0.106
- **Modpack**: ATm6 0.24b
- **Optifine Installed**: No

## Expected Behavior
Working without crashing

(Description here)

## Actual Behavior
Trying to put a lapis manasteel tip upgrade into a katana crash instantly

## Links/Images
https://paste.ee/p/qxTXs

## Steps to Reproduce the Problem
1.Craft a katana sword
2.craft a lapis manasteel tip
3.When both are in crafting table it crash

**Comment by SilentChaos512** [comment]
Are you using any additional data packs or resource packs, or is it just ATM6?

**Comment by Gayanfalor** [comment]
No i use default pack i dont have resource pack, its just atm6 

btw i tried with a sprice wooden katana and it was doing same maybe its coming from the tip and not the sword

**Comment by SilentChaos512** [comment]
Possibly fixed in version 2.0.6
