### ISSUE TITLE
Game crashes when searching for item in JEI

### ISSUE THREAD

**Issue by KMikeeU** [SilentChaos512/Silent-Gear#207]
## Versions
- **Silent Gear**: 1.11.0+147
- **Silent's Gems**: N/A
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.33
- **Modpack**:  Valhelsia 2
- **Optifine Installed**: Yes

## Expected Behavior
Searching for items in JEI

## Actual Behavior
Game sometimes crashes when searching for any item in JEI (Possibly fails to render item description/lore)

## Links/Images
https://hastebin.com/pimulolihi.cs

## Steps to Reproduce the Problem
1. Search for any item in JEI

**Comment by SilentChaos512** [comment]
Duplicate of #198, this crash was fixed in version 1.11.2
