### ISSUE TITLE
Cannot grade Materials not from Vanilla or Silent Gear

### ISSUE THREAD

**Issue by 456Xander** [SilentChaos512/Silent-Gear#208]
## Versions

- **Minecraft**: 1.15.2
- **Silent Gear**: 1.7.5
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.6.4
- **Forge**: 31.2.30
- **Modpack**: [HR: new Beginnings](https://www.curseforge.com/minecraft/modpacks/hr-new-beginnings) 2.4.2  
- **Optifine Installed**: No 

The Material Grader only works for Materials from Vanilla or Silent Gear. Materials from other mods, that have Silent Gear Stats do not work (including from Silent's Mechanisms).

## Expected Behavior
All materials that can be used to craft Silent Gear Tools/Armor should work in the material grader.

## Actual Behavior
Only Vanilla and Silent Gear materials work, other Materials cannot even be put in the top slot of the Grader. Tested with Mekanism Bronze, Silent's Mechanisms Steel, Bismuth Steel, Bismuth Brass and some more. 

## Steps to Reproduce the Problem

1. Open Materials Grader
2. Try to put some Material from a mod in it

**Comment by Funnymeme1** [comment]
i don't think this is a bug? there's 2 seperate material systems in 1.15 and it only works for the system which supports tool rods and such

**Comment by SilentChaos512** [comment]
Please update to a newer version. Materials were very WIP in that version. Newer versions will automatically adapt existing data packs into the new system.
