### ISSUE TITLE
Cannot apply coating to armor (1.16)

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#209]
## Versions

- **Silent Gear**: 2.0.6
- **Silent's Gems**: 3.6.2
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.106
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Netherite coating should apply to armor

## Actual Behavior

Netherite coating when crafted with armor does nothing, even though netherite has stats for armor (knockback resistance)

## Links/Images

- https://imgur.com/a/us6gu5R

## Steps to Reproduce the Problem

1. Craft armor
2. Craft coating
3. Attempt to craft them together

**Comment by Akkiraus** [comment]
Same issue.

**Comment by SilentChaos512** [comment]
This is working in the latest version.
