### ISSUE TITLE
Synergy and grades further decrease negative multipliers

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/Silent-Gear#212]
## Versions

- **Silent Gear**: 2.0.7
- **Silent's Gems**: 3.6.2
- **Silent Lib**: 4.7.0
- **Forge**: 32.0.75
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

Synergy and grades to not negatively impact stats.

## Actual Behavior

Negative stat modifiers become more negative. While this does make sense in a way, I don't believe this is how it should work.

## Links/Images

![2020-08-09_15 57 05](https://user-images.githubusercontent.com/5721949/89741740-70f0df80-da59-11ea-8db6-c19848244a2c.png)

**Comment by vlad0-0** [comment]
I think it would be nice if the negative characteristics do not add up But smooth out each other and strive for 100 percent
