### ISSUE TITLE
Shields Break Permanently

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#214]
## Versions

- **Silent's Gems**: v3.6.2+98
- **Silent Gear**: v1.11.2+153
- **Silent Lib**: v4.6.6+59
- **Forge**: v31.2.31
- **Modpack**: N/A 
- **Optifine Installed**: Yes

## Expected Behavior

- Shields should not break

## Actual Behavior

- Once a shield reaches 1 durability, the shield can permanently break if it blocks another attack. 

## Steps to Reproduce the Problem

1. Craft a shield
2. Break it.

**Comment by SilentChaos512** [comment]
Might get fixed whenever I merge 79f14ef013919497da5930e83b94d8668aa4e8cb into the 1.15 branch. I'll be sure to test it.

**Comment by WenXin20** [comment]
Thanks!
