### ISSUE TITLE
Allow Excavators to create paths in a 3x3

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#215]
## What Should Be Added or Changed?

- Allow Excavators to create paths in a 3x3 when right-clicking unless holding shift, similar to how it can break a 3x3.

## Why Should This Be Done?

- It would make creating paths easier in a large area.

**Comment by SilentChaos512** [comment]
Added as a trait/upgrade in version 2.3.8. Currently have it set to just replace grass blocks, but a data pack could change that.

**Comment by WenXin20** [comment]
Awesome, thanks!
