### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by stokes22b** [SilentChaos512/Silent-Gear#216]
## Versions

- **Silent Gear**: x.x.x
- **Silent's Gems**: x.x.x 
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by RemagOfficial** [comment]
good bug report

**Comment by stokes22b** [comment]
> good bug report

accidentally hit enter, actual report in next one. Tried to delete

**Comment by SilentChaos512** [comment]
You can edit the original post, btw.
