### ISSUE TITLE
Can't craft any armor

### ISSUE THREAD

**Issue by stokes22b** [SilentChaos512/Silent-Gear#217]
## Versions

- **Silent Gear**: 1.16.1
- **Silent's Gems**: 1.161  
- **Silent Lib**: 1.16.1
- **Forge**: 1.16.1
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Placing any kind of armor blueprint with the appropriate amount of the proper material will craft that piece of armor.

## Actual Behavior

When you place the items correctly and hover cursor over the possible armor creation, the description of the armor says "seems to contain invalid parts, stats are locked" and if the armor is crafted and put on it has no effect and has some kind of texture error that makes a pink block.

## Links/Images

![image](https://user-images.githubusercontent.com/69507455/89882950-c70e7180-db84-11ea-949a-da5db3c78b9b.png)
![image](https://user-images.githubusercontent.com/69507455/89882986-d097d980-db84-11ea-84e5-dafa14ed9bf6.png) 
![image](https://user-images.githubusercontent.com/69507455/89883639-a72b7d80-db85-11ea-8b6a-5818b5f7f7b3.png)

## Steps to Reproduce the Problem

1. Attempt to craft any kid of armor with armor blueprint
2.
3.

**Comment by WhitePhant0m** [comment]
1. Versions aren't just '1.16.1' you need to specify what version of the mod you are using, like this 
SilentGear-1.16.1-2.0.9+159
2. There is an updated version released 21h as of this moment when I commented that fixes your issue.
