### ISSUE TITLE
crash with blueprint books? (1.16)

### ISSUE THREAD

**Issue by zymex22** [SilentChaos512/Silent-Gear#218]
Hello i have a stange crash im using valhelsia pack but added a few more mods, (silent gear for one)

and after i updated all mods i get this crash when accesing chests, barrels and iron/diamond chests.

https://pastebin.com/PnXYWF8C
im not sure if its related to silent gear but asked in valhelsia discord and author said i should maybe report it here.

he said it had something to do with blueprint book. not sure what

**Comment by zymex22** [comment]
oh its when i hover over my blueprint book with the mouse it happens

**Comment by SilentChaos512** [comment]
Not sure how the selected slot got out of range, but I should be able to fix it. As a temporary workaround, you could edit the item's NBT to change the selected slot. The NBT key is "Selected".
