### ISSUE TITLE
Crashing when rightclicking the blueprint you get on world-spawn. (new world)

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#22]
### Versions

- **Silent Gear**: SilentGear-1.13.2-1.0.0+3
- **Silent Lib**: SilentLib-1.13.2-4.0.0+2
- **Forge**: 25.0.54
- **Modpack** (if applicable): Custom

### Expected behavior
 Game not crashing when right clicking the blueprint package i get on world-start.

### Actual behaviour
The game closes & crashes when opening the Blueprint Package i get on world-start.

### Links/Images
Crashlog: [Pastebin](https://pastebin.com/SbCecb1q)

### Steps to reproduce the problem

1. Load into a world
2. Open the blueprint you get on world-spawn
3. Game closes, crashed.

**Comment by SilentChaos512** [comment]
Temporary workaround: make sure you are not looking at a block when using it.

**Comment by Gbergz** [comment]
Alright yes, that worked. 
However is the "Crafting Station" supposed to not be opened? Nothing happens on right-click.

And also i don't think the textures are working properly on items, just created a stone-pickaxe and it does appear to look like glass pickaxe, unless this intended i'm sorry.
Also the names Tool Tip seems not to have a Lang file, the text in the middle. Look at screenshot below!

EDIT: Also can't find any of the tools in JEI (REI), again intended maybe? Idk.

Screenshot: [Gyazo Img](https://gyazo.com/1e5b76cdb1f5a8876b2d5523c6096139)
GIF of Crafting Station: [Gyazo GIF](https://i.gyazo.com/c0803b1b4ed2e89abf72cf34cc274c8f.mp4)

**Comment by SilentChaos512** [comment]
I am aware of both of those. All the blocks need some work. Gear models do
not load. I haven't asked about it, but it seems Forge is missing some
model patches or something.

**Comment by hedgesbrian384-prog** [comment]
> ### **`
`**

**Comment by hedgesbrian384-prog** [comment]
### ****
