### ISSUE TITLE
Nether+ compatibility 

### ISSUE THREAD

**Issue by RemagOfficial** [SilentChaos512/Silent-Gear#220]
## What Should Be Added or Changed?

- you should add compatibility for Nether+ in 1.15.2 or lower versions as the mod adds the nether update to 1.12.2-1.15.2 

## Why Should This Be Done?

- this would allow for netherite coating in older versions of the mod
mod link: https://www.curseforge.com/minecraft/mc-mods/netherplus

**Comment by SilentChaos512** [comment]
Not willing to do this, sorry. I'd rather keep 1.15.2 stable, so I won't add major new features.
