### ISSUE TITLE
Missing Texture after Tip Upgrade

### ISSUE THREAD

**Issue by GamerXD8991** [SilentChaos512/Silent-Gear#226]
## Versions

- **Silent Gear**: 2.1.0+161
- **Silent's Gems**: N/A
- **Silent Lib**: 4.7.0+58
- **Forge**: 31.0.108
- **Modpack**: All the Mods 6 - 1.16
- **Optifine Installed**: Yes (and OptiForge)

## Expected Behavior
Yellowish Boots as item Sprite with Blue (or something like that)

## Actual Behavior
Boots go from Yellowish Textured to Missing-Texture Sprite but instead of the pink it's Blue (See Picture). 
These are Gold-Gold-Osmium-Osmium Boots (Hence the Yellowish. See Picture) Osmium added by Mekanism.
In-World the Boots render as if no Tip Upgrade is applied 

## Links/Images

- Before 
![GoldBoots0](https://user-images.githubusercontent.com/40356877/91970005-50920900-ed17-11ea-8257-ea4264ed2d06.png)

- After
![GoldBoots](https://user-images.githubusercontent.com/40356877/91969742-dfeaec80-ed16-11ea-8f22-0f3bbc69c6b2.png)

- In-World Render 
![GoldBootsRender](https://user-images.githubusercontent.com/40356877/91970242-a5358400-ed17-11ea-91d4-ddebf17b2117.png)

## Steps to Reproduce the Problem

1. Create Boots fromBlueprint with Gold, Gold, Osmium, Osmium
2. Add Lapis Lazuli Tip Upgrade

**Comment by mettlephaontoms** [comment]
I have this issue too, even without optifine.
