### ISSUE TITLE
Compound Paxel cannot strip logs.

### ISSUE THREAD

**Issue by stephen-smith** [SilentChaos512/Silent-Gear#227]
## Versions

- **Silent Gear**: 2.1.0+161
- **Silent's Gems**: N/A
- **Silent Lib**: 4.7.0+58
- **Forge**: 32.0.108
- **Modpack**: All the Mods 6
- **Optifine Installed**: No

## Expected Behavior

Compound paxel can strip bark from logs, just like a plain paxel or compound axe.

## Actual Behavior

* Diamond Axe (Vanilla) strips logs.  (Right-click logs, may need to hold for just a moment)
* Diamond Paxel (Mekanism Tools) strips logs.
* Compound Axe (Head: 3xDiamond; Tool Rod: 2xDiamond) strips logs.
* Compound Paxel (Head: 5xDiamond: Tool Rod: 2xDiamond) cannot strip logs.

## Steps to Reproduce the Problem

1. Install ATM 6
2. Create Compound Paxel via blueprint or template
3. Fail to strip logs.

**Comment by KellAtreides** [comment]
Same issue if you have an axe with the trait Vulcan.

**Comment by SilentChaos512** [comment]
Traits taking priority over a tool's natural use action is intended behavior. And the traits that do that are rare enough that I'm not really concerned about changing it.
