### ISSUE TITLE
Use words instead of numbers to describe mining level

### ISSUE THREAD

**Issue by AngleWyrm10** [SilentChaos512/Silent-Gear#228]
#### What Should Be Added or Changed?
Change the display of tool mining levels to descriptive words, such as "diamond", "obsidian", "iron", etc

#### Why Should This Be Done?
It is difficult to tell what a particular gem can mine when all it says is "mining level: 2" or similar

**Comment by AbsorbingSafe11** [comment]
As some mods change the hardness value of certain blocks like stone, ores and obsidian, numbers are more consistent.
As an example, stone pickaxes in default minecraft can mine iron ore, so they would be mining level 1 (wood is 0), but some mods change iron ore to require copper or bronze to mine and then the player would be confused.
Also, the numerical system works better when some mods add higher than obsidian mining levels. (like Tinkers with cobalt and ardite)

**Comment by SilentChaos512** [comment]
I thought the default harvest levels for vanilla blocks were well-known. Still, I don't mind adding a hint. The numerical value will still be displayed.
