### ISSUE TITLE
Duplication of blueprints 

### ISSUE THREAD

**Issue by RayzoRayy** [SilentChaos512/Silent-Gear#23]
### Versions

- **Silent Gear**: SilentGear-1.13.2-1.0.0+3
- **Silent Lib**: SilentLib-1.13.2-4.0.0+2
- **Forge**: 25.0.59
- **Minecraft**: 1.13.2

### Expected behavior

To not spawn in and have an extra blueprint every time

- 

### Actual behaviour

Each time I re-log into my world, I spawn with a new blueprint, of which I already have when I made the world the very first time.
- 

### Links/Images

No crash

- 

### Steps to reproduce the problem

1.Load Minecraft World
2.Save and quit the world
3.Re-load the world and youll have another blueprint

**Comment by SilentChaos512** [comment]
I think this is an issue with Forge not saving entity data correctly. I'll take another look to make sure I didn't miss something.

**Comment by RayzoRayy** [comment]
Ah okay. I wasn't sure what it was caused by so I figured i'd report just in case. :)
