### ISSUE TITLE
Thermal Compatibility - "Failure to load Data Packs"

### ISSUE THREAD

**Issue by MokahTGS** [SilentChaos512/Silent-Gear#230]
## Versions

- SilentGear-1.15.2-1.11.3+160.jar
- SilentGems-1.15.2-3.6.2+98.jar
- SilentLib-1.15.2-4.6.6+59.jar
- thermal-1.15.2-0.2.5b.jar
- thermal_cultivation-1.15.2-0.2.4b.jar
- thermal_expansion-1.15.2-0.2.5b.jar
- thermal_innovation-1.15.2-0.2.4b.jar
- thermal_locomotion-1.15.2-0.2.4b.jar
- cofh_core-1.15.2-0.6.4b.jar
- Forge 31.2.41

## Actual Behavior

Loading a SP game produces this error in the chat.

Screen Shot: https://www.dropbox.com/s/mwh970s4ks16f7e/2020-09-19_14.04.21.png?dl=0
Log Error: https://pastebin.com/XENsz5RC
Full Mod List:  https://pastebin.com/t6Egwb8q

**Comment by SilentChaos512** [comment]
Nothing I can do about it, needs to be reported to whatever mod is breaking the data loading process.

**Comment by MokahTGS** [comment]
I'm talking with the Thermal people and it seems this is a red herring.  Another mod seems to be making messes.
