### ISSUE TITLE
Make armor cap configurable

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [SilentChaos512/Silent-Gear#231]
## What Should Be Added or Changed?
Right now each armor piece has a max cap of 40 (which corresponds to different amount of armor points based on whether it is a helmet, chestplate, leggings or boots).

There should be an option in the config to change or even completely remove this cap.

## Why Should This Be Done?
For starters, it makes powerful materials (SSS grade + max supercharged) not completely useless in armor making.
Additionally, it would allow for some interesting armor sets, like wearing only a helmet and having a protection equivalent to a full diamond set (or, in more reasonable conditions, having a jetpack and some goggles while also having quite a bit of armor).

However, the real benefits are when you combine it with [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix), which removes armor cap. This means that once the cap from silent gear is removed as well, it would be possible to create extremely powerful armor (which would counter balance extremely powerful weapons which are already craftable).

Making this configurable will allow players and pack makers for more possibilities without forcing the change on them.

**Comment by SilentChaos512** [comment]
Decided to just increase the caps on most stats to `Integer.MAX_VALUE` (~2 billion). Most other other stats already had extremely high caps anyway.
