### ISSUE TITLE
[1.16.3] Log gets spammed with an error, 150mb log, maybe makes loading take longer?

### ISSUE THREAD

**Issue by WhitePhant0m** [SilentChaos512/Silent-Gear#232]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.2.0+164.jar
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61.jar
- **Forge**: 34.1.1
- **Modpack**: [ATM6 1.16.3 prev3](https://cdn.discordapp.com/attachments/718184881628381284/761317643327373343/All_the_Mods_6-1.1.0-Prev3.zip)
- **Optifine Installed**: Yes

## Expected Behavior
not get my log spammed by this mod and NOT make it 150mb in a couple minutes

## Actual Behavior
log gets spammed with [this](https://paste.gg/p/wphant0m/c766105d37a4438cb07019f47350ffab) 

## Links/Images
[Here](https://drive.google.com/file/d/1fR43WAAAnglr9FRyHzAhLaqHSjXrP8kd/view?usp=sharing) is the full log(had to upload to drive since it was 150mb)

## Steps to Reproduce the Problem
Just booted up the pack and joined a server, i don't get the spam 100% of the time, no clue how to repeat.

**Comment by SilentChaos512** [comment]
The "Tag silentgear:grader_catalysts used before it was bound" looks very similar to the error in #224. Might be fixed next update when I remove the grader catalyst tooltip line. Sadly I don't know any way to fix it other than removing the tooltip hint.
