### ISSUE TITLE
[1.16.3] Missing textures and enchantability for helm, legs, boots, chest is fine.

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/Silent-Gear#233]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.2.0+164
- **Silent's Gems**: x.x.x 
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61
- **Forge**: 34.1.5
- **Modpack**: TownCraft TWO Test
- **Optifine Installed**: No 

## Expected Behavior
icon shown and able to enchant.

(Description here)

## Actual Behavior
after crafting a crimpson iron helm, legs and boots there is no icon and you can't enchant them.  The chestplace works great.

(Description here)

## Links/Images

![2020-10-04_23 53 38](https://user-images.githubusercontent.com/4427684/95045407-3b562480-069f-11eb-946d-92b740b84c4c.png)
![2020-10-04_23 53 49](https://user-images.githubusercontent.com/4427684/95045410-3beebb00-069f-11eb-9ffa-25f0caab9bcf.png)
![2020-10-04_23 54 38](https://user-images.githubusercontent.com/4427684/95045411-3c875180-069f-11eb-883e-11dd7c276f9e.png)
![2020-10-04_23 54 50](https://user-images.githubusercontent.com/4427684/95045413-3c875180-069f-11eb-9d5f-ea68f676c160.png)

**Comment by ClaudiusMinimus** [comment]
Same issue with Tip Upgrade 
![tip-grade](https://user-images.githubusercontent.com/17887664/96077136-43b31a00-0e6c-11eb-9e73-9414ed9d4aee.png)

**Comment by syelents** [comment]
I also have this same problem.. It fixes when I reload resources.

**Comment by Joshernoob** [comment]
![2020-11-06_21 52 25](https://user-images.githubusercontent.com/64944433/98430277-66ef7480-207a-11eb-9eef-a1eb2c86a8dc.png)
seems this is for most parts as iv had it happen to a few and then them fix themself on reload and then reload again and it bug
