### ISSUE TITLE
[1.16.3][Forge] Jei not loading first time on server(min mods)

### ISSUE THREAD

**Issue by Prophious** [SilentChaos512/Silent-Gear#234]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.2.0+164
- **Silent's Gems**: N/A 
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61
- **Forge**: 1.16.3-34.1.9
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

start new server world and push inventory button to see Jei (which is on by default)

## Actual Behavior

start new server world then push inventory button to see Jei, do not see Jei, relog in to server then can see Jei

## Links/Images

https://github.com/mezz/JustEnoughItems/issues/2101

## Steps to Reproduce the Problem

1.start server with 3 mods, silent gear/lib and Jei, new world 
2.log in to server from separate client, with just the same 3 mods 
3.push inventory key(can try ctrl+o, default keys for display jei, while in inventory screen)

**Comment by SilentChaos512** [comment]
None of the logs on that issue seem to mention Silent Gear. Please provide a relevant log or the issue will be closed.

**Comment by Prophious** [comment]
server:
[debug.log](https://github.com/SilentChaos512/Silent-Gear/files/5329410/debug.log)
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/5329411/latest.log)

client:
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/5329417/latest.log)


java is 64bit v261 client launched through twitch desktop app with 8gb of ram allocated

**Comment by SilentChaos512** [comment]
"Tag silentgear:grader_catalysts used before it was bound". This must be another symptom of #224.

**Comment by ProsperCraft** [comment]
We don't see JEI when logging in to the server as well, the workaround we have been doing is to log in to a single player world, then log in to the server.

Tag silentgear:grader_catalysts used before it was bound

https://gist.githubusercontent.com/digghair/51d7818505d82df2dd4d44ed51d2d2f1/raw/6ac0c855603ff2e3c79d8be7c825fb52c6bcec22/gistfile1.txt

**Comment by ProsperCraft** [comment]
Thank you for fixing, I was just going to link this seemingly related issue - https://github.com/SilentChaos512/Silent-Gear/issues/52
