### ISSUE TITLE
[1.15.2] Crash related to Blueprint Book

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silent-Gear#236]
## Versions

- **Silent Gear**: 1.11.3+160
- **Silent's Gems**: 3.6.2+98
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.43
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/the-new-adventure/files/3068481
- **Optifine Installed**: Yes

## Expected Behavior
Not to crash

## Actual Behavior
Hovering over the Blueprint Book causes a client crash. Also, interacting with storage (chests, barrels) with Blueprint Book in hotbar results in same crash.

Looks like this issue is similar to #218 , except that I am playing Minecraft 1.15.2.

## Links/Images
https://pastebin.com/MAam6h8Z

## Steps to Reproduce the Problem
1. Have Blueprint Book nearly 3/4 full of blueprints.
2. Hover over book or interact with barrels/chests.

**Comment by Partonetrain** [comment]
Does this happen without Optifine?

**Comment by SilentChaos512** [comment]
If this is the same bug, it's caused by Ctrl+clicking a slot in the player's inventory, which causes the selected slot index to go out of bounds. Editing the book's NBT to set the selected slot to a valid number (like 0) is one possible workaround.

**Comment by ghost** [comment]
I edited the book's NBT and am able to enter the world and interact with chests and barrels etc. I have not yet tried to reproduce the problem without Optifine.
