### ISSUE TITLE
Repair Kit issue

### ISSUE THREAD

**Issue by Blntswrd** [SilentChaos512/Silent-Gear#237]
## Versions

- **Silent Gear**: 1.6.3-2.2.0+164
- **Silent's Gems**: N/A
- **Silent Lib**: 1.16.3-4.8.1+61
- **Forge**: 34.1.12
- **Modpack**: All The Mods 6 1.1.0  
- **Optifine Installed**: No 

## Expected Behavior

The repair kit to act like I put in the correct amount of materials.

## Actual Behavior

When the repair kit is put in first and materials put into the crafting grid after it will only act like the first one is there but when the repair kit is taken out it will use all materials but the material count will only go up by one

## Links/Images

https://imgur.com/UDBKMfg

## Steps to Reproduce the Problem

1. Put repair kit into crafting grid, inventory or crafting table does not matter.
2. Put materials into crafting grid.
3. Mouse over repair kit.

**Comment by SilentChaos512** [comment]
Working correctly for me, although I tested on Forge 34.1.1. Maybe another mod is interfering with crafting somehow. Or if you are playing on a server, maybe that has something to do with it?

**Comment by Blntswrd** [comment]
Playing on single player with a modified version of the modpack I said I was using. I did however test in a non-edited version and was able to reproduce it. Guess I'll just tell the modpack authors

**Comment by FreeFull** [comment]
I have ran into this issue as well, while working on my own modpack. Could it possibly be a bad interaction with FastWorkbench?

**Comment by SilentChaos512** [comment]
I would not be surprised. It must be something that is modifying the crafting system.

**Comment by FreeFull** [comment]
After removing the FastWorkbench mod from my pack, I can't reproduce the issue any more, so that's probably it. Not sure if fixing this would fit better into Silent Gear's or into FastWorkbench's code, though.

**Comment by SilentChaos512** [comment]
I doubt I could fix it on my end. I'm using the crafting system as intended.
