### ISSUE TITLE
Directly replacing materials in a crafting table does not update the sprite or stats of an item.

### ISSUE THREAD

**Issue by gheckman** [SilentChaos512/Silent-Gear#239]
# Versions
Modpack: All The Mods 6
Minecraft 1.16.3
Forge: 34.1.18
Silent Lib: 1.16.3-4.8.1+61
Silent Gear: 1.6.3-2.3.0+165
Silent's Gems: No
Optifine Installed: No

# Expected Behavior
Sprites and their stats should update when materials are replaced in the crafting table.

# Actual Behavior
Sprites and stats retain their original values when materials are replaced.

# Links/Images
https://imgur.com/a/u16Qfts

# Steps to Reproduce the Problem
Put blueprint into crafting table.
Add materials that satisfy that blueprint. (Put 3 diamonds and a stick in with a pickaxe blueprint)
Directly replace some of the materials with different ones that also satisfy that blueprint. (Replace the diamonds with cobblestone)
Craft the item. It will have the stats and sprite from the original materials, while consuming the replacements. (Grab your diamond pick that cost 3 cobblestone) 

Note that this does not occur when removing and adding materials, only when directly replacing.

**Comment by SilentChaos512** [comment]
Probably another symptom of whatever is causing #237. Sounds like some mod is screwing with the crafting system. This works correctly with just Gear/Lib installled.

**Comment by V2LenKagamine** [comment]
Can confirm this issue still exists in ATM6
