### ISSUE TITLE
Repair Kit Not Repairing Armor

### ISSUE THREAD

**Issue by jesse-projects** [SilentChaos512/Silent-Gear#243]
## Versions

- **Silent Gear**: 1.15.2-1.11.3+160
- **Silent's Gems**: N/A
- **Silent Lib**: 1.15.2-4.6.6+59
- **Silent's Mechanisms*: 1.15.2-0.8.0+59
- **Forge**: 31.2.36
- **Modpack**: Valhelsia 2 v2.2.10
- **Optifine Installed**: No 

## Expected Behavior
Put a repair kit (containing material of equal Tier) and armor (made of the same Tier of material in the repair kit) in the crafting grid and get armor with increased durability out of the crafting output

(Description here)

## Actual Behavior
I have a sturdy repair kit with 32 obsidian (Tier 3, ungraded) and obsidian armor (made with varying grades of obsidian and nothing else). When I put them in the crafting grid together, I get my armor piece in the output, but with no increase in durability, and no material is used from the repair kit.

The same repair kit successfully repairs my obsidian tools.

I have given myself a Crimson repair kit and filled it with both obsidian (Tier 3) and signalum (Tier 4) and I get the same behavior, no repair is made to my armor.

However, when I use the same material and armor in an anvil, it DOES successfully repair.

(Description here)

## Links/Images

- [Repair kit not working](https://i.imgur.com/gtyyHZz.png)

## Steps to Reproduce the Problem

1. Damage obsidian armor
2. Fill a repair kit with obsidian
3. Craft the repair kit with the damaged armor

**Comment by SilentChaos512** [comment]
For my future reference, this was fixed in 1.16 a while back and only affects obsidian
