### ISSUE TITLE
[1.12.2]Tool Identifyers Changed in Newer Versions?

### ISSUE THREAD

**Issue by craft-lover** [SilentChaos512/Silent-Gear#249]
I am a novice developer working on some custom materials for my playthrough of R.A.D. I want my new materials to be as true to the sources as possible, including tool and armour restrictions. Unfortunately, the higher classifycations listed in the [Gear Types page](https://github.com/SilentChaos512/Silent-Gear/wiki/Gear-Types) do not appear to work. When I type the standard classifyers manually, all appears to work. My question is, therefore, two-fold: "Are the tiered classifyers a recent addition, or am I doing something wrong?"
The following is a excerpt from my file for Twilight Forest's Naga Scales. 

`    "availability": {
        "enabled": true,
        "tier": 2,
        "tool_blacklist": ["harvest_tool","weapon"]
    }`

**Comment by SilentChaos512** [comment]
All the documentation is for recent versions, not the early betas that 1.12 got. No support is provided for those versions.

**Comment by craft-lover** [comment]
Fair enough, I was just curious.
