### ISSUE TITLE
Friend cant connect via lan

### ISSUE THREAD

**Issue by cdebo9** [SilentChaos512/Silent-Gear#25]
https://pastebin.com/hWMUeHmp
When my friend attempts to connect with SilentGear and SilentLib installed, it joins her the instantly disconnects her and gives the error at the bottom of the log.

**Comment by SilentChaos512** [comment]
Tracked this down to a Forge bug (https://github.com/MinecraftForge/MinecraftForge/issues/5577). I'll see if I can come up with some temporary workaround. Otherwise, we might have to wait for a Forge fix.

**Comment by SilentChaos512** [comment]
Version 1.0.3 should allow LAN games to work. Some info is not getting synced to the client, but everything seems to be functioning at least. Tools and such won't look right, but I believe that's a separate issue.
