### ISSUE TITLE
Missing Upgrades?

### ISSUE THREAD

**Issue by mrkarp** [SilentChaos512/Silent-Gear#254]
## Versions
- **Silent Gear**: 2.3.5
- **Silent's Gems**: NA
- **Silent Lib**: 4.9.0
- **Forge**: 34.1.42
- **Modpack**: Valhelsia 3 (With SilentGear added)
- **Optifine Installed**: No

## Expected Behavior
Available upgrades show as recipes and or are craftable.

## Actual Behavior
Missing recipe's and actual items.
![image](https://user-images.githubusercontent.com/5105074/99178858-195bb300-26dd-11eb-8048-e9c59719a8dd.png)

## Steps to Reproduce the Problem
1. Copy Valhelsia 3 modpack profile
2. Unlock and "Get more content"
3. Install SilentGear and SilentLib (dependency)
4. Boot, everything is available except upgrades (see screenshot above)
5. All functionality is available except upgrades

If I'm being dumb and missing a dependency or a known conflict, I apologize!!

**Comment by SilentChaos512** [comment]
What upgrades are you referring to?

**Comment by mrkarp** [comment]
Are there not upgrades you can craft to apply to the tools? Using the "Upgrade Base", I've seen others combine them with lapis, redstone, etc. to create upgrades to apply to the tools.

**Comment by SilentChaos512** [comment]
Tip upgrades are still a thing, but they are compound parts now. They are made with blueprints now and the upgrade bases are largely unused. No way to show every possible combination in JEI because materials load much later. Just look for materials that support the "Tip" part type.
