### ISSUE TITLE
When crafting a Silent Gear bow or crossbow, the string is no longer on the weapon but it still works

### ISSUE THREAD

**Issue by Minecrafter1913** [SilentChaos512/Silent-Gear#257]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.3.5+170.jar
- **Silent's Gems**: SilentGems-1.16.3-3.7.3+106.jar
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63.jar
- **Forge**: 1.16.3
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

The bowstrings for the crossbow and bow are actually visible while in inventory/hot-bar/in hand

## Actual Behavior

When crafting a bow from the Silent Gear mod, as soon as you craft it the string is no longer visible on the bow/crossbow, it is still fireable but the string and arrow do not show up in the bow/crossbow.

## Steps to Reproduce the Problem

1. Grab any crafting materials that can be used to craft a bow/crossbow
2. add the blueprint for one
3.Click the item inside the craft square

**Comment by SilentChaos512** [comment]
Seems to be working just fine for me, going to need more information. Are specific materials causing this? Can you reproduce the issue with just Silent Gear/Lib installed? Or anything else you can think of?

**Comment by SilentChaos512** [comment]
Please check if the issue still exists in version 2.3.7

**Comment by Minecrafter1913** [comment]
Hmm, most likely an issue on my end, I will look further into it though,
but to give more context, whenever I craft a bow or crossbow using the
blueprints and everything, once I craft it the string disappears, it still
works but the string texture goes completely missing.
