### ISSUE TITLE
Server Crash with Newest Version

### ISSUE THREAD

**Issue by TwilightPSN** [SilentChaos512/Silent-Gear#261]
## Versions
- **Silent Gear**: 2.3.7+175
- **Silent's Gems**: 3.7.3+106
- **Silent Lib**: 4.9.0+63
- **Forge**: 1.16.4 - 35.0.16
- **Optifine Installed**: No 

## Actual Behavior
Mod crashes on dedicated server on boot

## Links/Images
https://pastebin.com/A2pPUBWS

**Comment by SilentChaos512** [comment]
Hotfix should be available on Curse in a few minutes. Clients should not need to update.
