### ISSUE TITLE
`silentgear:flax_seeds` misspelled as `silentgear:flaxseeds` in crop recipe

### ISSUE THREAD

**Issue by FreeFull** [SilentChaos512/Silent-Gear#263]
## Versions

- **Silent Gear**: 2.3.7
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.9.0
- **Forge**: 35.1.0
- **Minecraft**: 1.16.4
- **Modpack**: N/A 
- **Optifine Installed**: No 

When loading a world with Silent Gear + Botany Pots (6.0.6) installed, the following error appears:
```
[20:44:31] [Render thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe silentgear:crops/flax
com.google.gson.JsonSyntaxException: Unknown item 'silentgear:flaxseeds'
```
Looking at `src/main/resources/data/silentgear/recipes/crops/flax.json`, it indeed seems that it has `silentgear:flaxseeds` instead of `silentgear:flax_seeds`. Despite this, Botany Pots still seems to successfully pick up a recipe for flax anyway, so the error isn't observable without looking at Minecraft's logs.

**Comment by FreeFull** [comment]
The file still seems to have `flaxseeds` on line 10. I also created the issue since I'm not sure if having the file is necessary, at all.

**Comment by SilentChaos512** [comment]
Okay, you're right. Botany Pots added their own recipe at some point, so I'll just remove mine.
