### ISSUE TITLE
Quality of Life Changes

### ISSUE THREAD

**Issue by unmoving-javi** [SilentChaos512/Silent-Gear#264]
Long story short, I've used this mod for a while now and it's great, but there's a few things that REALLY get on my nerves. Very small things, of course. I was asked to make an issue on the Github about these, so here they are!

1. Config option to remove sound when tool's durability lowers (NOT the sound when it breaks)
2. Config option to remove chat message when a tool breaks

(Side note, it seems like the basic mod metals datapack is either built into this mod now or is built into Thermal Expansion, and will cause conflicts if the datapack is installed on top of the default stuff. Might want to update the CF page or datapack page to reflect this.)

**Comment by SilentChaos512** [comment]
The first option is already in the client config. The second I will have to be added to the common config instead.

**Comment by unmoving-javi** [comment]
Thank you for the quick response! Will be looking forward to the new options.
