### ISSUE TITLE
[1.13.2] Diamond-tipped upgrade does not upgrade tool

### ISSUE THREAD

**Issue by revdave33** [SilentChaos512/Silent-Gear#27]
### Versions

- **Silent Gear**: 1.13.2-1.0.11b+23
- **Silent Lib**: 1.13.2-4.0.9+24
- **Forge**:  forge-25.0.193
- **Modpack** (if applicable): Custom

### Expected behavior
I wanted to apply the Diamond-tipped Upgrade to a pickaxe I had made using various gems. 

The application of the upgrade did not affect the Harvest Level or the durability of the tool.

**Comment by SilentChaos512** [comment]
I believe I have found the cause. I'll release a new build later today. Thanks for reporting.
