### ISSUE TITLE
1.16.4 - No crafting station, really frustrating.

### ISSUE THREAD

**Issue by ghegi** [SilentChaos512/Silent-Gear#273]
## Versions

I'm on version 1.16.4.

- **Silent Gear**: SilentGear-1.16.3-2.4.0+183
- **Silent's Gems**:  SilentGems-1.16.3-3.7.3+106
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 35.1.0
- **Modpack**: N/A 
- **Optifine Installed**: Yes

## Expected Behavior

Have it so that I can see the crafting station or have a way to obtain it.

## Actual Behavior

I have a server, I installed like 30+ mods on it. BoP, Quark, Pickle Tweaks, Curios, Charm, Tetra, etc. like the good stuff. Then I installed the silent's gear because I heard it was good. Looked up some tutorials but when they told me to get a crafting station, I could not find it anywhere. Not in JEI, I tried the /give command nothing works, couldn't locate it. Even tried crafting it but nope. Nothing.

## Links/Images

- [Screenshots to missing crafting station along with the list of my mods installed](https://imgur.com/a/OLnvfvj)

**Comment by SilentChaos512** [comment]
The crafting station was removed to a dupe bug I could not solve. I recommend the blueprint book if you are looking for blueprint storage. If you want material information, the best solution right now is to use the `/sgear_mats dump` command on a singleplayer creative world. The command generates a file which can be imported into any spreadsheet program.
