### ISSUE TITLE
Bracelets dont go in the curios inventory

### ISSUE THREAD

**Issue by SnivyLlama** [SilentChaos512/Silent-Gear#275]
## Versions

- **Silent Gear**: 1.16.3-2.4.1+184
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 34.1.42
- **Optifine Installed**: No

## Expected Behavior

I expected the bracelet to go into the bracelet curios slot.

## Actual Behavior

When I try putting it in, nothing happens.

## Links/Images

None

## Steps to Reproduce the Problem

1. Make a bracelet, dosent matter what its made of or is it has an ordan
2. Try putting it in the bracelet slot and see it fail. Even right clicking to put it on dosent work

**Comment by SilentChaos512** [comment]
Looks like I forgot to generate the item tag file for bracelets. That will be easy to fix.

**Comment by SnivyLlama** [comment]
And also I just realized, bracelets don't have a template/blueprint recipe. I was thinking about making another issue but I am just going to put it here itself.
