### ISSUE TITLE
[1.16.4] Badly Compressed Packet Error

### ISSUE THREAD

**Issue by MacAttack-UK** [SilentChaos512/Silent-Gear#276]
I've Re-Opened this issue as it can be recreated by adding SilentGear+Lib to the new DW20 pack and trying to join a newly created world.

- **Silent Gear**: SilentGear-1.16.3-2.4.5+191
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: forge-1.16.4-35.1.13
- **Modpack**: FTB Presents Direwolf20 1.16 v1.1.0
- **Optifine Installed**: No

## Expected Behavior
To be able to join a dedicated server without this error

![mc-packet-error](https://user-images.githubusercontent.com/13574886/101207267-4958ff00-3668-11eb-9035-1fc39e19d995.png)

The Dedi server starts up fine without error and the same with the client but as soon as I try to join the server I get the Packet error. If I take out Silent Gear and leave SilentLib in it works fine

In SP I can create and join a world without issue, I only get the problem when I try to join a dedi server.

Server Log: [latest.log](https://github.com/SilentChaos512/Silent-Gear/files/5721654/latest.log)
Client Log: [latest.log](https://github.com/SilentChaos512/Silent-Gear/files/5721657/latest.log)

**Comment by SilentChaos512** [comment]
Not sure how Gear could be producing a packet that is bigger than the entire JAR file. Whatever the case, it does not happen for me with just Gear/Lib on a test server. Any data packs installed on the server? Does removing any other mods help?

Also, check out line 830 of the server log. I have never seen anything like that. No idea what could produce that.

**Comment by MacAttack-UK** [comment]
No problem, I'm currently building a fresh pack starting with Silent stuffs and working up from there. It's the long road but if it gets me to the problem it has to be done I guess :)

Yeah I saw that mush myself and like you never seen that before either. 1.16.4 is certainly fun to build packs with lol

Thanks for your time :)

Feel free to close this, I should of tested it on it's own myself.

**Comment by MacAttack-UK** [comment]
I've just tried adding Gear&Lib to the latest Direwolf20 Mopack v1.3.1 and everything is now working fine.

Forge: forge-1.16.4-35.1.36
Silent Lib: SilentLib-1.16.3-4.9.0+63
Silent Gear: SilentGear-1.16.3-2.4.11+200

Unsure what has fixed it but I'll close this issue.
