### ISSUE TITLE
Netherwood Tool Rod dosent up my durability to 70 if lower than that.

### ISSUE THREAD

**Issue by SnivyLlama** [SilentChaos512/Silent-Gear#280]
## Versions

- **Silent Gear**: 1.16.3-2.4.1+184
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 34.1.42
- **Optifine Installed**: No

## Expected Behavior

Expected my katana to have 70 durability.

## Actual Behavior

My katana had 45 durability instead.

## Links/Images

None

## Steps to Reproduce the Problem

1.Make a netherwood rod
2.Attach it onto something with a base durability lower than 120.
3.The durability is what it would've been in the first place - 50

**Comment by SilentChaos512** [comment]
The "max" modifier gets applied before the -50 "add" modifier, so that is working as intended. It caps the durability to 20 on the low end.
