### ISSUE TITLE
Unable to Regrade Materials (After Successful Regrading)

### ISSUE THREAD

**Issue by PiordaNautor** [SilentChaos512/Silent-Gear#284]
## Versions

- **Silent Gear**: 1.11.3
- **Silent's Gems**: N/A
- **Silent Lib**: 4.6.6
- **Forge**: 31.2.46
- **Modpack**: Valhelsia 2
- **Optifine Installed**: No

## Expected Behavior
Attempting to regrade a Steel Ingot (Grade S, Mekanism) using Blazing Dust as Catalyst.
Attempting to regrade an Emerald (Grade A, Vanilla) using Blazing Dust as Catalyst.

(Notes: I was able to previously regrade another Mekanism Steel Ingot from Grade C to D and then B)

Mining and Placing the Material Grader, or Relaunching the game did not fix the issue.

## Actual Behavior
Catalyst is consumed remains the same grade. Material continues to consume Catalysts, Material remains at the same grade.

## Links/Images
N/A

## Steps to Reproduce the Problem

1. Grade a Material
2. Attempt to regrade it (Several times if need be)
3. Grade a separate, identical Material
4. Attempt to regrade current Material

**Comment by SilentChaos512** [comment]
Regrading can take many attempts. It just rerolls and applies the new grade only if it is higher.

**Comment by PiordaNautor** [comment]
To clarify, will materials that fail to regrade will remain within the input slot?

**Comment by SilentChaos512** [comment]
Yes, that's right. In newer versions, the grader will also show the last grade it rolled.
