### ISSUE TITLE
1.14.2 serverside crash when breaking a tool on a server

### ISSUE THREAD

**Issue by tacct6** [SilentChaos512/Silent-Gear#29]
### Versions

- **Silent Gear**: 1.1.0+31
- **Silent Lib**: 4.1.1+28
- **Forge**: 26.0.33

### Expected behavior

I expected my wooden shovel to break when breaking a block (grass) on its last durability

i didn't test with other tools types
### Actual behaviour

On a server (can't reproduce on singleplayer), the server crashes after using a wooden shovel to break a grass block, restarting the server seems to leave the tool intact in the "broken" state, if you try to break a block with the broken tool the same crash will happen again. right clicking the grass to make a path doesn't seem to trigger a crash when the tool breaks
### Links/Images

server crash log: https://pastebin.com/HTG11NeZ

### Steps to reproduce the problem

1. setup a standalone multiplayer server
2. create a wooden shovel
3. break grass until your tool breaks
4. experience crash

**Comment by SilentChaos512** [comment]
Looks like I was calling a client-only method, so that would cause a dedicated server to crash. Should be fixed by some changes I made earlier. The shovels shouldn't be breaking completely though, thanks for pointing that out.
