### ISSUE TITLE
1.16.4[silent gear stone sword crashes seerver]

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/Silent-Gear#291]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.4.4+189-hotfix
- **Silent's Gems**:SilentGems-1.16.3-3.7.3+106
- **Silent Lib**:SilentLib-1.16.3-4.9.0+63
- **Forge**: 1.16.4-35.1.13
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/buildtech-lte-3
- **Optifine Installed**: No

## Expected Behavior
be able to swing my sword and it not crash the server

(Description here)

## Actual Behavior
i was fighting a husk using a stone sword converted from a normal one
then i swinged and it crashed the server
it did happen multple times with same sword
(Description here)

## Links/Images
crash report:
[crash-2020-12-20_13.59.27-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/5721031/crash-2020-12-20_13.59.27-server.txt)

![2020-12-21_01 27 48](https://user-images.githubusercontent.com/14084377/102715787-c3a5a680-432b-11eb-9ea8-14f39c1f3a99.png)

- (Link)

## Steps to Reproduce the Problem

1. as mentioned as above not sure if other ways of reproducing it
2.
3.

**Comment by drstorm81** [comment]
Same issue here, but with custom modpack and Vanilla Iron Sword.
[crash-2020-12-20_14.57.44-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/5721082/crash-2020-12-20_14.57.44-server.txt)

**Comment by SilentChaos512** [comment]
Reproduced with a random gear sword, but... A vanilla sword? Are you sure @drstorm81? None of that code should run for other items.

**Comment by drstorm81** [comment]
> Reproduced with a random gear sword, but... A vanilla sword? Are you sure @drstorm81? None of that code should run for other items.

I'll remove all SG stuff from my inventory and try again. Item is described in JEI as Minecraft Iron Sword, but it can be repaired with iron inglots so something can be interfering.

**Comment by drstorm81** [comment]
> > Reproduced with a random gear sword, but... A vanilla sword? Are you sure @drstorm81? None of that code should run for other items.
> 
> I'll remove all SG stuff from my inventory and try again. Item is described in JEI as Minecraft Iron Sword, but it can be repaired with iron inglots so something can be interfering.

Without SG equipment i'm inable to reproduce crash. It seems i had to switch to other SG item during combat. So Vanilla sword - no crashes.

**Comment by SDUBZ** [comment]
@SilentChaos512 its happens with a stone sword that has been crafted into a sg sword

**Comment by seebs** [comment]
Wow, nice! I came here to report this and you've already fixed it.
