### ISSUE TITLE
Texture of pickaxe lost when upgrading with Spoon

### ISSUE THREAD

**Issue by dashkal16** [SilentChaos512/Silent-Gear#296]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.4.7+194.jar
- **Silent's Gems**: SilentGems-1.16.3-3.7.3+106.jar
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63.jar
- **Forge**: 3.5.11
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

The pick to have a non-placeholder texture with the spoon installed.

## Actual Behavior

The pick gets a placeholder texture (purple/black) when the spoon is installed.

## Links/Images

![image](https://user-images.githubusercontent.com/464894/102941805-78dd7900-4468-11eb-8f8c-d5ea6c628c05.png)

## Steps to Reproduce the Problem

Created this pick, and tried to augment with a spoon:
![image](https://user-images.githubusercontent.com/464894/102941847-93175700-4468-11eb-80c7-49a06f1ef26f.png)

Crafttweaker /ct hand output:
`<item:silentgear:pickaxe>.withTag({SGear_UUID: [-573125464, 871843895, -1237698650, 601441597], SGear_Data: {Construction: {Parts: [{Item: {id: "silentgear:pickaxe_head" as string, Count: 1 as byte, tag: {CraftedCount: 1 as int, Materials: [{Item: {id: "silentgems:sapphire" as string, Count: 1 as byte}, ID: "silentgems:sapphire" as string}, {Item: {id: "silentgems:ruby" as string, Count: 1 as byte}, ID: "silentgems:ruby" as string}, {Item: {id: "silentgems:green_sapphire" as string, Count: 1 as byte}, ID: "silentgems:green_sapphire" as string}]}}, ID: "silentgear:pickaxe_head" as string}, {Item: {id: "silentgear:long_rod" as string, Count: 1 as byte, tag: {CraftedCount: 2 as int, Materials: [{Item: {id: "minecraft:iron_ingot" as string, Count: 1 as byte}, ID: "silentgear:iron" as string}, {Item: {id: "minecraft:iron_ingot" as string, Count: 1 as byte}, ID: "silentgear:iron" as string}, {Item: {id: "minecraft:iron_ingot" as string, Count: 1 as byte}, ID: "silentgear:iron" as string}]}}, ID: "silentgear:long_rod" as string}, {Item: {id: "silentgear:tip" as string, Count: 1 as byte, tag: {CraftedCount: 1 as int, Materials: [{Item: {id: "minecraft:diamond" as string, Count: 1 as byte}, ID: "silentgear:diamond" as string}]}}, ID: "silentgear:tip" as string}, {Item: {id: "silentgear:binding" as string, Count: 1 as byte, tag: {CraftedCount: 1 as int, Materials: [{Item: {id: "silentgems:gilded_string" as string, Count: 1 as byte}, ID: "silentgems:gilded_string" as string}]}}, ID: "silentgear:binding" as string}, {Item: {id: "silentgear:grip" as string, Count: 1 as byte, tag: {CraftedCount: 1 as int, Materials: [{Item: {id: "minecraft:leather" as string, Count: 1 as byte}, ID: "silentgear:leather" as string}]}}, ID: "silentgear:grip" as string}], RepairCount: 6 as int}, Properties: {ModVersion: "2.4.7+194" as string, Stats: {"silentgear:enchantability": 10.239832 as float, "silentgear:harvest_speed": 15.31626 as float, "silentgems:chargeability": 1.1 as float, "silentgear:harvest_level": 3.0 as float, "silentgear:durability": 2022.8743 as float, "silentgear:melee_damage": 8.570714 as float, "silentgear:magic_damage": 4.722995 as float, "silentgear:attack_speed": -2.7820375 as float, "silentgear:rarity": 59.857864 as float, "silentgear:repair_efficiency": 1.1 as float}, LockStats: 0 as byte, Traits: [{Level: 3 as byte, Name: "silentgems:imperial" as string}, {Level: 2 as byte, Name: "silentgear:brittle" as string}, {Level: 3 as byte, Name: "silentgear:magnetic" as string}, {Level: 2 as byte, Name: "silentgear:lustrous" as string}, {Level: 3 as byte, Name: "silentgear:flexible" as string}]}, Rendering: {ModelKey: "pickaxe:pickaxe_head{silentgems:sapphire,silentgems:ruby,silentgems:green_sapphire},long_rod{iron,iron,iron},tip{diamond},binding{silentgems:gilded_string},grip{leather}," as string}}, Enchantments: [{lvl: 3 as short, id: "minecraft:fortune" as string}], Botania_keepIvy: 1 as byte, AS_Amulet_Holder: [639832629, 1785283533, -2009330909, 1850121688]}).withDamage(300)`

**Comment by dashkal16** [comment]
Confirmed still present in SilentGear-1.16.3-2.4.8+195
Attached logs from a brief run where I logged in, set up the craft, observed the placeholder texture, aborted the craft, then closed minecraft.
[debug.log](https://github.com/SilentChaos512/Silent-Gear/files/5736805/debug.log)
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/5736806/latest.log)

**Comment by bakkerthehacker** [comment]
I'm also getting this bug on All The Mods 6 1.3.3

## Versions

- **Silent Gear**: SilentGear-1.16.3-2.3.9+181
- **Silent's Gems**: N/A
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: 35.1.4
- **Modpack**: All the Mods 6 1.3.3
- **Optifine Installed**: No

## Links/Images

![2021-01-12_02 03 15](https://user-images.githubusercontent.com/1406235/104281339-45a96b00-54a5-11eb-9b37-c7391b265f00.png)
![2021-01-12_02 03 41](https://user-images.githubusercontent.com/1406235/104281598-a9cc2f00-54a5-11eb-99c5-1c3b6c87c96d.png)

**Comment by bakkerthehacker** [comment]
F3 + T fixes it just like https://github.com/SilentChaos512/Silent-Gear/issues/190 does
