### ISSUE TITLE
Elytra doesn't appear behind the player

### ISSUE THREAD

**Issue by 27rogi** [SilentChaos512/Silent-Gear#297]
## Versions

- **Silent Gear**: 2.4.8
- **Silent's Gems**: 3.7.3 
- **Silent Lib**: 4.9.0
- **Forge**: 35.1.13
- **Optifine Installed**: Yes  (with Optifine off problem is the same)

## Expected Behavior

Elytra should be visible like default ones do.

## Actual Behavior

Elytras missing, but still working.

## Links/Images

![image](https://user-images.githubusercontent.com/10144091/103078011-ff699600-45e1-11eb-9a54-6695cebba9ef.png)

## Steps to Reproduce the Problem

1. Craft elytras
2. Equip them

**Comment by SilentChaos512** [comment]
Fixed by 73d12b4d01054a9c7fa55c6bcac9bf49ff1537d7
