### ISSUE TITLE
Colorless parts/weapons

### ISSUE THREAD

**Issue by Bagelboi** [SilentChaos512/Silent-Gear#30]
## Versions

- **Silent Gear**: 1.14.2-1.1.3+38  
- **Silent's Gems**: 1.14.2-3.1.3+41
- **Silent Lib**: 1.14.2-4.1.1+28  
- **Forge**: 1.14.2 - 26.0.63
- **Modpack**: N/A

## Expected Behavior
For the parts and weapons to display color based on the ores used.

## Actual Behavior

When I use ores on my blueprints to lets say, make a ruby pickaxe tip, it displays the standard gray one. Even when I try to mix and match to make weapons, everything's still gray. I did try with vanilla materials, same thing happend.

## Steps to Reproduce the Problem
1.Craft anything with a blueprint.

**Comment by Bagelboi** [comment]
Not only ores, but rods aswell, they end up gray.

**Comment by SilentChaos512** [comment]
That's odd, the colors should be correct in that version if you are on Forge 63.

**Comment by SilentChaos512** [comment]
Any news on this? I've had some similar reports recently, but no luck reproducing the issue. Log files would be helpful if this is still an issue.

**Comment by CyanSlinky** [comment]
I also encountered this and I'm fairly sure that it's Optifine, when i removed it the colors came back.

**Comment by WenXin20** [comment]
I've ran into this problem recently after installing OptiFine pre7
