### ISSUE TITLE
Elytra does not work when on Curio "Back" slot

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#302]
## Versions

- **Silent Gear**: 2.4.9
- **Silent's Gems**: 3.7.6 
- **Silent Lib**: 4.9.0
- **Forge**: 35.1.28
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Pressing jump mid-air to activate Elytra when on the Back slot

## Actual Behavior

Pressing jump mid-air does not activate elytra

## Links/Images

- (will add a video link later)

## Steps to Reproduce the Problem

1. Make Silent Gear elytra
2. Install a mod that adds a "Back" slot (like curious elytra)
3. Put elytra on back slot
4. Attempt to fly (and fail)

**Comment by iamnoobplzhelp** [comment]
This issue has come back in 1.17.
 Forge Version is 37.0.78
silent-gear-1.17.1-2.7.3

**Comment by Ocraftyone** [comment]
Was just about to say the same thing. Does not activate when on back curios slot

**Comment by PeterStrick** [comment]
This has come back in 1.21.1 too

NeoForge 21.1.92
Silent-Gear 4.0.10

**Comment by robertpharries** [comment]
@SilentChaos512 this appears to be broken still in:

ATM10

NeoForge 21.1.114
Silent-Gear 4.0.12

Same steps to reproduce, etc. Silentgear Elytra in back, curio slot, no fly. Works fine in armor chestplate slot.

**Comment by PowerChordGamer** [comment]
Issue is still present in 4.0.20

**Comment by SilentChaos512** [comment]
Make a new issue, this one is so old I'll never find it again if I reopen it.
