### ISSUE TITLE
Crashed when mining dirt with obsidian paxel from mekanism

### ISSUE THREAD

**Issue by AdnanuReeves** [SilentChaos512/Silent-Gear#303]
## Versions

- **Silent Gear**: x2.4.10+ 198
- **Silent's Gems**: not installed
- **Silent Lib**: 4.9.0+ 63
- **Forge**: 35.1.28
- **Modpack**: my own private
- **Optifine Installed**: No

## Expected Behavior
not crash? o.o

## Actual Behavior
Was just mining blocks with my obsidian paxel from mekanism and suddenly crashed.

## Links/Images
https://paste.ubuntu.com/p/jY3Pw5VPW7/

## Steps to Reproduce the Problem

1. I just mined some dirt with obsidian paxel
2.
3.

**Comment by SilentChaos512** [comment]
Not sure how mining a block could generate a crash in an item tooltip event, but I can add an extra check to prevent the NPE at least.

**Comment by AdnanuReeves** [comment]
Not sure why either, thanks for fixing it so quickly :)
