### ISSUE TITLE
Full game crash when clicking search or silentgear tabs in creative

### ISSUE THREAD

**Issue by Yurguth** [SilentChaos512/Silent-Gear#305]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.4.11+200  
- **Silent's Gems**: SilentGems-1.16.3-3.7.6+109 
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: minecraftforge:35.1.24
- **Modpack**: Personal CurseForge pack (overview in crashreport, can provide pack if needed) 
- **Optifine Installed**: Yes 

## Expected Behavior

simply be able to open said tabs

## Actual Behavior

game crashes completely

## Links/Images

- Crash Report: https://www.dropbox.com/s/tspwh7mfzhpv16d/crash-2021-01-03_23.04.32-client.txt?dl=0

## Steps to Reproduce the Problem

1. open inventory in creative
2. click on either search or any Silent tab
3. game freezes and shuts down

**Comment by SilentChaos512** [comment]
Is this reproducible without Optifine installed?
