### ISSUE TITLE
Silent gear startup crash - out of bounds exception

### ISSUE THREAD

**Issue by skohlhepp** [SilentChaos512/Silent-Gear#307]
I am getting a server crash during startup and crash reports lead me to believe it may be silent gear causing the problem. This doesn't always happen however. Crash report [here](https://gist.github.com/skohlhepp/8ff800a06c84d82872aa5e7e02ffa8b6).

**Comment by SilentChaos512** [comment]
Please follow the issue template. The crash report belongs on a paste site like Gist or Pastebin.

**Comment by skohlhepp** [comment]
> Please follow the issue template. The crash report belongs on a paste site like Gist or Pastebin.

Fixed

**Comment by SilentChaos512** [comment]
Is this random or does it happen every time? Does a particular combination of mods cause the crash?

**Comment by skohlhepp** [comment]
Seems to be random but this has happened a few times now just not on every startup.

**Comment by SilentChaos512** [comment]
Might be fixed by Silent Lib 4.9.1. It should prevent the crash on my end at least, but it might fail to register compostable items in cases where it would have crashed before.
