### ISSUE TITLE
Incorrect weapon stats, crafted with supercharged main parts

### ISSUE THREAD

**Issue by FerventCore** [SilentChaos512/Silent-Gear#308]
## Versions

- **Silent Gear**: 2.5.1
- **Silent's Gems**: 3.7.8 
- **Silent Lib**: 4.9.0
- **Forge**: 35.1.33
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior
Craft weapon with supercharged mainparts will result durability > 0 with the appropriate attack damage stats

## Actual Behavior
When I craft weapon (tested on katana/dagger) with supercharged I/II/III (tested with azure electrum/refined obsidian/enderium ingots) as main parts, it turns out a weapon with zero durability and a clearly understated attack

tested on katana/dagger with azure electrum
this problem has appeared since version 2.5.0

## Links/Images
![image](https://user-images.githubusercontent.com/77513510/104782733-c1513380-5795-11eb-86d2-f44d910c7fd8.png)
![image](https://user-images.githubusercontent.com/77513510/104782771-d037e600-5795-11eb-851b-4bb12ed1fd31.png)
![image](https://user-images.githubusercontent.com/77513510/104782796-dd54d500-5795-11eb-8af8-542b29e54099.png)

## Steps to Reproduce the Problem

1. Craft Katana with 3 x supercharged i/ii/iii azure electrum ingots and stick

**Comment by SilentChaos512** [comment]
Thanks for the detailed report. There is already an issue on the Gems repo for this, which is the best place for it since supercharging is a Gems mechanic. Just found a fix, so that should be uploaded sometime soon.

https://github.com/SilentChaos512/SilentGems/issues/523
