### ISSUE TITLE
[1.14.3] Recipe outputting PlaceHolder tool

### ISSUE THREAD

**Issue by TwilightPSN** [SilentChaos512/Silent-Gear#31]
## Versions
- **Silent Gear**: SilentGear-1.14.3-1.2.0+40
- **Silent's Gems**: SilentGems-1.14.3-3.2.2+52
- **Silent Lib**: 1.14.3-4.2.1+32 
- **Forge**: 27.0.24
- **Modpack**: N/A

## Expected Behavior
-When placing a tool part in a grid with a built tool it outputs a tool that seems to just be the placeholder tool

## Links/Images
![2019-07-06_22 48 44](https://user-images.githubusercontent.com/37508557/60763351-bbc34b00-a040-11e9-8dc1-946c81302068.png)

## Steps to Reproduce the Problem
1.Craft a Complete Tool
2.Craft a separate part for the tool
3.Place both the complete tool and new part into the craft table

**Comment by SilentChaos512** [comment]
Vanilla added back the old, broken repair recipe in 1.14.3 (tool heads count as a tool, so you're seeing the repair recipe). I'll need to override that recipe again...

**Comment by SilentChaos512** [comment]
I override the repair recipe to stop it from destroying gear items. I also added a recipe to allow tool head swapping, like you were trying to do in the screenshot.
