### ISSUE TITLE
StackOverflowError when connecting to a LAN world

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [SilentChaos512/Silent-Gear#310]
## Versions

- **Silent Gear**: 2.5.1
- **Silent's Gems**: 3.7.9
- **Silent Lib**: 4.9.0
- **Forge**: 35.1.36
- **Modpack**: Custom [1.16 (2).zip](https://github.com/SilentChaos512/Silent-Gear/files/5826499/1.16.2.zip)
- **Optifine Installed**: No

## Expected Behavior

Guest connects to a hosted LAN world successfully.

## Actual Behavior

During connecting to a LAN world, the game crashes. Crash occurs on the "Saving world" phase (after "Joining world").

## Links/Images

- Crash log: https://pastebin.com/Bj8wSDnr

## Steps to Reproduce the Problem

1. Host the following world: https://mega.nz/file/OdAhVY7J#Th5HxYLKznGKyrPesp89g4veptwL64RrDPQ1w-oXLEk
2. Load the world and open it to LAN
3. On a different client, try connecting to this world

Other notes: 
- Creating a new world solves this issue. Issue seems to only occur on the provided populated world.
- Deleting the guest client's profile from the host's side does not solve this issue
- We were upgrading Silent _Gems_ from 3.7.8 -> 3.7.9 when this occurred, but downgrading didn't help. Not sure how SGems might be related.

**Comment by SilentChaos512** [comment]
Not sure what exactly triggers this, but the 2.5.2 update should prevent the crash at least.

**Comment by EdvardasDlugauskas** [comment]
Unfortunately the crashes still persist. Interestingly, the stack traces are a bit different each time it seems https://pastebin.com/dSCpYZPK, https://pastebin.com/e0faFWiA

**Comment by SilentChaos512** [comment]
Both of those still show you are on 2.5.1

**Comment by EdvardasDlugauskas** [comment]
Ah, my bad. The latest version available is still 2.5.1 in the CurseForge client. I suppose the build hasn't been deployed yet. I'll be checking to see if it becomes available in the coming hours.

**Comment by EdvardasDlugauskas** [comment]
2.5.2 solves this issue. Haven't noticed any regressions or other side effects yet.
