### ISSUE TITLE
Stellar Trait not working for tools

### ISSUE THREAD

**Issue by alder-nighthawk** [SilentChaos512/Silent-Gear#312]
## Versions

- **Silent Gear**: SilentGear-1.15.2-1.11.4+187.jar
- **Silent's Gems**: N/A
- **Silent Lib**: SilentLib-1.15.2-4.6.6+59.jar
- **Forge**: 31.2.47
- **Modpack**: Valhelsia 2 - 2.3.1
- **Optifine Installed**: No
- 
## Expected Behavior

Stellar slowly repairs tools

## Actual Behavior

No tool crafted with materials with the stellar trait of any level repair.  Other functions of stellar (speed and jump boost on armor) appear to function appropriately.

## Steps to Reproduce the Problem

materials tested include terrasteel, elementium, and refined iron

**Comment by ZoMadeStuff** [comment]
Had the same bug in 1.16.4 tried stellar trait on Astral Sorcery's rock crystal and it never repairs itself
