### ISSUE TITLE
"Lucky" trait applies to armor but does not work

### ISSUE THREAD

**Issue by Pascalos99** [SilentChaos512/Silent-Gear#313]
When crafting an armor-piece with the "Lucky" trait, I expect wearing that armor-piece to increase the minecraft:generic.luck attribute by the appropriate amount as specified by the level of the trait.
Instead, it only works on tools, only giving the attribute addition bonus on offhand and mainhand.

Expected behavior: 
to not show up the "Lucky" trait on the armor-piece if it isn't supposed to work... OR to add the appropriate attribute modifiers to armor items when they have the "Lucky" trait (applying to their respective armor-piece attribute counterpart)
Actual behavior: 
armor-piece shows up as having the "Lucky" trait, but when wearing the piece, total minecraft:generic.luck attribute is still the same as before wearing the armor.

**Comment by SilentChaos512** [comment]
This does not seem to be an issue in the latest version. Maybe you are using an outdated version, but I have no idea because you somehow skipped picking the issue template and failed to fill it out.
