### ISSUE TITLE
Tool rods not showing stats when hovering on it while holding control

### ISSUE THREAD

**Issue by Cielisimo** [SilentChaos512/Silent-Gear#314]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.5.3+211.jar
- **Silent's Gems**:  N/A
- **Silent Lib**: SilentLib-1.16.3-4.9.1+64.jar
- **Forge**: 35.1.37
- **Modpack**: N/A
- **Optifine Installed**: No 
- jre-8u281-windows-x64

## Expected Behavior
tool rods show it's stats when hovering over it with the mouse cursor while holding control, works in version SilentGear-1.16.3-2.5.2+207.jar

## Actual Behavior
after updating the mod, when hovering over it with the mouse cursor while holding control, it just shows "Stats (Silent Gear)"

## Links/Images
https://ibb.co/B2Kppgb
https://ibb.co/VJDWK9z
https://ibb.co/VgCMNjD

## Steps to Reproduce the Problem

1. Install clean version of minecraft and forge
2. Download SilentGear and SilentLib from curseforge and install it
2. Start a game and create any tool rod
3. Try to check its stats

**Comment by Cielisimo** [comment]
Happens with bindings too, probably others.

**Comment by SilentChaos512** [comment]
I'm not seeing any issue when I test this. Could I get a log file?

**Comment by Cielisimo** [comment]
This is from a custom profile I just created using Overwolf curseforge (forgot to mention, all my profiles are created like this) using minecraft 1.16.5, forge 36.0.9, mods(SilentGear-1.16.3-2.5.4+212.jar , SilentLib-1.16.3-4.9.1+64.jar)
https://pastebin.com/vJGAUTza
