### ISSUE TITLE
Lumium and Signalum are the wrong color

### ISSUE THREAD

**Issue by unmoving-javi** [SilentChaos512/Silent-Gear#318]
## Versions
- **Silent Gear**: 2.5.4
- **Silent Lib**: 4.9.1
- **Forge**: 36.0.10
- **Optifine Installed**: No

## Expected Behavior
Lumium (from Thermal Foundation, natively supported by Silent Gear) should be a bright pastel yellow like the in-game item. Signalum, from the same, should be a bright red-orange.

## Actual Behavior
Lumium gear is a dark green and so is Signalum.

## Notes

I'm not sure if it's Thermal Foundation that supports Silent Gear or the other way around, but if it's a problem on the SG end, hopefully it's fixable.

**Comment by unmoving-javi** [comment]
Made some edits after realizing Lumium was not the only problem.

**Comment by SilentChaos512** [comment]
I used your descriptions to pick some colors using a color picker. Hopefully that's good enough.
