### ISSUE TITLE
Silent Gear resource loading issue (missing parts/traits)

### ISSUE THREAD

**Issue by Xetaxheb** [SilentChaos512/Silent-Gear#32]
## Versions

- **Silent Gear**: **1.2.1** 42
- **Silent's Gems**: 3.2.2 52 
- **Silent Lib**: 4.2.4 36
- **Forge**: 27.0.55
- **Modpack**: N/A

## Expected Behavior
Parts/traits load

## Actual Behavior
Parts/traits don't load

## Links/Images
Looks like something interfering with resources loading, maybe kleeslabs as was suggested, probably just a forge bug or other mod misbehaving

https://gist.github.com/Xetaxheb/c51cd314c02df4aac06d7a1588f5882f

When they don't load:

`[17Jul2019 14:23:40.421] [Server thread/INFO] [Silent Gear/TraitManager]: Gear traits loaded: 0
[17Jul2019 14:23:40.422] [Server thread/INFO] [Silent Gear/PartManager]: Gear parts loaded: 0`

Also, this pops up on connect if they haven't loaded: 
`[17Jul2019 14:23:57.327] [Netty Server IO #1/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.silentchaos512.gear.api.parts.MaterialGrade$Argument@31534fd7 (class net.silentchaos512.gear.api.parts.MaterialGrade$Argument) - will not be sent to client!`

**Comment by Omnimetatron** [comment]
Have this issue in 1.15, only on server though, works fine in singleplayer.

https://gist.github.com/Omnimetatron/af56d5917d839f774a7f6940a5f8f79c

Silent Gear: 1.5.4+79
Silent's Gems: 3.5.1+84
Silent Lib: 4.6.0+48
Forge: 31.1.27
Modpack: N/A

**Comment by SilentChaos512** [comment]
@Omnimetatron Searching your log for "Failed to reload data packs" is the best way to find the problem. Looks like you have a mod with a sideness issue on your server.
