### ISSUE TITLE
Hammer AOE crashes the game and server.

### ISSUE THREAD

**Issue by Laeron-Inkheart** [SilentChaos512/Silent-Gear#324]
## Versions

- **Silent Gear**: 1.16.3
- **Silent's Gems**: 1.16.3 
- **Silent Lib**: 1.16.3
- **Forge**: 1.16.5
- **Modpack**:  custom (screen shot in link)
- **Optifine Installed**: No

## Expected Behavior
Crafted a hammer, expected aoe 3x3 mining.

## Actual Behavior
Instead my server crashed repeatedly. I downloaded the map and replicated the crash in single player.
After using it the game sounds would cut out. I could still move around for roughly 30 seconds before the game window would close.
Using the hammer on dirt or mining a single block did not crash the game.

## Links/Images

- https://imgur.com/a/YJaQSmq

## Steps to Reproduce the Problem

1. Install mods
2. make a hammer
3. mine a 3x3 square

**Comment by SilentChaos512** [comment]
Please correct the versions section to include the actual mod versions and link a crash report. I can't do anything without details about the crash.
