### ISSUE TITLE
Hammer AOE crashes the game and server. (corrected copy)

### ISSUE THREAD

**Issue by Laeron-Inkheart** [SilentChaos512/Silent-Gear#325]
## Versions

- **Silent Gear**: 1.16.3-2.5.4+212
- **Silent's Gems**:1.16.3-3.7.9+112
- **Silent Lib**: 1.16.3-4.9.1+64
- **Forge**: 1.16.4-35.1.4
- **Modpack**: Custom, screenshot in imgur link
- **Optifine Installed**: No 

## Expected Behavior
Crafted a hammer, expected aoe 3x3 mining.

## Actual Behavior
Instead my server crashed repeatedly. I downloaded the map and replicated the crash in single player.
After using it the game sounds would cut out. I could still move around for roughly 30 seconds before the game window would close.
Using the hammer on dirt or mining a single block did not crash the game.

## Links/Images

- https://imgur.com/a/YJaQSmq
- https://paste.shockbyte.com/afocefutikukutidenex

## Steps to Reproduce the Problem

1.Install mods
2.make a hammer
3.mine a 3x3 square

**Comment by SilentChaos512** [comment]
Looks like an incompatibility with whatever `ht.treechop.TreeChopMod` is. Not sure which end it should be fixed on. Seems really odd that such a mod would be interacting with the hammer.

**Comment by Laeron-Inkheart** [comment]
Aye it was. Thanks for sending me in the right direction. Hammer works as expected now.
