### ISSUE TITLE
Compound Materials incorrectly mixing split armor stats

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#327]
## Versions

- **Silent Gear**: 2.6.0
- **Silent Lib**: 4.9.1
- **Forge**: 36.0.22

## Expected Behavior

Split armor stats to not be increased to ridiculous amounts

## Actual Behavior

When making a compound material, if a part which has split armor stats (helmet, chest, legs, boots) is compounded with one which does not (one single stat), it appears to mix the non-split stat with each of the split stats, causing a ridiculous increase in total armor. For example, a full set of 3 bismuth 1 iron armor gives 61 armor when all of it is worn.

## Links/Images

- https://imgur.com/a/sWk5gdh

## Steps to Reproduce the Problem

1. Make a metal alloyer/gem recrystallizer
2. Compound a material with split armor stats with one that does not split
3. Profit..?

**Comment by TheLewtz** [comment]
Saw this with refined obsidian boots in ATM6 pack being like 22 armor ...for just the boots.  Filled up all the armor shields+ by putting on boots.  Each piece would be 20+ armor each, where I think the set is suppose to total 30?
