### ISSUE TITLE
Cant craft ANY armor in silent Gear

### ISSUE THREAD

**Issue by BlueYoshi68** [SilentChaos512/Silent-Gear#33]
## Versions

- **Silent Gear**: 0.5.2
- **Silent's Gems**: 2.8.16
- **Silent Lib**: 3.0.13
- **Forge**: 14.23.5.2825
- **Modpack**: Realm Hoppers on technic (My own pack)

## Expected Behavior

This happens for all armor and all materials.
x =  Chestplate BLueprint
y = emeralds

Crafting Table:

x y y
y y y  = Emerald Chestplate
y y y

## Actual Behavior

![Capture](https://user-images.githubusercontent.com/10472980/61424242-7de3e380-a8d8-11e9-9224-0c9a6060e601.PNG)

It doesn't work. It works for tools though which is weird.

## Links/Images

See image above

## Steps to Reproduce the Problem

1. Try and make an armor piece.
2. Try again.
3. Try a 3rd time.

**Comment by SilentChaos512** [comment]
Already fixed way back in version 0.5.3. You need to update to a more recent version.
