### ISSUE TITLE
Compounding Recipes work with only 1 material [1.16]

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/Silent-Gear#333]
## Versions

- **Silent Gear**: 2.6.4
- **Silent Lib**: 4.9.1
- **Forge**: 35.1.37

## Expected Behavior

3 Crimson Steel should not give 4 Tyrian Steel

## Actual Behavior

Putting an amount of materials corresponding to the amount used in the recipe, if the material is used in a compounding recipe, you get the compounding result. As an example, Tyrian Steel uses 3 slots, so you can put in 3 Crimson Steel and get tyrian steel for free.

## Links/Images

- https://imgur.com/a/DI8wz9p

## Steps to Reproduce the Problem

1. Make a metal alloyer/recrystallizer
2. Put in a material used in a compounding recipe
3. Put one in each slot used by the recipe
4. Get the recipe while only using one material

**Comment by SilentChaos512** [comment]
That's funny. Should be an easy fix at least. Thanks for reporting.
