### ISSUE TITLE
Random Tool Rod Crash

### ISSUE THREAD

**Issue by KamikazePigeon** [SilentChaos512/Silent-Gear#334]
Forge version 35.1.33, latest version of Silent Gear.

Seems to not be a for-sure crash, as it only happened once and I'm not entirely sure it even involves Silent Gear that much but it does mention Silent Gear in this report so I figured I'd post it here.

How it crashed was I put two iron ingots in a crafting table, going to make tool rods out of them, took the blueprint and was about to add it and as soon as I clicked the crafting grid the game crashed. I was on a LAN server and the crash didn't affect the host at all. I tried to open the game again and tried to do it again but it didn't work. More importantly, when I loaded up the game again, both the ingots I had used and the blueprint for the tool rod had completely disappeared from existence. Just poof, gone. Just a fluke, maybe?

[crash-2021-02-23_14.59.57-client.txt](https://github.com/SilentChaos512/Silent-Gear/files/6033616/crash-2021-02-23_14.59.57-client.txt)

**Comment by SilentChaos512** [comment]
Probably an Optifine crash. I've seen reports like this before, but never encountered it myself.

**Comment by TNBlueBear** [comment]
Did you manage to fix it? I'm having an identical issue.

Edit: Sorry kinda new to modding. Had to do a full erase but I am now enjoying your mod sans optifine.

Update: Did more testing. Seems to work with optifine as long as shaders aren't activated.

**Comment by SilentChaos512** [comment]
@TNBlueBear Like I said before, probably an Optifine crash. I cannot fix Optifine's screw-ups.

(edit) If you do _not_ have Optifine installed, please provide a link to the full crash report. What you provided is not helpful in any way.

**Comment by KamikazePigeon** [comment]
I have both Optifine and SEUS Renewed Shaders. I'm honestly willing to believe it could be a Optifine/Shader problem, as this particular shader DOES have many a visual issue as far as modding goes, as well as the fact that the LAN server host did NOT have SEUS shaders (she has BSL) and didn't crash.

**Comment by SilentChaos512** [comment]
Added some code for next version which _might_ help. Will probably create a lot of log spam if it even prevents the crash. I have no way of testing this.

**Comment by TNBlueBear** [comment]
Final Update: I am currently having zero issues with the new update, current optifine, and BSL 8.0 shaders.
