### ISSUE TITLE
Comprehensive material data simplifier

### ISSUE THREAD

**Issue by teknikalarkitekt** [SilentChaos512/Silent-Gear#335]
Can we get a file that basically reads all of the data configs and then displays all of the information for each material and part in a simple file? Basically display all the traits, stats, and everything that can be read in the files and throw it into a simple spread sheet format? Since it generates the spreadsheet by reading your files, it will theoretically display all of the information you can find in game, but in the form of an automatically sorted spreadsheet so that you can easily look at all the items by tier and stuff.

**Comment by SilentChaos512** [comment]
The `/sgear_mats dump` command already does that, unless I'm misunderstanding something here.

**Comment by teknikalarkitekt** [comment]
is it something similar to what you find in this outdated spreadsheet? https://www.reddit.com/r/feedthebeast/comments/gj140q/ive_made_a_comprehensive_spreadsheet_for_every/

**Comment by SilentChaos512** [comment]
No, that was created by hand, I think. Here's a more recent example: https://docs.google.com/spreadsheets/d/1xCGffU7FuVs87zeoVjxv2pCqbMcveAU_UkuvdE-DgWA/edit?usp=sharing

**Comment by teknikalarkitekt** [comment]
yes, something like that but auto generated by a simple command to be up to date, including any modifications the user has made to the files. Also it would be cool to use the same file to import modified silent gear stats to equipment via the same command but like, import instead of export. like "/silentspreadsheet import <link>" and "/silentspreadsheet export" and it will just upload and give you a link or something to a spreadsheet and you can edit the numbers and save it then import the link or file path

**Comment by SilentChaos512** [comment]
That spreadsheet _was_ generated by the command I mentioned (`/sgear_mats dump`). It pulls the data straight from the class that loads all the data files, including ones that came from other mods and data packs. The formatting has to be done by hand still, but that only takes a few minutes.

Not sure about importing. I guess it would be possible to write a program to reverse the process and create all the JSON files, but I don't really want to tackle that myself. Just editing the files with a data pack isn't that bad.

**Comment by teknikalarkitekt** [comment]
unfortunate. so will it show mats for only the installed mods or all of the mats that sgear is capable of modifying?

**Comment by SilentChaos512** [comment]
Anything that was loaded, so that would exclude anything with conditions that cause it not to load (such as mod metals that your pack is missing).

**Comment by teknikalarkitekt** [comment]
so how does silent gear decide what materials are sgear materials in modded content? do you add them manually or do you generate stats based on rarity or something?

**Comment by SilentChaos512** [comment]
Everything is manually defined. Most materials specify a tag to look for, like `forge:ingots/silver`. For item tags that may not exist, it skips loading the whole file if the tag is missing.

All of the vanilla materials and common mod metals are defined here: https://github.com/SilentChaos512/Silent-Gear/tree/1.16.x/src/generated/resources/data/silentgear/silentgear_materials.

**Comment by teknikalarkitekt** [comment]
thank you
