### ISSUE TITLE
Netherite cannot be used in repair kits

### ISSUE THREAD

**Issue by mnsnownutt** [SilentChaos512/Silent-Gear#338]
## Versions

- **Silent Gear**:2.6.6+226
- **Silent's Gems**: 3.7.11+114

## Expected Behavior
Use netherite ingots in repair kits

## Actual Behavior
Cannot use netherite ingots in repair kits

I am not sure if it is a bug or working as intended.  If it is working as intended, then I guess this could be tagged as an enhancement request.

**Comment by SilentChaos512** [comment]
Netherite has no durability (only a durability multiplier), so its repair value is also zero. That is working as intended.

**Comment by mnsnownutt** [comment]
Understood.  Thanks.
