### ISSUE TITLE
Broken Datapack

### ISSUE THREAD

**Issue by CanBoy67** [SilentChaos512/Silent-Gear#341]
## Versions

- **Silent Gear**: 2.6.6 (corrected from 2.2.6)
- **Silent's Gems**: NA
- **Silent Lib**: 4.9.1
- **Forge**: 36.0.45
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior
Be able to load into the world without an issue

## Actual Behavior
Fails to load Into World

Whenever I load into a current world or start a new world It isn't able to load and it says "Errors in currently selected datapacks prevented the world from loading." then it gives you the option to starts in safe mode which never works or return to the main menu to manually fix the problem, when I disable your mod everything works as it should.

## Links/Images

- https://gist.github.com/CanBoy67/eadf970dfb133e0d585de311a079e965 (debug.log)
- https://gist.github.com/CanBoy67/631d3f7e98060c25ea34a66c3f4ec0c2 (latest.log)

## Steps to Reproduce the Problem

1.Load Minecraft
2.Select World with Silent Gear Enabled
3.See datapack issue

**Comment by SilentChaos512** [comment]
Looks like Immersive Engineering is the cause, based on your logs. You also got your Silent Gear version wrong, it's 2.6.6.

**Comment by CanBoy67** [comment]
I was think it was immersive too, but I wasn't sure
EDIT: Yup it's a problem with the latest version of Immersive thank you for looking at it even though it wasn't your mod that was the issue
