### ISSUE TITLE
Way to remove a trait put on by a soul gear

### ISSUE THREAD

**Issue by mnsnownutt** [SilentChaos512/Silent-Gear#342]
## What Should Be Added or Changed?
Either through a kit or crafting bench using an item, remove the last trait put on a tool/gear item by a soul gear.

## Why Should This Be Done?
I tried to strip some logs with my axe only to place obsidian with it.  Discovered it had received the Vulcan trait from the soul gear applied to it.  This also happened on a Topaz pickaxe I created with the Refractive trait.  It also obtained the Vulcan trait and started placing obsidian instead of lights.  It basically makes the other traits/abilities worthless.  I had to create a new Topaz pick and a new Axe.  Not the end of the world, but it would be nice to be able to remove traits somehow.

**Comment by SilentChaos512** [comment]
That trait shouldn't come from gear souls. Probably a tip upgrade (refined obsidian is the only one I know), which you could remove with a gear mod kit.

**Comment by mnsnownutt** [comment]
Correct!  Sorry about that!
