### ISSUE TITLE
Higher graded materials should be more effective for repairing tools

### ISSUE THREAD

**Issue by TheDeviantCrafter** [SilentChaos512/Silent-Gear#345]
## What Should Be Added or Changed?
When adding materials to a repair kit, I would like higher graded materials to be more effective. Instead of an SSS rank diamond adding exactly 1 repair worth of material, maybe it adds 1.5.

## Why Should This Be Done?
It makes sense that higher quality materials can do a better repair job. This would also make the material grading system more useful, especially for more expensive materials like tyrian.

**Comment by SilentChaos512** [comment]
Seems this is already handled correctly. The durability of the repair material is used to determine the repair amount, and it already considers the grade.
