### ISSUE TITLE
Missing Traits on tools and items

### ISSUE THREAD

**Issue by Annon9007723** [SilentChaos512/Silent-Gear#348]
## Versions

- **Silent Gear**: 2.6.8
- **Silent's Gems**: 3.7.11+114 
- **Silent Lib**: 4.9.4+68
- **Forge**: 36.0.48
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior

Items should have listed traits. There are no traits to be found.

## Actual Behavior

Traits are missing entirely on both tools and items. 

## Links/Images

![image](https://user-images.githubusercontent.com/26782997/110703596-36971e80-81b1-11eb-8a27-5e31603836ee.png)

![image](https://user-images.githubusercontent.com/26782997/110703538-2717d580-81b1-11eb-9867-95f2a538bcd0.png)

## Steps to Reproduce the Problem

1. Launch the game.

**Comment by SilentChaos512** [comment]
Looks like the traits are getting lost at the material level. Did some refactoring recently, so that's definitely the cause. Working on it now.
