### ISSUE TITLE
[Request] 1.14.3 Config option to nerf vanilla tools

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/Silent-Gear#35]
## What Should Be Added or Changed?
A config option added to nuke vanilla tools usefulness as in SG 1.12

## Why Should This Be Done?
CraftTweaker isn't available for 1.14 as yet, so there's currently no way to prevent the use of vanilla tools over Silent Gear in modpacks.

If this option was added, then pack devs could force reliance on SG tools instead.

**Comment by SilentChaos512** [comment]
The only problem with this is that altering max item damage is impossible now. So I would need to do something else instead. Not sure what my options are.

**Comment by GamertechAU** [comment]
Is it still possible to do durability?

Could just give them 1hp so they break on use and add a red tooltip "for crafting use only" or similar.

**Comment by SilentChaos512** [comment]
That's what I meant, durability cannot be changed. At least not directly, there is another way to change it. Looks like that might work based on a quick test.

**Comment by GamertechAU** [comment]
Confirmed working. Cheers Silent
