### ISSUE TITLE
Saw doesn't vein mine bare tree

### ISSUE THREAD

**Issue by toruPuchuu** [SilentChaos512/Silent-Gear#352]
## Versions

- **Silent Gear**: 2.6.13
- **Silent's Gems**: x.x.x 
- **Silent Lib**: 4.9.6
- **Forge**: 36.0.63 
- **Modpack**: private
- **Optifine Installed**: No
- **Minecraft**: 1.16.5

## Expected Behavior
Bare tree is vein mined by saw

## Actual Behavior
After harvesting a tree's leaves, a Silent's Gear saw will no longer vein mine the tree.

## Links/Images
n/a

## Steps to Reproduce the Problem
1. Make saw
2. Grow tree
3. Harvest all of the leaves
4. Try to cut down the bare tree with the saw; it will only break one block.

## Comments
Pain in the tuckas for a Skyblock/Ex Nihilo world. If this is intended, then please have a config option to override.

**Comment by SilentChaos512** [comment]
The issue with that is a bunch of logs does not necessarily make a tree. What if the logs were part of a player's build? I understand that leaves can also be used for building, but I would rather minimize the risk of accidental destruction.
