### ISSUE TITLE
Material Grader UI Desync (Visual Glitch)

### ISSUE THREAD

**Issue by Dat-Guy** [SilentChaos512/Silent-Gear#353]
## Versions

- **Silent Gear**: 2.6.10
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.9.6
- **Forge**: 36.0.46
- **Modpack**: All the Mods 6 - To The Sky 
- **Optifine Installed**: No 

## Expected Behavior

When shift-clicking grader catalyst, it should be auto-inserted into the catalyst slot, if empty.

## Actual Behavior

When shift-clicking grader catalyst, it is correctly moved from the player inventory to the material grader, but the UI does not reflect this. This bug is not persistent beyond exiting the grader UI.

## Links/Images

(Did not cause a crash)

## Steps to Reproduce the Problem

(Needed materials: Grader, Material, Catalyst)

1. Place a Grader
2. Open the UI
3. Add the material
4. Shift-click the catalyst

**Comment by Dat-Guy** [comment]
My best guess is that the client is screwing up one of the inventory.isItemValidForSlot calls. I only tested this issue with glowstone so far, I'll need to test dedicated catalysts next. Here's a reference to the relevant statements [97-106](https://github.com/SilentChaos512/Silent-Gear/blob/b54427c27060d47d504760ff6b80f9fbbf41db94/src/main/java/net/silentchaos512/gear/block/grader/GraderContainer.java#L97). May be caused by inventory.isItemValidForSlot, which

**Comment by Dat-Guy** [comment]
After some testing, this bug applies to ALL catalysts, even those which aren't also a material.
Also, I'm guessing that [inventory.isItemValidForSlot](https://github.com/SilentChaos512/Silent-Gear/blob/b54427c27060d47d504760ff6b80f9fbbf41db94/src/main/java/net/silentchaos512/gear/block/grader/GraderTileEntity.java#L247) used in [GraderContainer](https://github.com/SilentChaos512/Silent-Gear/blob/b54427c27060d47d504760ff6b80f9fbbf41db94/src/main/java/net/silentchaos512/gear/block/grader/GraderContainer.java#L97) may be a culprit, as everything else seems to be inherited from Forge and used as intended. I've spent maybe an hour on this, I'll need to clone and do some standalone testing to make sure this is the case, and not the result of some unintended interaction in the pack.

**Comment by SilentChaos512** [comment]
That's probably the cause, I fixed a very similar issue with another block recently. The client side gets a generic inventory object which returns the wrong value. It's an easy fix.
