### ISSUE TITLE
Dedicated server log spam causing lag

### ISSUE THREAD

**Issue by EnderMelody** [SilentChaos512/Silent-Gear#354]
## Versions

- **Silent Gear**: 1.16.3-2.6.13
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.0
- **Optifine Installed**: No
 - **Modpack**: https://www.curseforge.com/minecraft/modpacks/bread-bank-2

## Expected Behavior
no log spam

## Actual Behavior
log is spammed with repeated generation changes. example "[Silent Gear/]: Add wild fluffy plants to byg:seasonal_taiga"
The generation change happens multiple times causing massive lag on the server. It eventually has a "base value out of range" which seems to reset it.
## Links/Images
[debug.log](https://github.com/SilentChaos512/Silent-Gear/files/6200985/debug.log)

## Steps to Reproduce the Problem
install pack
connect to server running the pack
wait till it starts to lag

**Comment by SilentChaos512** [comment]
That's... really odd. Any idea what causes that to happen? Like a specific mod? Normally, biomes are only loaded once, so you should see each message only once.

(edit) I should definitely add a config to disable the world gen logging regardless.

**Comment by EnderMelody** [comment]
No idea. Just updated a few mods and this started happening, though I honestly dont think its caused by this mod, this is the only one that showed up in logs.
updated mods: architecturey API, CoFH Core, Collective, CraftTweaker, Customizable Elytra, Dynamic Surroundings, Industrial Forgoing, LibX, Thermal Foundation, Upgrade Aquatic.
non of these are listed in the logs afaik, so im not sure what happened. I also cant say this wasnt happening before updating, though it was never this bad before.

**Comment by SilentChaos512** [comment]
Alright. Well whatever the case, I added a new option (`debug.logging.worldGen`) in version 2.6.14 which will disable the messages. It's enabled by default, so you'll have to set it to `false` to disable the logging.
