### ISSUE TITLE
[1.14.4] Cannot build a complete tool in one step

### ISSUE THREAD

**Issue by revdave33** [SilentChaos512/Silent-Gear#36]
## Versions

- **Silent Gear**: 1.14.4-1.3.0+49 
- **Silent's Gems**: 1.14.4-3.3.0+54
- **Silent Lib**: 1.14.4-4.3.0_38
- **Forge**: 28.0.13
- **Modpack**: N/A

## Expected Behavior

When building a tool, I should be able to build the tool in one step: template/blueprint + gems + tool rod. It then shows the updated stats as I try out different configurations.

## Actual Behavior
When building the tool, once the rod is added to the recipe, the stats pane is empty, and there is no tool to be picked. If I remove the tool rod, the head is formed, but the stats pane text becomes too small to read. I can then build the tool with the head and the rod separately.

**Comment by SilentChaos512** [comment]
Fixed in 1.3.1. I also changed the crafting station to trim long lines. Maybe not the best way of handling it, but good enough for now, I hope?
