### ISSUE TITLE
[Pickle Tweaks] Stone pickaxe (with +stone rod) shows level obsidian

### ISSUE THREAD

**Issue by nekonesse** [SilentChaos512/Silent-Gear#361]
## Versions
only tested on 1.16.5,

- **Silent Gear**: 2.6.14
- **Silent's Gems**: 3.7.13
- **Silent Lib**: 4.96
- **Forge**: 1.16.5 36.1.3
- **Modpack**: (the modpack mods are all in this drive.) https://drive.google.com/drive/folders/13qqpCongqPs4qS8v2pEGUmCKsA-6KZ9q?usp=sharing 
- **Optifine Installed**: No 

## Expected Behavior
Stone pickaxe's mining level shows as iron when created.

## Actual Behavior
The stone pickaxe's mining level shows as obsidian when created, though it purely visual and cant mine diamonds/obsidian.

## Links/Images
- video of this happening, https://streamable.com/dmnly0

## Steps to Reproduce the Problem
Literally just make a stone pickaxe.

1. Make a stone rod,
2. Craft a stone pickaxe with the rods

**Comment by SilentChaos512** [comment]
Caused by another mod. They are checking the harvest level incorrectly.

**Comment by SilentChaos512** [comment]
By the way, if you happen to figure out which mod adds those tooltip lines, please tell me. I will help them fix this issue because I have already had multiple reports of this.

**Comment by FreeFull** [comment]
The tooltip lines are from Pickle Tweaks.

**Comment by SilentChaos512** [comment]
Thanks @FreeFull, I reported the issue to them (https://github.com/BlakeBr0/PickleTweaks/issues/71).
