### ISSUE TITLE
Non [a-z0-9_.-] character in namespace of location

### ISSUE THREAD

**Issue by LPwithPaul** [SilentChaos512/Silent-Gear#362]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.3.9+181.jar
- **Silent's Gems**: N/A
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63.jar
- **Forge**: 1.16.4
- **Modpack**: Yes, All The Mods 6
- **Optifine Installed**: No 

## Expected Behavior
Game loads without errors.

The Game should load without any error and you should spawn regularly.

## Actual Behavior
The game gives an Error before you load into the server.

The game gives the Error as shown below. You cannot spawn.

## Links/Images

- Screenshot of error: https://screenshots.weil-ichs-kann.com/i/1_js4cjqtw8zthpof.png
- Paste of latest.log: https://screenshots.weil-ichs-kann.com/f/QPmgTLD3R3.txt
- Paste of 2021-04-02-2.log: https://screenshots.weil-ichs-kann.com/f/KwGK8pDR0W.txt

## Steps to Reproduce the Problem

1. Install the All The Mods 6 "Simple Server Files 1.5.7" (Windows and Linux give the same error)
2. Download All The Mods 6 on Curseforge.
3. Join on the Server and youll se the Error

**Comment by SilentChaos512** [comment]
The version of Silent Gear you are running on your client is badly outdated compared to the server you are trying to connect to. Please make sure you have the same version of all mods on both your client and server.
