### ISSUE TITLE
Fine silk binding gives armor buff but cannot be used for armor

### ISSUE THREAD

**Issue by EnderMelody** [SilentChaos512/Silent-Gear#363]
## Versions

- **Silent Gear**: 2.6.16
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.0

## Expected Behavior
Using fine silk as a binding gives a +2 magic armor. You would assume that it would then be applicable to armor, but it is not.

## Actual Behavior
Fine silk is not usable as a binding for armor even though it has an armor buff.

## Links/Images
![Untitled](https://user-images.githubusercontent.com/12649140/113478461-eda45400-9456-11eb-8dfd-4a2fb95f0823.png)

**Comment by SilentChaos512** [comment]
The elytra supports bindings, that's why it has armor-related stats.
