### ISSUE TITLE
Salvager: Unable to salvage the materials - let alone with proper fragments.

### ISSUE THREAD

**Issue by TailedMute** [SilentChaos512/Silent-Gear#364]
## Versions

- **Silent Gear**: 2.6.14
- **Silent's Gems**: N/A
- **Silent Lib**: 4.9.6
- **Forge**: forge-36.1.2
- **Modpack**: All The Mods 6 (CurseForge)
- **Optifine Installed**: No

## Expected Behavior

The Salvager is to break down items into components and fragments, including compounds, and these fragments can be combined back into said components.

## Actual Behavior

Compounds, if they are created, come out as "unknown alloy" ingots with no NBT. Fragments are unable to be crafted back into normal ingredients. Alloy ingot fragments also lose their NBT.

## Links/Images

![Screenshot_1 (2)](https://user-images.githubusercontent.com/81915986/113512344-cf5b5880-9529-11eb-8df6-9c66ed5c9518.png)
![Screenshot_1 (2)](https://user-images.githubusercontent.com/81915986/113512367-f87be900-9529-11eb-9e2d-ff7270ac886c.png)
![Screenshot_1 (2)](https://user-images.githubusercontent.com/81915986/113512414-24976a00-952a-11eb-874b-39e4622c036e.png)

## Steps to Reproduce the Problem

1. Mercilessly merge multiple gems/alloys together.
2. Create your product, or multiple of them.
3. Panic, because of a mistake you made during the creation process, creating Katanas instead of Swords, and begin to break down the tool. And multiple of them, at that.
4. Begin to develop a mental scar as your fresh materials are now useless fragments that cannot be converted back.

**Comment by SilentChaos512** [comment]
Looks like a problem with `SalvagingRecipe#salvage`. It ignores the actual item that was used as a material and creates a new instance. I believe I decided to do that to remove the material grade and enchantments like Supercharged. That worked when compound materials did not exist, but it clearly fails here.

**Comment by ArtemisFowl16** [comment]
wait, but why can't I craft fragments back into the ingots? For example, I used a crimson steel ingot and crimson iron, but cant craft their fragments into the ingots. Please Help?!
