### ISSUE TITLE
Renew trait does not work

### ISSUE THREAD

**Issue by milkev** [SilentChaos512/Silent-Gear#365]
## Versions
- **Silent Gear**: 2.6.16
- **Silent's Gems**: 3.7.14 
- **Silent Lib**: 4.9.6
- **Forge**: 1.16.5-36.1.2
- **Modpack**: Private
- **Optifine Installed**: No

## Expected Behavior
put renew trait on item, item repairs over time.

## Actual Behavior
item does not repair over time

## Steps to Reproduce the Problem
1: create tool with a material with the renew property. i used phantom membranes on elytra at a 50% ratio. make sure the trait actually displays on the gear under its trait list.
2: damage the tool, note the damage value
3: leave the tool in; hotbar, main hand, inventory slots, armour slots, or curios slots
4: wait a while. i left it for atleast 15-30 minutes in each of the slots i listed.
5: check durability value against noted value from step 2. it is the same value.

**Comment by SilentChaos512** [comment]
Well, armor and elytra were definitely not ticking traits from the normal inventory, which I can fix. But the trait is working in armor inventory slots for elytra. Maybe you just got unlucky when testing it. The activation rate is really low.
