### ISSUE TITLE
My Crimson Steel Pickaxe doesnt break blocks correctly

### ISSUE THREAD

**Issue by GianBala83** [SilentChaos512/Silent-Gear#369]
Im playing Silent Gear on version 0.6.7 at 1.12.2 and i made a pickaxe with a diamond,a emerald, and a crimson steel, some time the pickaxe starts to insta mine stones in the map but dont really break them, and this is happening in a high frequency

Someone can help me to solve this?

https://user-images.githubusercontent.com/76718735/114105041-644fb000-98a2-11eb-93e9-31cde2662806.mp4

**Comment by SilentChaos512** [comment]
No idea if that's something I can fix or not. Either way, 1.12.2 is no longer supported.
