### ISSUE TITLE
Why i cant use Thermal Expansion Ores to make Silent Gear Tools?

### ISSUE THREAD

**Issue by GianBala83** [SilentChaos512/Silent-Gear#370]
## Versions

- **Silent Gear**: 0.6.7
- **Silent's Gems**: x.x.x No
- **Silent Lib**:3.0.13
- **Forge**: 1.12.2
- **Modpack**: N/A No
- **Optifine Installed**: No  Yes

## Expected Behavior

i expected to use Thermal Expansion ores to make my tools

## Actual Behavior

I can only use the vanilla materials and those originally from SG
![silent gear materials]

## Links/Images

- (https://user-images.githubusercontent.com/76718735/114111988-bcda7980-98b1-11eb-9009-51964d7345fb.png)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Common mod metals were not included in the base mod back then. Your options are:
1. Install Basic Mod Metals pack (https://github.com/SilentChaos512/SGear-Basic-Metals/releases/tag/1.0)
2. Play a version of Minecraft that wasn't played by your grandfather
