### ISSUE TITLE
(Suggestion) If Farmer's Delight is installed, make SG knives have the farmersdelight:tools/knives and farmersdelight:straw_harvesters tags

### ISSUE THREAD

**Issue by pm065** [SilentChaos512/Silent-Gear#371]
When the Farmer's Delight mod is installed, give the SG knives the tags that let them cut straw. (They already work on the chopping board since they have the forge:tools/knives tag). As far as I know, there is no way to change the tags of Silent gear on the user side.

**Comment by pm065** [comment]
Oh, wait, you can do this easily with crafttweaker... oops

**Comment by SilentChaos512** [comment]
Or better yet, a data pack
