### ISSUE TITLE
Adamant weapons not yet implemented?

### ISSUE THREAD

**Issue by Slyklaw** [SilentChaos512/Silent-Gear#373]
## Versions

- **Silent Gear**: silent-gear-1.16.3-2.6.13.jar
- **Silent Lib**: silent-lib-1.16.3-4.9.6.jar
- **Forge**: 36.1.2
- **Modpack**: ATM6 v1.5.6
- **Optifine Installed**: No

## Expected Behavior

Invar ingot tooltip says, (Adamant trait) "tools deal more damage to mobs with a base health of more than 10 hearts".

## Actual Behavior

Weapons crafted with Invar do not have an Adamant trait, nor do they appear to have any bonus damage.

**Comment by SilentChaos512** [comment]
The trait not appearing is probably due to a bug that was fixed in version
2.6.21. The bonus damage is still missing however, iirc. I'll get that
fixed when I can.
