### ISSUE TITLE
Problem with new models in 1.16 SGear

### ISSUE THREAD

**Issue by ChromaPIE** [SilentChaos512/Silent-Gear#374]
## Versions

- **Silent Gear**: 2.6.22
- **Silent Lib**: 4.9.6
- **Optifine Installed**: Yes

## Expected Behavior
Models don't make the block on which it's placed transparent.

## Actual Behavior
Models make the block on which it's placed transparent. Not sure if it's caused by the shaderpack, probably not.

## Links/Images
https://imgur.com/a/T1x3cJS

**Comment by najlitarvan** [comment]
known, wait for fix. the hitboxes weren't adjusted yet
