### ISSUE TITLE
Config option for enchantments

### ISSUE THREAD

**Issue by tired9494** [SilentChaos512/Silent-Gear#375]
## What Should Be Added or Changed?
A config option for disabling enchantments on Silent Gear tools/armour. This would either make it impossible to enchant them or make it so that enchantments have no effect on the tool.

## Why Should This Be Done?
Enchantments ruin the customisation and bonuses of Silent Gear tools. Mending, efficiency, etc make the creation of a good tool (in terms of relative durability, speed, etc.) trivial as any weaknesses of your tool can be patched up with enchantments. Of course, this is all my own opinion but I think the ability to disable enchantments would make tool creation a lot more interesting and impactful.

**Comment by Nexus24** [comment]
I'm going to make a pull request for this feature, if it works at all, I'll try to get it merged.

**Comment by tired9494** [comment]
Not to be annoying but is this still being worked on?

**Comment by SilentChaos512** [comment]
Guess I'll take a stab at it.

**Comment by SilentChaos512** [comment]
Ended up adding two configs. One just zeroes out the item's enchantability, which prevents the enchanting table (and maybe some other things) from working on the item. The other is a more brute force option that removes all enchantments already on the item, aside from those added by traits.

**Comment by tired9494** [comment]
Thank you!

**Comment by Nexus24** [comment]
Apologies for not following through on this, some employment hitches prevented me from doing much else for the past few months
