### ISSUE TITLE
Idea For Addon or a Simple idea For silent Gear

### ISSUE THREAD

**Issue by Acmester** [SilentChaos512/Silent-Gear#376]
##   Idea For Addon or a Simple idea For silent Gear

-Upgrades For Materials: Exemple

A block that classifies the categories of a material and that uses a material as fuel (This is already in the game)
It's Simple to make a SSS tier or even a Max tier

- My idea is :Separate the classifications and make the upgrade process more complicated

Like: The normal way (E;D;C;B;A;S;SS;SSS;MAX) to >>> (E;D;C;B;A)
- A to S = Another machine with a diferent fluel (Midgame Vanila (1) item or a New Upgrade item from Silentgear) 
- S to SS = Another machine with a diferent fluel (Lategame Vanila (2)items or a New Upgrade items from Silentgear)
- SS to SSS = Another machine with a diferent fluel (Lategame Vanila (3)items or a New Upgrade item from Silentgear)
- SSS to MAX = Another machine with a diferent fluel (Lategame Vanila (5)items or a New Upgrade items from Silentgear)

## OBS

- *Notes : this new upgrade itens can be a powerful item like a Nether Star , and his fuel can be a Dragon Breath for exemple or another category of new itens for Silentgear(New creaftable iten or a new ore or material or even gems)

- *Notes 2 : I tink is more funny to upgrade and add more content and dificult for the mod , Thanks for Read

**Comment by SilentChaos512** [comment]
I really don't want to introduce more blocks for the same function. But allowing the catalysts to be configured to only allow certain grade ranges could be nice.  It's something worth thinking about, but not something I feel like tackling right now.

**Comment by Acmester** [comment]
Thank you very much for the feedback, I will post more suggestions on the server at #mod ideas
