### ISSUE TITLE
Hybrid gem blade vanishing

### ISSUE THREAD

**Issue by xXCubbie** [SilentChaos512/Silent-Gear#378]
## Versions
 1.16.4

- **Silent Gear**: x.x.x
- **Silent's Gems**: x.x.x  yes
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A  choose some mods myself
- **Optifine Installed**: No  yes

## Expected Behavior

(Description here) I expected to create a normal looking sword, not a cursed one...?

## Actual Behavior
 

(Description here) What happens is, when I put the hybrids with the template, it gives you an example blade

## Links/Images

- (Link)
- 
![1](https://user-images.githubusercontent.com/83208675/116049692-dbdd5780-a676-11eb-9482-45cad1ff2bd3.png)
![2](https://user-images.githubusercontent.com/83208675/116049735-e8fa4680-a676-11eb-9da9-745bc6da875d.png)
![Screenshot_8](https://user-images.githubusercontent.com/83208675/116049297-6b363b00-a676-11eb-9593-13af471a4804.png)
![Bug](https://user-images.githubusercontent.com/83208675/116049301-6bced180-a676-11eb-96ed-c9ff8257a060.png)
![Bug 4](https://user-images.githubusercontent.com/83208675/116049302-6bced180-a676-11eb-908b-6450ce2c3d3c.png)
![Bug 3](https://user-images.githubusercontent.com/83208675/116049303-6c676800-a676-11eb-98e3-a80186163086.png)
![Bug 2](https://user-images.githubusercontent.com/83208675/116049304-6c676800-a676-11eb-86c1-05f59d36f20d.png)
v
[2021-04-25-2.log.gz](https://github.com/SilentChaos512/Silent-Gear/files/6375426/2021-04-25-2.log.gz)

## Steps to Reproduce the Problem

1. Use Pyrope and Kunzite and make a hybrid gem
2. Make a Blade out of the hybrid gem
3. Combine it with a stick or toolrod

**Comment by SilentChaos512** [comment]
Would have appreciated proper version information, but this can be reproduced in 2.6.23 in dev.
