### ISSUE TITLE
Enchantment tokens in Silent's Gear

### ISSUE THREAD

**Issue by foxanthony1** [SilentChaos512/Silent-Gear#379]
I feel that enchantment tokens would fit better in Silent's Gear. As a pack dev and fan of the mod it would certainly help me. I'm trying to get away from the enchantment table in the pack I'm making.

**Comment by SilentChaos512** [comment]
I already made a mod that has just the enchantment tokens. You can find it here: https://github.com/SilentChaos512/Token-Enchanter
