### ISSUE TITLE
Recipes?

### ISSUE THREAD

**Issue by Logics2996** [SilentChaos512/Silent-Gear#381]
Is there a link anywhere to a recipes guide or anything, jei doesn't show recipes, it only shows stats and traits of weapons, armour and tools, iv been searching everywhere for a recipes guide as I'm trying to make a bow but can't find them anywhere? Please help 🙂

**Comment by najlitarvan** [comment]
recipes of what? compounder class stations: alloy, recrystal, refabri just take the same type of material (like metals for alloy and combine them), as for tools you use a blueprint or a template and add materials, depending on those materials and how they are laid out from left to right from top to bottom. the tool will then generate the stats upon that, use u on a template or a blueprint and that should help in jei
also patchouli is in works
