### ISSUE TITLE
Material grading

### ISSUE THREAD

**Issue by foxanthony1** [SilentChaos512/Silent-Gear#383]
Remove it (put it in Silent's Gems? It seems like that's where it belongs).
Or, give me a config option to remove it.

Simplify the mod, please.

Remember when Tinker's Construct first came out?

We all LOVED it!

There was a bit of an initial investment, but we could create the tools we wanted and KEEP them. Silent's gear is (almost) like that.

Material grading adds a random element. That belongs with Silent's Gems. In my opinion, Silent's Gems is for players that want to obsess over their tools. That's cool, for that type of player.

As a modpack developer, I want players to focus on the pack goals, and material grading is a distraction.

Make it just a tools mod. I could do without the sinew (eww!), the salvager, the plants and trees. At least make them config options.

[Example] My modpack is a trainset in Minecraft. It depends on Immersive Engineering which is a hard mod, but building a trainset should be mostly a creative exercise. I need to speed the players through the early game, without just handing them things. It is in peaceful, but they still need tools for building, mining, landscaping etc. I DO NOT want to guide them through this step by step. The pack is for building. The end game is factories and farms, villages and towns, cities, etc. Whatever the player can imagine. It's a trainset. In Minecraft.

**Comment by SilentChaos512** [comment]
You can remove recipes and modify loot tables. Clear the grader catalyst tags, remove the material grader recipe, etc. I'm not a fan of adding configs to "disable" blocks and items, especially since there is no way to clearly define that. They get registered no matter what. But I'm pretty sure I've heard of some mod (maybe CraftTweaker) allowing you to hide items in JEI.

**Comment by foxanthony1** [comment]
Easier to just remove the mod. This pack needs to be simple.
