### ISSUE TITLE
0x arrow damage multiplier

### ISSUE THREAD

**Issue by JonBonJoviFan** [SilentChaos512/Silent-Gear#384]
## Versions

- **Silent Gear**: 2.6.22
- **Silent's Gems**: N/A
- **Silent Lib**: N/A?
- **Forge**: 36.1.2
- **Modpack**: ATM6
- **Optifine Installed**: No

## Expected Behavior
Arrow should deal damage
Arrow was built with full obsidian arrowhead, full obsidian long tool rod, and full feather fletching.

## Actual Behavior
Arrow deals 0 damage

(Description here)

## Links/Images
logs not available

- (Link)

## Steps to Reproduce the Problem

1. build obsidian arrowhead, obsidian long tool rod, and feather fletching
2. put together to make arrow
3. profit

**Comment by SilentChaos512** [comment]
Obsidian does have zero ranged damage for whatever reason, so I'll need to fix that. Or maybe I should change arrows so zero damage arrows can't even happen anymore...

btw, you definitely have Silent Lib. My bigger mods can't run without it.
