### ISSUE TITLE
Armor causing massive FPS issue

### ISSUE THREAD

**Issue by Krisocka** [SilentChaos512/Silent-Gear#389]
We got a massive FPS problem with an armour set we created, having to armor on while alone causes the FPS to drop by 1/3 to 1/2, but if I and a buddy with the same armor get close to each other the the problem amplifies a lot, when all 3 the armors are together it can get into unplayable territory. 
If we all remove one part of the set its a lot better, about the same effect as if we were wearing the full set only ourselves.

Modpack is TNP 3 Limitless + Structurize/Minecolonies
My buddy and I who have the biggest problems both have the i7 2600k, everything else is different between us.

[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/6511219/latest.log)
![grafik](https://user-images.githubusercontent.com/49768131/118875472-64ed5480-b8ec-11eb-95ef-6f6a1c03802b.png)

**Comment by SilentChaos512** [comment]
Please follow the bug report issue template next time. It exists for a
reason...

Include the versions of all relevant mods. Also list the traits on each
armor piece. My guess is that a trait is responsible.

**Comment by Krisocka** [comment]
Sorry, after logging in it only showed a blank page, no choice for bug report/feature request

- **Silent Gear**: 2.6.24
- **Silent's Gems**: 3.7.15
- **Silent Lib**: 4.9.6
- **Forge**:  36.1.18
- **Modpack**: TNP Limitless 3 1.10.3
- **Optifine Installed**: No


Helmet:
 - Crushing II
 - Stellar I
 - Synergistic II
 - Malleable I
 - Flexible II

Chest:
 - Crushing II
 - Stellar I
 - Synergistic II
 - Malleable I
 - Flexible II
 - Lucky I
 - Critical I
 - Imperial I

Leggings:
 - Crushing II
 - Stellar I
 - Synergistic II
 - Flexible II
 - Lucky I
 - Critical I
 - Imperial I

Boots:
 - Crushing III
 - Brittle I
 - Stellar I
 - Synergistic I
 - Bounce
 - Lucky IV

![grafik](https://user-images.githubusercontent.com/49768131/118885341-ed252700-b8f7-11eb-8941-b459cbd8035d.png)
![grafik](https://user-images.githubusercontent.com/49768131/118885403-029a5100-b8f8-11eb-846f-8ba10af1399a.png)
![grafik](https://user-images.githubusercontent.com/49768131/118885459-15148a80-b8f8-11eb-8c62-50bfcb2c2cdb.png)

**Comment by SilentChaos512** [comment]
Added some possible performance improvements to potion effect traits in version 2.6.25. Please let me know if this changes anything for you.

**Comment by SilentChaos512** [comment]
Closed according to conversation on Discord. Re-open if the issue persists.
