### ISSUE TITLE
[Bug] 1.14.4 - Crash on launch - ItemColors rendering

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/Silent-Gear#39]
## Versions
- **Silent Gear**: 1.3.2+51
- **Silent's Gems**: 3.3.1+56
- **Silent Lib**: 4.3.0+38 
- **Forge**: 28.0.14
- **Modpack**: N/A

## Expected Behavior
Pack to load as normal

## Actual Behavior
Crash on pack (Forge .14) or world load (.22)

Log indicates an issue with ItemColor rendering, pointing to Silent Gear.

## Links/Images
https://pastebin.com/q0qPGQvd

## Steps to Reproduce the Problem
1. Update to above mod versions
2. Load pack
3. Crash

**Comment by SilentChaos512** [comment]
Is this crashing consistently, or just occasionally?

**Comment by GamertechAU** [comment]
Every time

**Comment by SilentChaos512** [comment]
I believe you are experiencing [this issue](https://github.com/MinecraftForge/MinecraftForge/issues/5862). Definitely something Forge needs to fix, but I can make a few changes which should prevent the crash.

**Comment by SilentChaos512** [comment]
Should be fixed in 1.3.3

**Comment by GamertechAU** [comment]
Can confirm working in 1.3.3. Cheers as always Silent
