### ISSUE TITLE
Cannot figure out material combination to harvest Azure Silver ore

### ISSUE THREAD

**Issue by reckonedstormlight** [SilentChaos512/Silent-Gear#391]
Forge: 36.1.16
Minecraft: 1.16.5
Silent gear: 1.16.3-2.6.19

Got to the end and wanted to mine azure silver ore. Says it needs harvest level 4. Spent the better part of 2 days trying out different materials and combinations and not a single thing goes above 3, even netherite. What can be done?

**Comment by SilentChaos512** [comment]
Netherite should work. Make sure you are looking at the correct value. The
lines added by Pickle Tweaks are bugged. Hold Ctrl and check the real value.
