### ISSUE TITLE
Armor has wrong color when equipped

### ISSUE THREAD

**Issue by xXCubbie** [SilentChaos512/Silent-Gear#392]
## Versions
 Minecraft 1.16.4

- **Silent's Gems**: x.x.x 1.16.3 3.7.14
- **Silent Gear**: x.x.x  1.16.5 2.6.25
- **Silent Lib**: x.x.x  1.16.3 4.9.6
- **Forge**: x.x.x  1.16.4 35.1.37
- **Modpack**: N/A  no
- **Optifine Installed**: Yes

## Expected Behavior

I made two types of armor, one with moonstone-jade-emerald-moonstone-jade-emerald-jade-emerald, and one with hybrid gems consisting of moonstone, jade and emerald. It gave the chestplate item a nice green color. I expected to see the same dark green color when equipping the armor.

## Actual Behavior

The Armor in my armor slot is still dark green, but the armor on my mc skin when pressing f5 is gray. Removing Optifine doesn't help, and it's the same for other constructions I did too. I think it most likely occurs when its like 1,2,3,1,2,3,2,3 instead of like 1,1,2,2,3,3,3,3 or something. (1 being gem 1, 2 being another gem and 3 being a third gem). So what I wanna say is, I think if it doesnt follow the 1,1,2,2,3,3,4,4 order thing, so they're put in more or less likely in random orders, this bug occurs. I made a chestplate with garnet (1) and amethyst (2) in following order: 1,1,1,1,1,1,2,2. It then showed the right color, maybe just a coincidence though as this orange color I got from the garnet amethyst one seems to appear often when the bug occurs.

## Links/Images

- (Link)
![image](https://user-images.githubusercontent.com/83208675/119667727-d66e5b00-be36-11eb-8b2d-af4a19d6d7b5.png)

- (Another link, if needed)
- [latest.log](https://github.com/SilentChaos512/SilentGems/files/6547141/latest.log)

## Steps to Reproduce the Problem

1. Get 2 max graded moonstone, 3 max graded jade and 3 max graded emerald (or use hybrid gems instead, use moonstone, jade and emerald for the hybrid gem, one of each and in this order, also max graded)
2. Get a chestplate template and do the following construction: moonstone, jade, emerald, moonstone, jade, emerald, jade, emerald. (Or just use 8 hybrid gems instead)
3. Equip the chestplate after its done

**Comment by najlitarvan** [comment]
i think it is actually not rendering any color at all

**Comment by SilentChaos512** [comment]
Partial duplicate of #192. Should have all armor models rendering correctly now.
