### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Switch-Back18** [SilentChaos512/Silent-Gear#393]
## Versions

- **Silent Gear**: 2.6.22
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.2
- **Modpack**: Stacia Expert
- **Optifine Installed**: No

## Expected Behavior

Launch the modpack with my custom launcher

## Actual Behavior

I want to start the game but that crash.
I don't know why but i use custom launcher

## Links/Images

- https://hastebin.com/ozowewiwab.rb

## Steps to Reproduce the Problem

1.Use a custom launcher
2.Lauch the modpack
3.That crash

**Comment by SilentChaos512** [comment]
Can you reproduce this with only Silent Gear and Lib installed? And any
idea what `joptsimple` is? None of my code references that package. Seems
like you have something that's modifying code.

**Comment by SilentChaos512** [comment]
Okay, that's weird. Apparently I did screw up an import somehow. I wonder why most users don't crash though?

**Comment by Switch-Back18** [comment]
I tried with only silent gear and lib that not works
then i tried without silent gear and that works the problem is from silent gear
