### ISSUE TITLE
Silent Gear Golden & Iron Swords Attack Speeds Differ from their Vanilla Counterparts

### ISSUE THREAD

**Issue by jecowa** [SilentChaos512/Silent-Gear#394]
## Versions

- **Silent Gear**: 1.16.5-2.6.24
- **Silent's Gems**: N/A
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.18
- **Modpack**: [CRIF](https://www.curseforge.com/minecraft/modpacks/create-an-empire-of-rats-to-fight-ice-and-fire)
- **Optifine Installed**: No

## Expected Behavior

Silent Gear Golden & Iron Swords to have the same attack speeds as their vanilla counterparts

## Actual Behavior

Silent Gear Golden Sword (w/ stick rod) - 1.8 attack speed
Vanilla Golden Sword - 1.6 attack speed

Silent Gear Iron Sword (w/ stick rod) - 1.5 attack speed
Vanilla Iron Sword - 1.6 attack speed

In particular, I'm curious about the Iron Sword, since it is worse than the vanilla version in this regard. I noticed this when checking to see how vanilla materials were adapted to Silent Gear and the discord told me that this was probably not intentional for their attack speeds to be different.

## Steps to Reproduce the Problem

1. Craft Silent Gear Gold or Iron sword using the same materials as their vanilla counterpart

**Comment by SilentChaos512** [comment]
While the attack speed differences were intended, I do believe it should be changed.

**Comment by SilentChaos512** [comment]
Also adjusted the speeds for axes to match vanilla, and discovered and fixed a bug along the way. Yay.
