### ISSUE TITLE
Shears not working as intended?

### ISSUE THREAD

**Issue by Th4tM0nk3y** [SilentChaos512/Silent-Gear#397]
## Versions

- **Silent Gear**: 2.6.26
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.31
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/vervains-builder-dream
- **Optifine Installed**: No 

## Expected Behavior
Silent Gear Shears breaking and dropping leaf blocks

## Actual Behavior
Normal drops (sticks, apples) drop, instead of the expected leaf blocks

## Steps to Reproduce the Problem

1. Craft Silent Gear Shears of any type
2. Whack tree leaves
3. see drops (if any)

**Comment by SilentChaos512** [comment]
What types of leaves does this affect? Just modded ones, or vanilla as well?

**Comment by Th4tM0nk3y** [comment]
Tested this just now, seems to be only modded.
The ones included in the mentioned pack are "Quark" and "Oh the Biomes you'll go" specifically.

**Comment by OGitsBoondock** [comment]
Are Nouveau also not working.  Seems to be the same issue that arose in the 1.16.2 version i believe it was.  I have tried multiple materials etc.   Looking through byg I don't see missing tags for leaves at least, last time I asked Corgi about this he verified it was something on silent end but you fixed it with a minor update.  I can't for the life of me remember any more sorry.
Plants requiring shears not working either.

**Comment by SilentChaos512** [comment]
Also affects netherwood leaves, ironically. I can fix that at least. But since loot tables are responsible for block drops, I don't believe there's anything else I can do for the other mods. They should update their loot tables to check for the `forge:shears` _tag_, instead of the `minecraft:shears` _item_.
