### ISSUE TITLE
Blueprint package doesn't provide any blueprints (new world)

### ISSUE THREAD

**Issue by Nahkranoth0** [SilentChaos512/Silent-Gear#40]
## Versions

- **Silent Gear**: 1.3.2+51
- **Silent Lib**: 4.3.0+38
- **Forge**: 28.0.20
- **Modpack**: N/A

## Expected Behavior
Blueprint package providing me with the starter blueprints as it would be on previous versions

## Actual Behavior
Upon creation of world, i've used (right-click) the blueprint package and, to my surprise, the package disappeared and there was no blueprints in the inventory. I've created other worlds and the same issue occurred

## Links/Images
I've traced this warning regarding the package in the logs
https://pastebin.com/kYLLSfJN
[18:05:03] [Server thread/WARN]: LootContainerItem has no drops? 1 blueprint_package, table=silentgear:starter_blueprints

## Steps to Reproduce the Problem
Open the blueprint package to make it disappear and not give anything in return

**Comment by SilentChaos512** [comment]
Could I get a full log file, please? I just tested this and had no issues.

**Comment by Nahkranoth0** [comment]
https://pastebin.com/kYLLSfJN

Here it is

**Comment by Nahkranoth0** [comment]
@SilentChaos512, i've created a new world with just Silent Gear and Corail Tombstone, and now it is working, I'll keep investigating further to see what is causing the issue and get back to you

**Comment by Nahkranoth0** [comment]
Ok from what i could test of all the mods, i found that structurize-0.10.123-ALPHA.jar is causing the issue. As soon as i run into a new world, or even a existing one, the blueprints didn't appear.
Thanks for your time in this. Have nice day
