### ISSUE TITLE
Material grader missing

### ISSUE THREAD

**Issue by ssbugman** [SilentChaos512/Silent-Gear#403]
## Versions

- **Silent Gear**: 1.16.5-2.6.27
- **Silent's Gems**: 1.16.3-3.7.15
- **Silent Lib**: 1.16.3-4.9.6
- **Optifine Installed**: No

## Expected Behavior
Material Grader exist is game.

## Actual Behavior
Material Grader not exist in game.

## Steps to Reproduce the Problem
Just launch game and search for material grader in JEI. There no material grader in game.

**Comment by SilentChaos512** [comment]
The material grader shows up in dev. Whatever mod pack you are playing may be hiding it intentionally.
