### ISSUE TITLE
Traits Disappearing when scrolling through hotbar

### ISSUE THREAD

**Issue by EvilKingStan** [SilentChaos512/Silent-Gear#404]
## Versions

- **Silent Gear**: 2.6.27
- **Silent's Gems**: N/A
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.32
- **Modpack**: ATM 6
- **Optifine Installed**: Yes

## Expected Behavior
When Scrolling, Traits should remain on Aluminum Paxel

## Actual Behavior
When Scrolling on hot bar, all Traits will be removed from Aluminum Paxel. To put them back on I use a extra tool rod to switch on and then switch back to the original tool rod I had on, this is just a temporary fix however and eventually the tool will lose its traits again. It is not effecting the Hammer or Spear both from silent Gear that I also have on my hotbar. I also just tried with and without the enchant I had on it and it still happens both with and without Unbreaking IV

Paxel setup
Aluminum Paxel Head
Aluminum first 4 slots 
Iron in last spot

Diamond tip upgrade 
one diamond first slot.

Aluminum Tool Rod
Aluminum first spot
Iron second spot

## Steps to Reproduce the Problem

1. Place paxel in hotbar, with Traits as normal
2. Scroll back and forth between items, faster can make it happen quicker but, it has and does happen at normal scrolling speed during normal gameplay not just when I'm trying to make it happen.
3. check Traits with hover over paxel and hold "show Traits" key and list of traits won't show anything.

![paxelNoTraits](https://user-images.githubusercontent.com/46544754/124525100-1bcd6300-ddbb-11eb-9f5e-4bad41910a4c.png)

**Comment by EvilKingStan** [comment]
Forgot to mention also that the effects of the traits are NOT active when not listed. like the magnetic III doesn't work at all after the traits have disappeared. Just to help rule out the possibility of visual only bug.

**Comment by SilentChaos512** [comment]
Going to need at least a log file on this. There is no way this is reproducible normally. I've never heard of anything like it.

**Comment by Kenshij** [comment]
Have it too. It is since i tiped them with manasteal. When i have no mana tablet in my inventory and it is damaged, it looses all traits on scrolling. Repair even with empty repair kit brings all traits back. No problem when there is a mana tablet in my inventory. 

Can't reproduce it in a fresh world.

**Comment by Linguardium** [comment]
ATM6 - 1.6.14

I have had this issue with a glowstone tipped paxel. I am unsure if its ever been an issue before this as i don't pay attention to the traits normally, but suddenly not being able to place light sources is very noticeable. As stated, "repairing" fixes it temporarily. The logs do not show any errors or make mention of anything failing.
Restarting/save+exit the game (single player) resolves the issue as well.

I can 100% reproduce this by placing a 2nd paxel (currently tipped netherite glowstone) in a slot next to the original and scrolling onto it then back to the first.

Paxel A:
Stone 
Wooden tool rod
Glowstone+emerald tip

Paxel B:
Obsidian, brass x4
Wooden tool rod
Netherite coating
Glowstone Emerald tip

Choose slot 2 in the hotbar
Paxel A in slot 2, Paxel B in slot 1.
Choose Paxel A in the hotbar
scroll from slot 2 to slot 1 (A to B)
scroll back to slot 2
Traits are now missing on the Stone Paxel

This is scroll direction agnostic
Placing an item between them seems to alleviate the issue of scrolling (A in slot 1, another item in 2, B in slot 3)
This issue also happens under other circumstances but I havent been able to pin down exactly what does it.

**Comment by yohancool123** [comment]
Have the same problem. playing on All The Mods 6 1.7.6 version modpack. it didn't seemed to occur at the begining when i made the paxel, i have used the paxel for a while without the bug. i don't know what started the bug might be the tip (diamond and glowstone) or the glowstone trait since i started to use paxel as a torch too.

**Comment by SilverTemper** [comment]
I have the same thing happen to my shield when I put it in the shield slot.  I'm also playing the All the  Mods 6 pack.

**Comment by littlebear22** [comment]
I have my tools occasionally lose their traits as well, when playing ATM 6.  (v1.8.14)  Just noticed it now with a brass mattock.  It was "silky" a few minutes ago.  Now it shows no traits and no longer silk touches blocks when harvesting them.  Repairing the item brings back the traits for me too.  (It's a nasty surprise when you go to pick up that supremium farmland thinking you have silk touch and... yeah).

**Comment by GGServersDevelopment** [comment]
> Going to need at least a log file on this. There is no way this is reproducible normally. I've never heard of anything like it.

In my ATM6 1.8.14 & 1.8.15(happens after update as well, not sure if silent wwas updated in this one though) world I can reproduce this every single time without exception. The easiest way I found was to simply put the tool/weapon in the offhand, and select a non silentgear tool/weapon in the main hand, the traits disappear and become inactive.
