### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by DDogeOneeSama** [SilentChaos512/Silent-Gear#407]
## Versions

- **Silent Gear**: 2.6.27
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.32
- **Modpack**: All The Mods 6 
- **Optifine Installed**: No 

## Expected Behavior

Join Server

## Actual Behavior

When I try to join a server it throws an internal exception error.
Have fully uninstalled the modpack and changed modpack launchers and nothing has changed.
Joining the server worked one day stopped working the next.

## Links/Images

https://imgur.com/a/iAHwvtV

**Comment by SilentChaos512** [comment]
The server is using a newer version of Silent Gear than you are. They must have updated, and you can't connect because you're running an older version.
