### ISSUE TITLE
Poison damages armor

### ISSUE THREAD

**Issue by iakfar** [SilentChaos512/Silent-Gear#408]
## Versions

- **Silent Gear**: 1.16.5-2.6.30
- **Silent's Gems**: N/A 
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.65
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Getting poisoned doesn't damage armor.

## Actual Behavior

Getting poisoned damages armor.

## Links/Images

https://youtu.be/YEtME11eTSg

## Steps to Reproduce the Problem

1. Get poisoned from commands/witch/cave spider.
2. Watch armor go down.

**Comment by lele92007** [comment]
The minecraft wiki says : 

" The following types of damage are not reduced by ordinary armor and have no effect on the armor's durability. Some enchantments can protect against them, but they still don't damage the armor.
    Ongoing damage from being on fire
    Suffocating inside a block or due to entity cramming (also includes the world border)
    Drowning in water (partially for turtle shells)
    Starvation
    Fall damage (including Ender Pearl)
    Falling into the void or /kill
    Colliding a block with an elytra
    The Poison, Wither and Instant Damage status effects
    Being inside of a powder snow block "

But, I found a reddit post on minecraft suggestion of someone with the same issue.
I will test myself later.

EDIT : Which MC version ?

**Comment by iakfar** [comment]
16.5, I tried vanilla on it too and it worked as the wiki said

**Comment by ExiledMiner04** [comment]
Was poisoned by witches and it happened in 1.17.1

**Comment by zaeonNineZero** [comment]
Can confirm this bug also occurs in 1.16.5 running version 1.16.5-2.6.36, on Forge version is 36.2.35.  This bug is not limited to Silent Gear armor - all armor, both vanilla and modded, takes durability damage from poison damage, and this does not occur when Silent Gear is not installed.  Imo, it is a pretty game-breaking bug, as a few cave spiders or one witch can tear apart your armor in a few hits thanks to the poison damage.

**Comment by SilentChaos512** [comment]
Does anyone know if this occurs on 1.18.2?

**Comment by SilentChaos512** [comment]
I still need to test this, but I think the issue is in `GearEvents#onLivingHurtMagicArmor`. The code ignores the type of armor (which is a bug in itself) and poison damage is, unfortunately, considered to be magic damage...
