### ISSUE TITLE
[2.6.30][atm-6] Holding broken sg item in causes severe lag

### ISSUE THREAD

**Issue by radiomike** [SilentChaos512/Silent-Gear#409]
## Versions

- **Silent Gear**: 2.6.30
- **Silent's Gems**: N/A
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.65
- **Modpack**: atm-6
- **Optifine Installed**: No 

Also note this is on a server, haven't tested in single player.

## Expected Behavior
No lag, or significant impact on performance.

## Actual Behavior

Significant impact on tps and depending on tool held fps also impacted.
Worse with some items, particularly pickaxes. less so on shovels.

## Links/Images

Spark profile with SG iron pick in hand
https://spark.lucko.me/TKstlpPTtT

Reference profile with empty hand
https://spark.lucko.me/mFR1CzLPeO

## Steps to Reproduce the Problem

1. Hold a broken SG tool in hand
2.
3.

**Comment by ProjectGSX** [comment]
Im seeing this with both damaged and fully repaired SG tools.
