### ISSUE TITLE
Minecraft crashes when viewing Parts List when custom tips are added via datapack

### ISSUE THREAD

**Issue by EnbyChu** [SilentChaos512/Silent-Gear#41]
## Versions

- **Silent Gear**: 1.3.3+52  
- **Silent's Gems**: 3.3.1+56
- **Silent Lib**: 4.3.0+38  
- **Forge**: 28.0.23
- **Modpack**: Custom Modpack (I can send an list if needed, there are 40+)

## Expected Behavior

- When loading the Parts list in the Crafting Station, I should be able to see all of the parts I have added, including the custom tip upgrades that were added in SilentGear 1.3.2.

## Actual Behavior

- When attempting to open the Parts List, the game hangs for a few seconds before crashing, giving me a Rendering Screen error. No such error occurs when no custom tips are added, and no such error occurs when crafting the custom tips. The parts list screen is the only time the rendering error occurs. Additionally, this issue does NOT occur when using the test upgrade part for Crimson Steel that was provided on Discord.

## Links/Images
[Crash Report](https://pastebin.com/S19Uub1w) This crash report references RandomPatches, another mod, but I have tested this issue without the mod and it still occurs as described.
[Custom Datapack](https://www.dropbox.com/s/z52vhyd9zyyh7h3/customsgear%20EnbyChu.zip?dl=0) Contains the files for my custom tips, in case how I structured them is somehow causing the crash.

## Steps to Reproduce the Problem

1. Use the linked copy of my data pack and add it to a world.
2. Place the Crafting Station and look at the Parts List
3. Game should crash

**Comment by SilentChaos512** [comment]
There's an extra closing curly brace in the magma cream tip part, inside `crafting_items`. Should look like this:

```json
"crafting_items": {
    "custom_tipped_upgrade": {}
}
```

Strange that it actually crashes the game. It should just fail to load the file. If nothing else, I see a way to prevent the crash.

**Comment by EnbyChu** [comment]
Wow I can't believe that one curly bracket crashed Minecraft, thanks so much! I got rid of it and everything works as expected now.
