### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Awesomespore** [SilentChaos512/Silent-Gear#414]
## Versions

- **Silent Gear**: 1.16.5-2.6.30
- **Silent's Gems**: 1.16.3-3.7.16 
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.65
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

I expect the console to not be spammed

## Actual Behavior

The console gets spammed with what I can only assume is rendering info (I think whenever I hold one of the tools? I'm not quite sure)
This doesn't seem to directly cause any crashes, but doesn't seem good either

## Links/Images

![image](https://user-images.githubusercontent.com/59407684/128997499-d6dfb511-0e30-4f8a-bef8-fb9516334844.png)

## Steps to Reproduce the Problem

1. Have tools
2. Exist
3. Look at console

**Comment by SilentChaos512** [comment]
This can be disabled by changing the `debug.logging.modelAndTexture` config in `silentgear-common.toml` back to its default value of `false`.
