### ISSUE TITLE
[1.17] Mattock having the AIOT ability (Harvesting all blocks) 

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#420]
The Mattock is being flagged as a Hoe, shovel, pickaxe, and axe. 

I am using The One Prove and the Mattock is being allowed to harvest with efficiency all blocks. 

I am using the silent-gear-1.17.1-2.7.2.jar version

**Comment by Sleet827** [comment]
It is supposed to

**Comment by SilentChaos512** [comment]
It's not meant to be a pickaxe. Just a shovel and axe.

**Comment by Sleet827** [comment]
Oh, well, I might have been a bit hasty to not make a diamond pickaxe lol.
Just made diamond sword with iron rod and diamond mattock with stone rod
