### ISSUE TITLE
Problems with adornments in MineCraft 1.17.1

### ISSUE THREAD

**Issue by Reckis** [SilentChaos512/Silent-Gear#422]
## Versions

- **Silent Gear**: 2.7.2
- **Silent's Gems**: x.x.x 
- **Silent Lib**: x.x.x
- **Forge**: 37.0.44
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Tooltips indicate that Flint, Lapis, and Emerald can be used to create adornments for curios.

## Actual Behavior

When placing a Jeweler's Kit and any of the above materials into a crafting grid, no output results.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Place a Jeweler's Kit in the crafting grid.
2. Place any of the three materials listed above in the crafting grid.
3. Output slot remains empty.

**Comment by GhostieEcho** [comment]
For further information that may assist with correcting this bug, I've reviewed the recipes and found that the one to create the adornment requires an adornment blueprint, which I was unable to find the recipe to create, and doesn't exist according to JEI.  

Specifically... 

{
  "type": "silentgear:gear_crafting",
  "ingredients": [
    {
      **"type": "silentgear:blueprint",
      "part_type": "silentgear:adornment"**
    },
    {
      "item": "silentgear:bracelet_band"
    },
    {
      "type": "silentgear:part_type",
      "part_type": "silentgear:adornment"
    }
  ],
  "result": {
    "item": "silentgear:bracelet"
  }
}

**Comment by GhostieEcho** [comment]
After further chasing down details, I found that the Jeweler's Kit is identified as the adornment blueprint (although it's not visible anywhere while playing).  After finding the adornment recipe, and now knowing the Jeweler's Kit is the blueprint, I was successfully able to craft the adornment by adding the Bort specified in the recipe.
{
  "type": "silentgear:compound_part",
  "ingredients": [
    {
      "type": "silentgear:blueprint",
      "part_type": "silentgear:adornment"
    },
    {
      **"item": "silentgear:bort"**
    },
    {
      "type": "silentgear:material",
      "part_type": "silentgear:adornment"
    }
  ],
  "result": {
    "item": "silentgear:adornment"
  }
}

**Comment by SilentChaos512** [comment]
Seems to be working as intended then. Bort was added to make creating adornments more difficult. The old recipe was left in place only until the next major update, which was 1.17.
