### ISSUE TITLE
1.16.5 Ice Dragonsteel Alloy losing ability to deal damage.

### ISSUE THREAD

**Issue by Sarelth** [SilentChaos512/Silent-Gear#424]
## Versions

- **Silent Gear**: 2.6.30
- **Silent's Gems**: x3.7.16
- **Silent Lib**: 4.9.6
- **Forge**: 36.2.2
- **Modpack**: Chroma Tecchnology 2
- **Optifine Installed**: Yes

## Expected Behavior
Dealing damage when used in a sword blade.

## Actual Behavior
In Chroma Tech 2 I made an alloy of 2 Ice Dragonsteel, 1 Fire Dragonsteel, and 1 Lightning Dragonsteel. The sword that I made worked fine for a while, then randomly lost the ability to deal damage, 3 separate blades had this happen. It seemed to only happen after using the /home command, but not really sure.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Alloy the 3 Dragonsteel types, adding an extra Ice Dragonsteel.
2. Fight a bunch of things
3. use /home to get back to base
4. Does not happen every time, but when it does the only solution currently found is to replace the blade of the sword with another one of a different material, the original blade stays glitched even after relogging.

**Comment by SilentChaos512** [comment]
Is it only the Dragon Gear materials that are affected? Did you report to Dragon Gear as well?

**Comment by Sarelth** [comment]
I tried it with alloys of the 3 types of Dragonsteel, and only the one with 2 Ice had the weird glitch. I did not report it to Dragon gear, did not realize that was a thing, but I just posted it there as well.

**Comment by Sarelth** [comment]
This is the bugged sword info, I was able to get a server admin to grab it for me. Not sure if it will help or not. 

`{id: "silentgear:sword", Count: 1b, tag: {SGear_UUID: [I; -2085259005, -1097510973, -1100292296, -1879467975], RepairCost: 63, SGear_Data: {Construction: {Parts: [{Item: {id: "silentgear:sword_blade", Count: 1b, tag: {CraftedCount: 1, Materials: [{Item: {id: "silentgear:alloy_ingot", Count: 1b, tag: {SGear_Grade: "MAX", Materials: [{Item: {id: "iceandfire:dragonsteel_fire_ingot", Count: 1b}, ID: "iafgear:dragonsteel/fire_dragonsteel"}, {Item: {id: "iceandfire:dragonsteel_ice_ingot", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 2s, id: "silentgems:supercharged"}]}}, ID: "iafgear:dragonsteel/ice_dragonsteel", Count: 2b}, {Item: {id: "iceandfire:dragonsteel_lightning_ingot", Count: 1b}, ID: "iafgear:dragonsteel/lightning_dragonsteel"}], Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "silentgear:metal_alloy", Count: 2b}]}}, ID: "silentgear:sword_blade"}, {Item: {id: "silentgear:rod", Count: 1b, tag: {CraftedCount: 4, Materials: [{Item: {id: "silentgear:blaze_gold_ingot", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}]}}, ID: "silentgear:blaze_gold", Count: 2b}]}}, ID: "silentgear:rod"}, {Item: {id: "silentgear:binding", Count: 1b, tag: {CraftedCount: 1, Materials: [{Item: {id: "silentgems:gilded_string", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}]}}, ID: "silentgems:gilded_string"}]}}, ID: "silentgear:binding"}, {Item: {id: "silentgear:grip", Count: 1b, tag: {CraftedCount: 1, Materials: [{Item: {id: "silentgear:mixed_fabric", Count: 1b, tag: {SGear_Grade: "MAX", Materials: [{Item: {id: "minecraft:leather", Count: 1b, tag: {SGear_Grade: "MAX"}}, ID: "silentgear:leather"}, {Item: {id: "minecraft:phantom_membrane", Count: 1b, tag: {SGear_Grade: "MAX"}}, ID: "silentgear:phantom_membrane"}], Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}]}}, ID: "silentgear:mixed_fabric"}]}}, ID: "silentgear:grip"}, {Item: {id: "silentgems:gear_soul", Count: 1b, tag: {SG_GearSoul: {skills: [], xp: 0, element1: "LIGHTNING", level: 1, element2: "VENOM"}}}, ID: "silentgems:gear_soul"}, {Item: {id: "silentgear:coating", Count: 1b, tag: {CraftedCount: 2, Materials: [{Item: {id: "elementalcraft:fireite_ingot", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "elementalcraft:fireite_ingot"}, {Item: {id: "minecraft:netherite_ingot", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "silentgear:netherite"}]}}, ID: "silentgear:coating"}, {Item: {id: "silentgear:tip", Count: 1b, tag: {CraftedCount: 1, Materials: [{Item: {id: "silentgear:hybrid_gem", Count: 1b, tag: {SGear_Grade: "MAX", Materials: [{Item: {id: "minecraft:quartz", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "silentgear:quartz"}, {Item: {id: "minecraft:lapis_lazuli", Count: 1b, tag: {SGear_Grade: "MAX", Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "silentgear:lapis_lazuli"}], Enchantments: [{lvl: 3s, id: "silentgems:supercharged"}, {lvl: 3s, id: "silentgear:star_charged"}]}}, ID: "silentgear:hybrid_gem"}]}}, ID: "silentgear:tip"}]}, Properties: {ModVersion: "2.6.30", Stats: {"silentgear:enchantability": 2757.196f, "silentgear:harvest_speed": 418.1424f, "silentgems:chargeability": 1.5034782f, "silentgear:harvest_level": 14.0f, "silentgear:durability": 5.3828531E8f, "silentgear:melee_damage": 232.2297f, "silentgear:magic_damage": 58.505478f, "silentgear:attack_speed": -1.9245455f, "silentgear:rarity": 345.6832f, "silentgear:repair_efficiency": 1.1254902f}, LockStats: 0b, Traits: [{Level: 1b, Name: "iafgear:dragon_defense"}, {Level: 1b, Name: "iafgear:dragondamage_ice"}, {Level: 3b, Name: "silentgear:flexible"}, {Level: 2b, Name: "silentgear:synergistic"}, {Level: 2b, Name: "silentgear:ancient"}, {Level: 4b, Name: "silentgems:soul/magic_damage"}, {Level: 3b, Name: "silentgems:soul/durability"}, {Level: 2b, Name: "silentgems:soul/aerial"}, {Level: 1b, Name: "silentgems:soul/skull_collector"}, {Level: 1b, Name: "silentgems:soul/aquatic"}, {Level: 1b, Name: "silentgems:soul/harvest_speed"}, {Level: 1b, Name: "silentgear:fireproof"}, {Level: 1b, Name: "silentgear:chipping"}, {Level: 3b, Name: "silentgear:jagged"}]}, Rendering: {ModelKey: "sword:sword_blade{metal_alloy[[iafgear:dragonsteel/fire_dragonsteel,iafgear:dragonsteel/ice_dragonsteel*2iafgear:dragonsteel/lightning_dragonsteel]],metal_alloy[[iafgear:dragonsteel/fire_dragonsteel,iafgear:dragonsteel/ice_dragonsteel*2iafgear:dragonsteel/lightning_dragonsteel]]},rod{blaze_gold,blaze_gold},binding{silentgems:gilded_string},grip{mixed_fabric[[leatherphantom_membrane]]},silentgems:gear_soul,coating{elementalcraft:fireite_ingot,netherite},tip{hybrid_gem[[quartzlapis_lazuli]]},"}}, display: {Name: '{"text":"Blade of Thieves"}'}, Enchantments: [{lvl: 6s, id: "cyclic:beheading"}, {lvl: 3s, id: "cyclic:life_leech"}, {lvl: 5s, id: "tombstone:magic_siphon"}, {lvl: 4s, id: "minecraft:looting"}, {lvl: 7s, id: "apotheosis:capturing"}, {lvl: 3s, id: "apotheosis:scavenger"}, {lvl: 4s, id: "minecraft:sweeping"}, {lvl: 3s, id: "silentgems:ice_aspect"}, {lvl: 10s, id: "minecraft:sharpness"}, {lvl: 5s, id: "silentgems:life_steal"}, {lvl: 5s, id: "cyclic:disarm"}, {lvl: 3s, id: "cyclic:ender"}, {lvl: 6s, id: "cyclic:venom"}, {lvl: 4s, id: "minecraft:unbreaking"}, {lvl: 5s, id: "apotheosis:sea_infusion"}, {lvl: 1s, id: "tombstone:soulbound"}, {lvl: 2s, id: "cyclic:magnet"}, {lvl: 1s, id: "minecraft:mending"}], SG_GearSoul: {skills: [{level: 4s, id: "silentgems:soul/magic_damage"}, {level: 3s, id: "silentgems:soul/durability"}, {level: 2s, id: "silentgems:soul/aerial"}, {level: 1s, id: "silentgems:soul/skull_collector"}, {level: 1s, id: "silentgems:soul/aquatic"}, {level: 1s, id: "silentgems:soul/harvest_speed"}], xp: 80248, element1: "LIGHTNING", level: 13s, element2: "VENOM"}, Damage: 1}}`
