### ISSUE TITLE
[1.17.1] Stacktrace on load- java.lang.NoSuchFieldException: maxDamage

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/Silent-Gear#427]
## Versions

- **Silent Gear**: silent-gear-1.17.1-2.7.2
- **Silent's Gems**: x.x.x 
- **Silent Lib**: silent-lib-1.17.1-5.0.0
- **Forge**: .51
- **Modpack**: [TownCraft THREE for 1.17.1](https://www.curseforge.com/minecraft/modpacks/towncraft)
- **Optifine Installed**: No 

## Actual Behavior

https://gist.github.com/ProsperCraft/aacc4265de438fb4125f0a01a93a04ef

**Comment by SilentChaos512** [comment]
Hmm, okay. Not the first time `ObfuscationReflectionHelper` has caused me problems. But I can fix it.
