### ISSUE TITLE
Incompatibility with Aequivaleo.

### ISSUE THREAD

**Issue by furtabs** [SilentChaos512/Silent-Gear#428]
## Versions

- **Silent Gear**: 2.6.30
- **Silent's Gems**: 3.7.16
- **Silent Lib**: 4.9.6
- **Forge**: 33.2.2
- **Modpack**: N/A
- **Optifine Installed**: No
- **Aequivaleo**: 0.1.52

## Expected Behavior
To my knowledge this is more of an issue with how Aequivaleo works, but its something you in your mod are doing wrong

(Description here)

## Actual Behavior
The game will eventually run out of memory and lock up. I would recommend talking to Aeq's developer @OrionDevelopment

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Load the game
2. wait for it to lock up
3.

**Comment by marchermans** [comment]
This has been fixed on Aequivaleos side.
Aequivaleos implementation for cycle reduction had a bug which surfaced when combined with Silent Gears.

This issue can be closed.
