### ISSUE TITLE
[1.17] Spoon upgrade not working on pickaxe

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#429]
## Versions

- **Silent Gear**: silent-gear-1.17.1-2.7.3.jar
- **Silent's Gems**: x.x.x  N/A
- **Silent Lib**: silent-lib-1.17.1-5.0.0.jar
- **Forge**: 37.053
- **Modpack**: N/A 
- **Optifine Installed**: No  

## Expected Behavior

Pickaxe should now be able to harvest the same as a shovel
## Actual Behavior

Nothing changes, Pickaxe can't harvest dirt efficiently 
## Links/Images

![image](https://user-images.githubusercontent.com/44974827/132285946-d5a9808a-b2a5-43b3-83bf-ed856ff3483d.png)
![image](https://user-images.githubusercontent.com/44974827/132286004-8651a0ac-28e0-4b6d-b934-43eb333a11f4.png)

## Steps to Reproduce the Problem

1. Add the spoon upgrade to a pickaxe
2. try to dig dirt
3. fail

**Comment by RamenNoodles** [comment]
I'd like to add that the shovel part of paxel also doesn't working, you'll notice that a mattock will dig through dirt faster than a paxel.  Tested this with a diamond paxel and iron mattock, the mattock would dig faster.

**Comment by SilentChaos512** [comment]
@RamenNoodles Same version as above? Pretty sure that one was fixed already.

**Comment by RamenNoodles** [comment]
@SilentChaos512 yes, double checked same version as above, redownloaded it to be sure. Just made diamond paxel, iron mattock and shovel in a new world and they dig faster than the paxel.
