### ISSUE TITLE
Netherite not working as expected in repair kits or on tools

### ISSUE THREAD

**Issue by astocky** [SilentChaos512/Silent-Gear#439]
## Versions

- **Silent Gear**: 1.17.1-2.7.4
- **Silent's Gems**: N/A
- **Silent Lib**: 1.17.1-5.0.0
- **Forge**:  1.17.1-37.0.79
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
I try to put netherite into repair kits and it will not work, i expected the kit to fill with netherite. I also tried spawning an item with the give command:
/give @p silentgear:sturdy_repair_kit{Storage:{netherite: 8.0f}} and while that worked, it could not repair a diamond tool that I upgraded into a netherite tool with the smith station.

## Actual Behavior
Does not work as expected

## Links/Images
N/A

## Steps to Reproduce the Problem
As described above

**Comment by SilentChaos512** [comment]
Repairs are based on the durability of the material. Since netherite has no durability (only a multiplier) it cannot be used as a repair material.

I have considered making netherite a main material as well to prevent reports like this, but that would only cause other confusions.

**Comment by astocky** [comment]
Is that the same for Netherite armour? Or can't netherite armour be made in the smith station?

**Comment by SilentChaos512** [comment]
Should be the same for armor. You can still repair with any material that's compatible with the tool head, by the way.
