### ISSUE TITLE
Adornments Not working

### ISSUE THREAD

**Issue by stradar21** [SilentChaos512/Silent-Gear#442]
## Versions

- **Silent Gear silent-gear-1.17.1-2.7.3
- **Silent's Gems silents-gems-1.17.1-4.1.2
- **Silent Lib silent-lib-1.17.1-5.0.0
- **Forge 1.17.1 / 37.0.81
curios-forge-1.17.1-5.0.1.0.jar
- **Optifine Installed yes  preview_OptiFine_1.17.1_HD_U_H1_pre5

So I put the Jeweler Tools into the crafting station with diamonds or emeralds or bort and nothing shows up to make an adornment. Any reason for this?

**Comment by SilentChaos512** [comment]
Adornments now require one bort _in addition to_ the adornment material. The recipe should be visible in JEI. This was done to balance adornments somewhat.

**Comment by stradar21** [comment]
> Adornments now require one bort _in addition to_ the adornment material. The recipe should be visible in JEI. This was done to balance adornments somewhat.

Ok for some reason I only see example adornment Edit ok I figured it out sweet!!! thanks!
