### ISSUE TITLE
[1.16-1.17] please implement bulk adding materials to repair kit 

### ISSUE THREAD

**Issue by LuciusV** [SilentChaos512/Silent-Gear#449]
## What Should Be Added or Changed?

- Adding materials to repair kit is extremely annoying because I have to click 32 time to add 32 cobblestone - craft one by one

## Why Should This Be Done?

- Please add possibility to bulk add materials in one click

**Comment by SilentChaos512** [comment]
You can already add up to 8 materials at once.

**Comment by LuciusV** [comment]
Sorry I can't figure out how - crafting only allows me to add 1 cobblestone etc. Should I put 8x cobblestone and repair kit filling full 3x3 crafting grid in order to do as you mentioned?

**Comment by SilentChaos512** [comment]
Yes, you fill the crafting grid, one material per slot. Same concept as crafting with blueprints.
