### ISSUE TITLE
Infinite repairs strikes again

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silent-Gear#45]
I am starting to think this is a bug on my side, but you can still do it.
![image](https://user-images.githubusercontent.com/50839278/62415187-e45c4780-b5e2-11e9-8983-14ce84eb2369.png)
![image](https://user-images.githubusercontent.com/50839278/62415193-f6d68100-b5e2-11e9-9e75-406f2145d957.png)
![image](https://user-images.githubusercontent.com/50839278/62415266-11f5c080-b5e4-11e9-9d08-ecceb48fab82.png)

**Comment by SilentChaos512** [comment]
So now it affects the result.. I bet I know what I did wrong. I'll get that fixed in a bit.
