### ISSUE TITLE
[1.18-Forge] Can't load into worlds if Silent Gear + Elemental Craft are loaded together.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#450]
## Versions
- **Silent Gear**: 2.8.0
- **Silent Lib**: 6.0.0
- **ElementalCraft**: 4.0.1
- **DataPack Anvil (Lib)**: 3.0.0b
- **Forge** 38.0.14
- **Optifine Installed**: No

## Expected Behavior
That the world loads when Silent Gear & Elemental Craft are both loaded together.

## Actual Behavior
Worlds fail to load and give out the disconnect message: "Server sent an invalid packet".

## Logs/Images
Logs: https://gist.github.com/Gbergz/91049273d23d1b5f48d7c8cb53a03ed7

Image:
![image](https://user-images.githubusercontent.com/26634554/144833743-23281f28-934d-4bc9-9dae-fa8b37db6bd6.png)

## Steps to Reproduce the Problem
1. Install Silent Gear + Lib
2. Install ElementalCraft +DataPack Anvil (Lib)
3. Load Game.
4. Create world.
5. Fail, error.
6. Profit.

**-** Gbergz

**Comment by SilentChaos512** [comment]
Elemental Craft definitely has a material (air silk) that they need to update. But I'm not sure why that would cause the error. It should just load in and display a warning about the material.

**Comment by Sirttas** [comment]
> Elemental Craft definitely has a material (air silk) that they need to update. But I'm not sure why that would cause the error. It should just load in and display a warning about the material.

Air silk has been fixed, I'll take a look a ti once I get home, but it seems to be caused by EC alone.

**Comment by oliverrook** [comment]
I can confirm that deleting the silent gear materials folders from Elemental Craft fixes the issue, though obviously it gets rid of the cross compatibility.

**Comment by Sirttas** [comment]
> Air silk has been fixed, I'll take a look a it once I get home, but it seems to be caused by EC alone.

so it's not caused by EC only. I'll check if I can use datagen to generate my SG compatibility.
