### ISSUE TITLE
[1.18] tool durability not changing, repair kit has reverse durability.

### ISSUE THREAD

**Issue by drakosoldier298** [SilentChaos512/Silent-Gear#451]
## Versions
1.18

- **Silent Gear**: 2.8.0
- **Silent Lib**: 6.0.0
- **Forge**: 38.0.15
- **Optifine Installed**: No

## Expected Behavior
Durability to show properly on tools and repair kits.
## Actual Behavior
Repair kits as filled show reverse durability bar.
tools durability bar changes upon first use before and after repair then never chnage again till repaired.

## Steps to Reproduce the Problem

1.Load  previously mentioned versions 
2. use any pickaxe shovel or axe, (it probably does it with everythign these are just what ive been using)
3. watch as the durability doesnt change, and fill repair kits watch as they have reverse durability.

**Comment by Snaitf** [comment]
MC 1.18
Forge 38.0.15
Gear 2.8.0
Lib 6.0.0

~~Tool durability seems to work ok for me~~ (nvm, this isn't working for me anymore either), but I am in agreement that the repair kits 'fill' bar is backwards, as in, it gets smaller as you put more mats inside.

**Comment by Wilevar** [comment]
I can second these reports. Haven't yet confirmed that it's a persistent issue for all material levels or not, but wooden tools durability bars don't reduce with usage. Repair kits show full when crafted, but their bar reduces as you fill it/increases as it's used.
