### ISSUE TITLE
Gear Type: Trident 

### ISSUE THREAD

**Issue by CatAfterDark** [SilentChaos512/Silent-Gear#454]
## What Should Be Added or Changed?

- A gear type able to accept vanilla trident enchantments and fulfill a similar niche to the trident in vanilla gameplay.

## Why Should This Be Done?

- Silent gear currently has gear type counterparts to nearly every vanilla piece of equipment, and then some. The trident noticeably lacks an equivalent gear type.
- While the trident has fun, niche applications in vanilla, it's durability and damage make it lackluster compared to most options even in the base game. It's damage and durability become laughably poor in comparison to silent gear offerings.
- I want to use a cool red trident.

**Comment by ZOrangeBandit** [comment]
I would also like to see support for Tridents in Silent-Gear.
Trident's are my favorite weapon in Minecraft, and I would like for them to be viable as a useful weapon.

**Comment by SilentChaos512** [comment]
Added by 64c151b968f4592e817f1141dd5a42af3639c4d5. They need some work still I'm sure, but they function at least. The more minor issues can be worked out over time.

Would be awesome if someone pitched in to help with the rendering code lol
