### ISSUE TITLE
[1.18.1] Increase the spawn of Flax and Fluffy plants.

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#457]
## What Should Be Added or Changed?

I think that increasing the spawning chances of both Flax and Fluffy seeds would be beneficial for 1.18.1

## Why Should This Be Done?

Due to the 1.18 new terrain generation, the spawn of both Flax and Fluffy seeds is mostly gone, and almost nowhere to be found.

**Comment by SilentChaos512** [comment]
Doesn't seem to be an issue to me. I found several patches of each in just a couple minutes of flying around, same as before. Try increasing the `tryCount` and `patchCount` values for both wild plants in the config file.

**Comment by SilentChaos512** [comment]
Tested on the wrong branch, my bad. Something is definitely wrong.
