### ISSUE TITLE
[1.14.4] Crash on launch - NoClassDefFoundError

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [SilentChaos512/Silent-Gear#46]
## Versions

![image](https://user-images.githubusercontent.com/21359162/62482446-cac32780-b7bd-11e9-9483-9f208afd4ff4.png)

- **Forge**: 27.0.60

Other mods:
```
AmbientSounds_v3.0.9_mc1.14.3.jar
Apotheosis-1.14.3-2.0.5.jar
ChineseWorkshop-1.14.3-2.2.5.jar
dbag-1.14.3-5.5.jar
EnchantmentDescriptions-1.14.3-1.3.2.jar
FastLeafDecay-v16.jar
Hwyla-forge-1.10.4-B65_1.14.2.jar
ironchest-1.14.3-9.0.DEV.55a7af2.jar
jei-1.14.3-6.0.0.8.jar
Kiwi-1.14.3-2.2.5.jar
Morpheus-1.14.3-4.1.22.jar
Placebo-1.14.3-2.0.1.jar
randomenchants-2.0.0d.jar
reap-1.9.0.jar
ruins-1.14.3.jar
SBM-BoneTorch-1.14.3-0.0.1.jar
SilentGear-1.14.4-1.3.4+53.jar
SilentGems-1.14.3-3.2.2+52.jar
SilentLib-1.14.3-4.2.4+36.jar
simplecoloredblocks-1.1.2.jar.disabled
simplefarming-1.14.3-1.0.4.jar
SimpleStorageNetwork-1.14.3-0.0.7.jar.disabled
simplytea-2.0.1.jar
tramplestopper-1.14.4-2.0.0.16-universal.jar
useful_backpacks-1.14.3-1.7.0.33.jar
u_team_core-1.14.3-2.7.0.128.jar
XaerosWorldMap_1.4.4_Forge_1.14.3.jar
Xaeros_Minimap_1.17.4_Forge_1.14.3.jar
XL-Food-Mod-1.14.3-2.0.1.jar
```

## Expected Behavior
Load packs as normal

## Actual Behavior
Game crashes with error
![minecraft_wmDmqLa8j5](https://user-images.githubusercontent.com/21359162/62482173-27721280-b7bd-11e9-8127-87c15f79f5df.png)

Crash log:
https://pastebin.com/vqDgBw6v

Works fine with Silent Gear disabled. Reproduced on 2 machines.

## Steps to Reproduce the Problem

Load game with packs

For convenience: mod pack exported profile (Twitch/Curse import profile to get mods installed):
[neworld-1.0.0.zip](https://github.com/SilentChaos512/Silent-Gear/files/3468650/neworld-1.0.0.zip)

**Comment by EdvardasDlugauskas** [comment]
Thank you for your hard work, hope this report helps

**Comment by SilentChaos512** [comment]
Looks like you're playing on 1.14.3? I thought the mod would be compatible with that version as well, but maybe not. I would suggest downgrading Silent Gear to 1.2.4 until you are able to update.
