### ISSUE TITLE
complimentary shaders incompatability 1.18.1

### ISSUE THREAD

**Issue by caligator** [SilentChaos512/Silent-Gear#460]
apparently with shaders on, none of the items in this mod show up

![image](https://user-images.githubusercontent.com/7035954/146241298-22dff98a-ae8f-438c-a6cf-66e1b70d9419.png)

**Comment by SilentChaos512** [comment]
Nothing I can do if the issue is caused by another mod, sorry.

**Comment by oliverrook** [comment]
This appears to happen with all optifine shaders
