### ISSUE TITLE
Weird issue. When Silent Gear is present on a dedicated server, boot process gets frozen like 95% of the time.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#466]
## Info
So, yes this is a weird issue. But I've sat down and removed every single mod one by one till' I found out which solved this specific odd problem.

For some reason the server doesn't boot, it gets frozen during the startup process. 
It just stays there until the process is forcefully ended.

I've tested this a lot, like a lot. 
And it came down to that it's caused by **Silent Gear** somehow...? Not sure onto why. 
Removing Silent Gear (+ the addons) is the only mods that allows server to boot 100% of the time.

There's a chance that the server starts up normally but that is just chance, not all the time. 
It's either 1 in 5 or 1 in 10 chances that it boots up successfully.

No errors in console / logs that shows why the process stops completely, or anything. But they're linked below anyways.

This issues started happening and was found when Silent Gear was added to the modpack.

## Versions
- **Silent Gear**: 2.8.1
- **Silent's Gems**: 4.2.1
- **Silent Lib**: 6.0.0
- **Minecraft**: 1.18.1
- **Forge**: 39.0.5
- **Modpack**: [TNP Limitless 5](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5)
- **Optifine Installed**: No

## Expected Behavior
That the server boots up like normal and doesn't freeze during the startup process.

## Actual Behavior
Server gets frosen during the startup process and never continues. Completely frozen.

## Links, logs: (I've removed all mods mentioned at the bottom like KubeJS & Connectivity, removing Silent Gear is the only way to let it boot 100% of the time.)
- [(latest.log)](https://gist.github.com/Gbergz/c390361ce8e0b4d4337ae099d27c48a0)

## Steps to Reproduce the Problem ( I used BisectHosting for this problem. )
1. Install Silent Gear, Gems & Lib
2. Be on Forge 39.0.5
3. Start server.
4. booting..
5. Gets stuck.
6. profit.

Alternatively:
1. Install TNP Limitless 5 (v0.6.0) on a BisectHosting server.
2. Let it install.
3. Start server
4. Gets stuck on startup process like almost every time.

Hopefully this can be solved.
**-** Gbergz

**Comment by Gbergz** [comment]
Accidentally closed.
After some time I was reminded by a similar issue.
https://github.com/SilentChaos512/Silent-Gear/issues/438

**Comment by drakosoldier298** [comment]
id like to mention this happens on self host as well.
ive had this issue since adding silent gems, it seems to be a mix of silent gems and gear but only hangs when it mentions adding silent gems stuff.

**Comment by Gbergz** [comment]
A workaround "fix" for now is to set maxThreads from -1 to 1 in fml config.

Like mentioned in the linked issue above.

**Comment by Gbergz** [comment]
So. 
This seems to still be an issue even on client now in 1.18.2. 

Setting maxThreads to 1-4 solves it. -1 hangs it for some reason.
