### ISSUE TITLE
Silent Gear axes don't disable shields for a short while

### ISSUE THREAD

**Issue by blahblahbal** [SilentChaos512/Silent-Gear#467]
## Versions

- **Silent Gear**: 2.8.0
- **Silent's Gems**: N/A
- **Silent Lib**: 6.0.0
- **Forge**: 38.0.17
- **Modpack**: N/A
- **Optifine Installed**: No
- Mods installed: Amplified Nether 1.0.1, Chunkloaders 1.1.7b, Create v0.4a, Curios 5.0.2.5, Easy Villagers 1.0.3, JEI 9.0.0.40, Quark 3.0-333, Quark Oddities, Sophisticated Backpacks 3.12.1.433, Supplementaries 1.0.7, Xaero's Minimap 21.22.5 (and all of the above mods' dependencies)

## Expected Behavior

The axes disable shields for a short while.

## Actual Behavior
When attacking with a Silent Gear axe on a player holding up their shield, the shield is not disabled.

## Links/Images

If necessary I can upload a gif, but it's pretty easy to test.

## Steps to Reproduce the Problem

1. Craft a Silent Gear axe and a shield of any type (it doesn't matter if SG or vanilla).
2. Give your shield to someone on a server and have them hold it up.
3. Attack them from the front with your SG axe, noticing that it doesn't disable the shield.

**Comment by SilentChaos512** [comment]
Seems to be caused by the fact that gear axes no longer extend the vanilla `AxeItem` class... I guess that change had some unintended side effects.
