### ISSUE TITLE
Buggy durability bar for hammers

### ISSUE THREAD

**Issue by EvergreenSystems** [SilentChaos512/Silent-Gear#468]
## Versions

- **Silent Gear**: 2.8.0
- **Silent's Gems**: n/a
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.5
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Durability bar for hammers to function normally, with nothing in the bar equating to very low dura and full bar equating to high dura

## Actual Behavior

The durability bar empties really early; the bar appears to be at 0 dura graphically, but in reality the tool still has about 1/3 of its dura left.

This has been seen with a hammer with a diamond head and iron handle

## Links/Images

![2021-12-26_13 52 46](https://user-images.githubusercontent.com/23658767/147418716-5a60f462-a3a9-4985-bf85-ef0084990d97.png)
![2021-12-26_13 56 32](https://user-images.githubusercontent.com/23658767/147418761-75ffe05f-052f-45da-beb0-f5532c36eb74.png)

- (Link)

## Steps to Reproduce the Problem

1. Craft a hammer w/ a diamond head and iron handle
2. Use as intended for mining
3. Check dura when the bar depletes to dura; the number does not match the bar (bar is incorrect, number is correct)

**Comment by EvergreenSystems** [comment]
![2021-12-26_14 15 48](https://user-images.githubusercontent.com/23658767/147419112-4dc141b3-f2a6-442b-8497-a6e452dc6657.png)

My apologies, its more like 1/2 of dura instead of 1/3

**Comment by SilentChaos512** [comment]
Durability bar issues should already be fixed in 2.8.1. Update to the latest version and reopen the issue if the bug still exists.
