### ISSUE TITLE
Amethyst items naming text issue

### ISSUE THREAD

**Issue by MCKyralina** [SilentChaos512/Silent-Gear#469]
## Versions

- **Silent Gear**: 1.18.1-2.8.2
- **Silent's Gems**: N/A
- **Silent Lib**: 1.18-6.0.0
- **Forge**: 1.18.1 - 39.0.8
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Items crafted with amethyst to display as "Amethyst (item)"

## Actual Behavior
The items display as "material.silentgear.amethyst (item)"

The amethyst items appear to be using the base item identifier and not an actual display name.

## Links/Images
![2021-12-26_20 54 59](https://user-images.githubusercontent.com/83620601/147419951-8d7d6f81-a49f-4e25-b323-ebeb3be73199.png)

## Steps to Reproduce the Problem
Make any item out of amethyst and then view the item's info pane popup.

**Comment by SilentChaos512** [comment]
The lang key is probably missing in 1.17 as well.
