### ISSUE TITLE
Fluffy puff World Generation

### ISSUE THREAD

**Issue by OmniAdachi** [SilentChaos512/Silent-Gear#473]
Fluffy puff seems to have some issues in 1.18.1, as no matter what values i set the world generation of them to be (both high and low) they just dont spawn anywhere, ive found flax, bort and the other ores just fine, but for some reason fluffy puff just doesnt exist

**Comment by SilentChaos512** [comment]
I'm not seeing any issues. Try searching in forest- and swamp-like biomes.

**Comment by SilentChaos512** [comment]
Tested on the wrong branch, my mistake. But this is a duplicate of #457.
