### ISSUE TITLE
[1.18.1] Hook Returns Immediately After Fishing Rod Being Casted

### ISSUE THREAD

**Issue by ravesdie** [SilentChaos512/Silent-Gear#476]
## Versions
<Minecraft 1.18.1 -->

- **Silent Gear**: 2.8.2
- **Silent's Gems**: 4.2.0
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.9
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Fishing rod to be casted, floater floats, get fish/items.

## Actual Behavior
When casting fishing rod, instead of being able to cast it just fine and be able to fish, the hook/floater, which you can see being casted, returns immediately to you. It does not even touch the water.

## Steps to Reproduce the Problem

1. Create a Fishing Rod from the mod
2. Cast your made fishing rod.

**Comment by V2LenKagamine** [comment]
can confirm this issue

**Comment by SilentChaos512** [comment]
Duplicate of #425
