### ISSUE TITLE
Starlight Charger problem in 1.16.5

### ISSUE THREAD

**Issue by FelipePachec0** [SilentChaos512/Silent-Gear#478]
The recipe for the starlight charger dont work, and it don’t is on the creative menu or in JEI

**Comment by SilentChaos512** [comment]
Follow the issue template next time. I need to know what versions you are using. Include the version of Forge, Silent Gear, and Silent Lib.

**Comment by FelipePachec0** [comment]
Sorry i didnt know there was a template
Forge 1.16.5-forge-36.2.0
Silent Gear 1.16.5-2.6.30
Silent Lib 1.16.3-4.9.6

**Comment by FelipePachec0** [comment]
Ok i tried with a newer version and it worked sorry for the incovenience
