### ISSUE TITLE
Placing netherwood sapling crashes game (1.18.1)

### ISSUE THREAD

**Issue by Konin-Sensei** [SilentChaos512/Silent-Gear#482]
## Versions

- **Silent Gear**: 2.8.4
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.36 (used to say 39.0.6. That was a typo on 36. my bad)
- **Optifine Installed**: No 

## Other Mods (Not a public modpack. Built using the curseforge launcher)
- **AE2**: 10.0.0-beta.4
- **Advanced Netherite**: 1.10.0
- **AppleSkin**: 2.2.0
- **Balm**: 2.4.1+0
- **Carry On**: 1.17.0.7
- **Cooking for Blockheads**: 11.1.0
- **Fast Leaf Decay**: 27.2
- **JEI**: 9.2.1.69
- **Mouse Tweaks**: 2.21
- **Sophisticated Backpacks**: 3.15.1.505
- **Waystones**: 9.0.3

## Expected Behavior
I expect to place a Netherwood sapling on dirt or grass in the overworld

## Actual Behavior
The game crashes immediately upon right-clicking the ground with the sapling in hand.

## Links/Images
[Crash Log](https://pastebin.com/zBpHFq8S)

## Steps to Reproduce the Problem

1. In Singleplayer and/or multiplayer, attempt to place a Netherwood sapling in the overworld

## Edit:
- I tried to replicate this in the same forge version with no other mods and it still happens.
- I also tried the latest forge version at the time of writing, which was 39.0.44
- fixed a typo in this post on the forge version listed at the top

**Comment by ffuentesm** [comment]
I got the same issue, IllegalStateException: Tag silentgear:netherwood_soil used before it was bound
Log: https://crashy.net/12Ti2zYXvvUMNKJEoOe9

Now I can't play in my world due to using the sapling in a create tree farm.

**Comment by SilentChaos512** [comment]
I think I know a solution for this. I can't test it however, because this doesn't crash for me.
