### ISSUE TITLE
[1.18.1] Amethyst cluster only drops 2 shards when broken with pickaxe or paxel

### ISSUE THREAD

**Issue by insanepinky** [SilentChaos512/Silent-Gear#484]
## Versions

- **Silent Gear**: 2.8.5
- **Silent's Gems**: N/A 
- **Silent Lib**: 6.0.0
- **Forge**: 39.0.19
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

When broken with an unenchanted pickaxe, amethyst clusters are supposed to drop 4 shards instead of the 2 they drop when broken with any other tool.

## Actual Behavior

When using an unenchanted Silent Gear pickaxe or paxel the amethyst cluster only drops 2 shards. Enchanting the pickaxe/paxel with Fortune 3 also still only makes it drop 2 shards. A regular unenchanted, vanilla iron pickaxe drops the correct amount of 4.

## Steps to Reproduce the Problem

1. Break an Amethyst Cluster with a Silent Gear pickaxe or paxel.

**Comment by SilentChaos512** [comment]
~Seems that the Imperial trait also doesn't work with amethyst clusters. I would consider that a related bug.~ Wait, it's totally broken for other ores too in 1.18.2...
