### ISSUE TITLE
(1.16.5) java.lang.NullPointerException: Failed to recalculate gear properties

### ISSUE THREAD

**Issue by samuraijkid** [SilentChaos512/Silent-Gear#486]
## Versions

- **Silent Gear**: 2.6.36
- **Silent's Gems**: N/A
- **Silent Lib**: 4.10.0
- **Forge**: 36.2.20
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior

I'd usually expect the game to load slower while launching my world. Instead it loaded to 100% after a few short seconds. Many of my worlds wouldn't do that.

## Actual Behavior

After quickly loading to 100% the game saves my world, and crashes and brings me back to the Minecraft Launcher.

## Links/Images

- https://pastebin.com/ZHyhMnW1 (Crash Log)
- https://www.youtube.com/watch?v=l--0OcE_Uxw (Video of what happens)

## Steps to Reproduce the Problem

1. Started a world In Creative.
2. Used the mod Minecolonies to start civilization. (Didn't give modded tools to workers.)
3. Had shaders enabled. (First crash was because shaders was enabled. After turning it off in the settings the crash switched to silentgear being the issue.)

**Comment by EnotScript** [comment]
> ## Versions
> * **Silent Gear**: 2.6.36
> * **Silent's Gems**: N/A
> * **Silent Lib**: 4.10.0
> * **Forge**: 36.2.20
> * **Modpack**: N/A
> * **Optifine Installed**: Yes
> 
> ## Expected Behavior
> I'd usually expect the game to load slower while launching my world. Instead it loaded to 100% after a few short seconds. Many of my worlds wouldn't do that.
> 
> ## Actual Behavior
> After quickly loading to 100% the game saves my world, and crashes and brings me back to the Minecraft Launcher.
> 
> ## Links/Images
> * https://pastebin.com/ZHyhMnW1 (Crash Log)
> * https://www.youtube.com/watch?v=l--0OcE_Uxw (Video of what happens)
> 
> ## Steps to Reproduce the Problem
> 1. Started a world In Creative.
> 2. Used the mod Minecolonies to start civilization. (Didn't give modded tools to workers.)
> 3. Had shaders enabled. (First crash was because shaders was enabled. After turning it off in the settings the crash switched to silentgear being the issue.)

 you fix that?
