### ISSUE TITLE
Error loading mod with 28.0.45

### ISSUE THREAD

**Issue by Sunekaer** [SilentChaos512/Silent-Gear#49]
## Versions

- **Silent Gear**: SilentGear-1.14.4-1.3.4+53.jar
- **Silent's Gems**: SilentGems-1.14.4-3.3.1+56.jar
- **Silent Lib**: SilentLib-1.14.4-4.3.0+38.jar
- **Forge**: 28.0.45
- **Modpack**: N/A

![image](https://user-images.githubusercontent.com/18720460/62561690-f9a1d200-b87f-11e9-8175-29b714f564d2.png)

**Comment by Sunekaer** [comment]
https://paste.dimdev.org/otixexalab.md

**Comment by SilentChaos512** [comment]
Fixed in latest version by f4366bc3799de0079aa1f71d2080ecbfd0191ce4 and 81e43f377e6507dadceab45e1229e43e0869a921.
