### ISSUE TITLE
Saw crashes server when it breaks

### ISSUE THREAD

**Issue by HuntorWorks** [SilentChaos512/Silent-Gear#493]
versions: 
Mineraft 1.16.5
Silent Gear 2.6.30

Additional silent gems 3.7.16

Whenever the saw reaches zero durability, the icon shows it has some durability remaining, and it crashes the server. 

Steps to reproduce: 
grow a tree,
cut down tree
break server (with saw breaking during process)

**Comment by SilentChaos512** [comment]
Please provide a crash report or the issue will be closed.
