### ISSUE TITLE
1.18.2 fails to load correctly

### ISSUE THREAD

**Issue by krjencik** [SilentChaos512/Silent-Gear#497]
## Versions

- **Silent Gear**: 2.9.1
- **Silent's Gems**: x.x.x 
- **Silent Lib**: 6.1.0
- **Forge**: 40.0.17
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

load and work - no crashes
(Description here)

## Actual Behavior

silent gear failed to load correctly 
java.lang.reflect.InvocationTargetException: null
(Description here)

## Links/Images

https://gist.github.com/krjencik/3a803e303f71e88837ee9ff638aa31ce#file-silentsgemscrash
- (Link)

## Steps to Reproduce the Problem

1.click the play button in Minecraft launcher
2.
3.

**Comment by SilentChaos512** [comment]
Crash confirmed with nothing but Gear and Lib installed. I guess Mojang decided to rename a class in a minor update for some reason.
