### ISSUE TITLE
Stone Rod Recipe Conflicts with Inspirations Mod same item - Compatibility possibility?

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#5]
### Versions

Minecraft Version: 1.12.2
Silent Gear Version: 0.1.1-38
Silent Lib Version: 3.0.1-145

### Expected behavior

-Stone rods for your tools may need a different recipe to prevent conflicts - perhaps an easy fix would be to require a stick with the other materials? Or maybe an easy template/blueprint for the rods as well?

### Actual behaviour

- Inspirations stone rod overtakes your rod recipe, preventing the crafting of your stone tool rods.

### Steps to reproduce the problem

1. Install your mod
2. Install Inspirations
3. Try to craft stone rods for tools
4. You get Inspirations stone rods

**Comment by SilentChaos512** [comment]
Seems the Inspiration stone rods use rodStone for their ore dictionary key, and I'm using stickStone. Not sure which of the two is more common. But having a tool rod blueprint as a backup is a good idea.
