### ISSUE TITLE
Able to dupe gear in multiplayer

### ISSUE THREAD

**Issue by darkphan** [SilentChaos512/Silent-Gear#50]
## Versions

- **Silent Gear**: 1.14.4-1.3.5+54
- **Silent Lib**: 1.14.4-4.3.1+39
- **Forge**: 28.0.45

## Expected Behavior

When modifying gear in the Crafting Station it should not show the gear in the output slot after the gear was modified by another player.

## Actual Behavior

When 1 player enters the Crafting Station and puts in a recipe to modify a tool, another player can then enter the Crafting Station and wait for the first person to then remove the gear, the item will still be in the output slot and the 2nd player can then remove the gear to duplicate it.

## Steps to Reproduce the Problem

1. Player 1 enters the Crafting Station and puts in a recipe to modify gear but does not remove the result.
2. Player 2 then enters the Crafting Station.
3. Player 1 removes modified gear.
4. Player 2 can then remove the modified gear that still shows up, duplicating Player 1's gear.

**Comment by Soschian** [comment]
This is actually possible with all crafting recipies in 1.14.4-1.3.10+59, just had it happen with my friend

**Comment by MasterEnderman** [comment]
This also happens in the 1.12.2 Version of the Mod.

**Comment by Danekjovax** [comment]
If Crafting Station is removed in 1.16, then this bug may be fixed, by proxy.
