### ISSUE TITLE
[1.18.2] Mod Ingots not being accepted as materials 

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#503]
## Versions

- **Silent Gear**: silent-gear-1.18.2-2.10.0.jar
- **Silent's Gems**: x.x.x 
- **Silent Lib**: silent-lib-1.18.2-6.2.0.jar
- **Forge**: 40.0.52
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

SG should identify Immersive engineering, Botania, Create metals as tool materials, such as aluminum, uranium, steel, etc

## Actual Behavior

SG is not identifying mod metals as usable materials

## Links/Images

![image](https://user-images.githubusercontent.com/44974827/163530215-301eb5df-f03e-4f21-a875-50ff0536e391.png)
![image](https://user-images.githubusercontent.com/44974827/163530225-f93925b8-9347-4916-bb2e-e6015248610e.png)
![image](https://user-images.githubusercontent.com/44974827/163530231-3fb9f612-f232-46b8-b50b-78d4cb5fd45c.png)
![image](https://user-images.githubusercontent.com/44974827/163530237-e43ab652-b839-4270-9664-bfc1c35ee930.png)
![image](https://user-images.githubusercontent.com/44974827/163530535-cc52fe26-d8e0-437d-ad5d-1c38d8c7e7f9.png)
![image](https://user-images.githubusercontent.com/44974827/163530570-6c7164ea-4488-4372-954c-c1cb41e66ed1.png)
![image](https://user-images.githubusercontent.com/44974827/163530577-53772796-b25f-4235-98b8-ba3762fe5c68.png)

## Steps to Reproduce the Problem

1. Instal SG and other mods with metals
2. Check if metals are being identified as usable materials

**Comment by SilentChaos512** [comment]
Fixed in version 2.10.1. Materials will load now, but materials with no corresponding items will still show an "empty tag" in recipes. That's a minor issue, so I'll fix it some other time.
