### ISSUE TITLE
[1.18.2] Magmatic trait not working

### ISSUE THREAD

**Issue by Snaitf** [SilentChaos512/Silent-Gear#504]
## Versions

- **Silent Gear**: 2.10.0
- **Silent's Gems**: N/A 
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Tool with Magmatic trait from a Crimson Steel tip should smelt as it mines.

## Actual Behavior

Magmatic trait is not smelting.
Tested with nothing but Gear and Lib installed.

## Links/Images

- N/A

## Steps to Reproduce the Problem

1. Make tool
2. Make crimson steel tip
3. Apply tip to tool
4. Mine smeltables with tool

**Comment by SilentChaos512** [comment]
Confirmed. Not sure what changed, but it's probably a 1.18.2-specific issue. Either Minecraft or Forge changed something. I'll have to debug it later.
