### ISSUE TITLE
Missing translations keys

### ISSUE THREAD

**Issue by LunarFactory** [SilentChaos512/Silent-Gear#508]
## Versions

versions are not important of this issues, so I didn't check it.

## Links/Images

![2022-05-01_10 59 45](https://user-images.githubusercontent.com/69113888/166130818-21fc7a47-aa78-4cdf-89b5-5e474390d93c.png)
![2022-05-01_11 00 46](https://user-images.githubusercontent.com/69113888/166130819-acfa9080-5af0-45a7-8e91-c8c1567abddd.png)
![2022-05-01_11 01 47](https://user-images.githubusercontent.com/69113888/166130821-2b5daa58-8310-4044-ae80-1c266bd80058.png)
![2022-05-01_11 03 08](https://user-images.githubusercontent.com/69113888/166130822-99245a00-f7bf-453b-b4b0-76685af427fb.png)
![2022-05-01_11 04 53](https://user-images.githubusercontent.com/69113888/166130824-08b508c1-3a99-4e03-9a74-07c90f3a932b.png)
![2022-05-01_11 07 11](https://user-images.githubusercontent.com/69113888/166130825-5fdcfb07-1416-44cc-9d3c-c589a6932ae1.png)
![2022-05-01_11 07 30](https://user-images.githubusercontent.com/69113888/166130826-e6d06c06-a5ec-4144-b515-6829780bb364.png)
![2022-05-01_11 11 13](https://user-images.githubusercontent.com/69113888/166130828-b8aaad4d-cb0f-4024-b523-59db952092a3.png)
![2022-05-01_11 37 36](https://user-images.githubusercontent.com/69113888/166130829-9c12c6bd-e214-4cfd-8afd-c547bd1e8781.png)

Those sentences should have translation keys.

**Comment by SilentChaos512** [comment]
Thanks for the report. Looks like the affected bits of text are: material categories, part types, gear types, and some debug lines for materials. There's definitely a case for adding the translations.

**Comment by LunarFactory** [comment]
Oh, and refined glowstone in creative / guidebook text are same too.

**Comment by SilentChaos512** [comment]
I believe I have added translation keys for everything. I am uploading version 2.10.4 right now. Let me know if I missed anything.
