### ISSUE TITLE
Running a search in Cloud Storage with SGear's blueprints in the network crashes a server.

### ISSUE THREAD

**Issue by Kitsumei** [SilentChaos512/Silent-Gear#512]
## Versions

- **Silent Gear**: 2.10.1
- **Silent's Gems**: 4.3.1 
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Simply searching for an item in a container shouldn't cause a crash.

## Actual Behavior

When on a server, attempting to use cloud storage's search function causes the entire server to crash, forcing a restart. This only occurs when Silent Gear's blueprints are in a cloud network, and only on multiplayer. 

## Links/Images

This likely isn't a problem on Silent Gear's end, but it seems to be relevant to the problem, so I'm posting here just incase SG is what's throwing the error.

https://pastebin.com/TA7W98LS

- (Link)

## Steps to Reproduce the Problem

1. Create a server for 1.18.2 with Silent gear, Gems, lib, and Cloud storage installed
2. Join server, place any blueprint item into a cloud chest
3.attempt to use the search function, and crash.

**Comment by SilentChaos512** [comment]
~Was this reported to Cloud Storage as well? Please link the issue if so.~ Found it, https://github.com/Alex-the-666/CloudStorage/issues/18.

I glanced at the code that is crashing, but I'm not sure off the top of my head if this is a bug with Silent Gear or Cloud Storage. The code in question is related to building the item tooltip, which is something that works fine normally.

**Comment by Kitsumei** [comment]
just doing a little cross-post here. After a little screwing around, this seems to occur after using the sort button and then attempting the search in the cloud network gui.

**Comment by SilentChaos512** [comment]
Seems to have been fixed by Cloud Storage.
