### ISSUE TITLE
Please allow access to your mods for third party lanuchers.

### ISSUE THREAD

**Issue by blackd** [SilentChaos512/Silent-Gear#514]
## What Should Be Added or Changed?

With the new curseforge REST API rollout your mods are currently only accessible using the curseforge site and the curseforge app.

Could you please allow access for launchers like ATLauncher.

For more info https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

## Why Should This Be Done?

Not all people use WIndows which makes impossible to use CurseForge on Linux so third party launchers are our only way to play

**Comment by derrickmehaffy** [comment]
I second this, please enable 3rd party access for those of us on Linux who can't use the CF launcher

**Comment by SilentChaos512** [comment]
I decided to allow this. While I'm not happy about my mods being distributed outside Curseforge, I know that people will find away around it regardless. Just remember that I earn nothing for my hard work when you download outside of Curse.

**Comment by derrickmehaffy** [comment]
> I decided to allow this. While I'm not happy about my mods being distributed outside Curseforge, I know that people will find away around it regardless. Just remember that I earn nothing for my hard work when you download outside of Curse.

Thank you for supporting us linux users, I know it may not help you much for now but until CF offer a linux launcher there isn't much we can do other than to support you on patreon. <3
