### ISSUE TITLE
Refractive trait not placing phantom lights when used on certain tools

### ISSUE THREAD

**Issue by EntropicPariah** [SilentChaos512/Silent-Gear#515]
## Versions

- **Silent Gear**: 1.18.2-2.10.6
- **Silent's Gems**: 1.18.2-4.3.1
- **Silent Lib**: 1.18.2-6.2.0
- **Forge**: 40.1.16
- **Modpack**: None
- **Optifine Installed**: Yes

## Expected Behavior

When you have the Refractive trait on Hammers and Picks etc... right clicking should place a phantom light.

## Actual Behavior

So far I've only tested this with hammers, picks and shovels but neither the pick nor hammer places phantom lights regardless of how the Refractive trait was added. A shovel, however, with the Refractive trait from an end rod tool handle places phantom lights correctly. Shield in the offhand doesn't matter and neither does the surface on which you right click

## Steps to Reproduce the Problem

Try placing phantom lights with any tool possessing the Refractive trait. Like I said, so far only shovels work and i haven't tested more than picks, hammers and shovels.

**Comment by arshiahf** [comment]
Doesn't work with paxels either
