### ISSUE TITLE
Crash when recipes shown in jei (magnesium installed)

### ISSUE THREAD

**Issue by Ondras4620** [SilentChaos512/Silent-Gear#517]
## Versions

- **Silent Gear**: 2.6.30
- **Silent's Gems**: N/A 
- **Silent Lib**: 4.9.6
- **Forge**: 36.2.34
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

(Description here)

I have installed Magnesium, magnesium dynamic lights & magnesium extras and several more performance mods, without magnesium my game isnt running very smooth

## Links/Images

- (Link)
- crash > https://gist.github.com/Ondras4620/2f61028fceb9d69f1e26c364a9111018
- log > https://gist.github.com/Ondras4620/89cac0f17f61809bdd0737817c75b679

## Steps to Reproduce the Problem

1.run game
2.start world
3.scroll in jei until silent gear(you might have to put mouse over silent gear items)

**Comment by SilentChaos512** [comment]
If the crash only occurs with mods that change rendering installed, there is probably nothing I can do to fix it.
