### ISSUE TITLE
Paxels and Spoon-upgraded Pickaxes are Ineffective Shoveling

### ISSUE THREAD

**Issue by Subi-alt** [SilentChaos512/Silent-Gear#518]
## Versions
 

- **Silent Gear**: 2.10.7
- **Silent's Gems**: 4.3.1
- **Silent Lib**:  6.2.0
- **Forge**: Forge - 40.1.48
- **Modpack**:  TNP Limitless 5
- **Optifine Installed**: Yes
 
## Expected Behavior

Paxels and spoon-upgraded pickaxes should be able to break dirt/etc as fast as shovels. Paxels are also ineffective on wooden items above wood tool hardness.

## Actual Behavior

Dirt and wooden items are broken as fast as fisting.

## Links/Images

![2022-06-13_16 56 20](https://user-images.githubusercontent.com/79768153/173452017-75855737-b732-44fa-a75d-8106e46a5ae4.png)
![2022-06-13_16 56 24](https://user-images.githubusercontent.com/79768153/173452054-0ba3fe93-673c-484e-b507-a13876225262.png)

## Steps to Reproduce the Problem

1. Get a paxel.
2. Try to break dirt/sand/gravel/wood above wood tool hardness.
3. See that it is no better than using your fist.

**Comment by Namoku** [comment]
This happens too with a pickaxe in 1.18.2-2.10.7

**Comment by bcrotty** [comment]
Not sure if this is related, but the axe behavior of the paxel is spotty too. For example, it counts as an axe with vanilla logs, but not a melon from vanilla. This happens several other places like logs from other mods.

Silent Gear 1.18.2-2.10.7 on ATM7 0.4.15
