### ISSUE TITLE
Silent Gear Stops jei from working on server

### ISSUE THREAD

**Issue by IchigoGames** [SilentChaos512/Silent-Gear#52]
- **Silent Gear**:SilentGear-1.14.4-1.3.8+56
- **Silent's Gems**:SilentGems-1.14.4-3.3.8+65
- **Silent Lib**:SilentLib-1.14.4-4.3.1+39
- **Forge**:28,0,49
- **Modpack**:The Aquatic Frontier

## Expected Behavior
jei to work in multiplayer

- (Description)

## Actual Behavior
jei does not work in multiplayer with this mod Silent-Gear added it will work in multiplayer or if you connect to the server twice but it will not load on first try reported it to jei but this does not happen without this mod added.

## Steps to Reproduce the Problem

1. add jei-1.14.4-6.0.0.10
2. add SilentGear-1.14.4-1.3.8+56 and all needed mods for it.
3.try to connect to a server desktop hosted or hosted server ether one DO NOT go into singeplayer first it happens when you go into multiplayer first.

**Comment by SilentChaos512** [comment]
OK, I think I see what's going wrong. JEI is trying to validate recipes before gear parts are loaded, so the recipe throws an error... Not sure of the best way to fix this, but I'll work on it.
