### ISSUE TITLE
Arrow amount to easy to abuse

### ISSUE THREAD

**Issue by TarenGameDev** [SilentChaos512/Silent-Gear#520]
An option to tweak ammo amount or durability. Currently its very cheap to get infinite arrows (4 iron for x200+ shots) 

Discord msg:
#silent-gear  is there an option to nerf arrow amount/durability?? 

I'm tweaking my mod pack so only SG gear is craftable (no vanilla tools, armour or arrows for example), and using the arrow blueprint its not very expensive to get essentially infinite arrows (1 iron to craft = x64 shots. 3 iron in repair kit =200+ shots)

**Comment by SilentChaos512** [comment]
There are two parts to this problem:

1. The starting amount for a new stack of arrows is always 64 (hardcoded in `construct`)
2. The amount restored by repair kits is controlled by `getRepairModifier` and is based on the hidden durability stat of the arrows

I need to choose an appropriate way to control both of these values. Actually, it might already be possible to control the repairs by tweaking the repair efficiency for arrow heads with a data pack. I'll need to test that.
