### ISSUE TITLE
Armor durability calculation is unclear / unintuitive

### ISSUE THREAD

**Issue by eSonOfAnder** [SilentChaos512/Silent-Gear#521]
## Versions
- **Silent Gear**: 1.18.2-2.10.7
- **Silent's Gems**: N/A
- **Silent Lib**: 1.18.2-6.2.0
- **Forge**: 40.1.31
- **Modpack**: All The Mods 7
- **Optifine Installed**: No

## Expected Behavior
Armor crafted from materials that report a higher durability create armor pieces with a higher durability.

## Actual Behavior
Durability for armor appears to be calculated from some unlisted / unknown base value that has nothing to do with the material. The reported Durability stat only applies to tools and weapons, and it is only the Armor Durability multiplier that has any impact here.

Examples:
Invar reports a Durability of 640, with an Armor Durability multiplier of 20x (20 times what? It is never shown or documented anywhere.)

Lumium reports a Durability of 920 with an Armor Durability multiplier of 20x.

Both materials produce a Chestplate with a durability of 360. On initial inspection, this appears to be the multiplier times the total armor value of the armor set, but then that only applies to the chestplate, and there is no way of figuring out what the armor value for the other pieces are going to be.

There has to be some better way of showing this information to the user, or at the very least have an explanation of how this works in the wiki. As is, it is extremely difficult to try and figure out a good material to make armor out of without simply wasting materials to make the pieces and see what comes out the other side.

## Steps to Reproduce the Problem

1. Make a piece of armor
2. See stats cannot be calculated based on reported tooltip information.

**Comment by SilentChaos512** [comment]
Armor durability is described on the wiki here: https://github.com/SilentChaos512/Silent-Gear/wiki/Stats

It's pretty much the same way vanilla handles armor durability. You just don't see the values in the base game.

**Comment by eSonOfAnder** [comment]
Thank you for pointing out the specific section; that was pretty easy to miss on a casual read through of the pages. Minor suggestion, update the tooltip verbiage to callout specifically Tool Durability vs. Armor Durability, and maybe add a tooltip to the armor blueprints that includes the base armor values, since the multiplier has no frame of reference within the game.
