### ISSUE TITLE
Game Crashes when attempting to parse unknown sound in datapack

### ISSUE THREAD

**Issue by Auseawesome** [SilentChaos512/Silent-Gear#523]
## Versions
Only attempted on minecraft 1.18.2 (Silent Gear 2.10.10)

- **Silent Gear**: 2.10.10
- **Silent's Gems**: 4.3.1
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.54
- **Optifine Installed**: No

## Expected Behavior

Error in parsing the json file and it prints to log

## Actual Behavior

Game kicks you from singleplayer world with error message 'Invalid Packets Recieved' and you end up on multiplayer screen

## Steps to Reproduce the Problem

1. Make a custom datapack for Silent Gear
2. Make a custom block placer trait
3. Add the place sound as an invalid sound eg. "minecraft.block.ice.place"
4. Put the datapack in the world folder and load the world

**Comment by SilentChaos512** [comment]
Provide a crash report or log file please

**Comment by Auseawesome** [comment]
[2022-07-08-3.log](https://github.com/SilentChaos512/Silent-Gear/files/9075949/2022-07-08-3.log)
At the bottom of the log file is where the error is. That is just due to the sound being invalid in my file. I can send the whole datapack with the error in if required and I do have access to the modpack it was used in if that is also needed
