### ISSUE TITLE
I can't craft any tool in Nitrado server

### ISSUE THREAD

**Issue by ajimenezg24** [SilentChaos512/Silent-Gear#525]
## Versions

- **Silent's Gems**: 1.16.5-3.7.16
- **Silent Gear**: 1.16.5-2.6.35 
- **Silent Lib**: 1.16.5-4.10.0
- **Forge**:  1.16.5-36.2.35
- **Modpack**: Yes 
- **Optifine Installed**: Yes 

## Expected Behavior

I would like to be able to craft and use the mod without problems on my server

## Actual Behavior

In a player, testing the mod if it lets you craft the tools, with minecraft materials such as iron and diamond at the same time as those of the mod itself. But when I've tried it on our minecraft server at Nitrado, it won't let me. I put the materials with the plan and everything exactly the same and there is no crafting at all.

## Links/Images

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1. 
2. 
3.

**Comment by SsjGabe360** [comment]
Have you ever tried Aternos? If Aternos doesn't work then can you send me the modpack?
