### ISSUE TITLE
Severe TPS drops if used in combination with other mods

### ISSUE THREAD

**Issue by Graphicscore** [SilentChaos512/Silent-Gear#529]
## Versions

- **Silent Gear**: **silent-gear-1.18.2-2.10.10.jar**
- **Silent Lib**: **silent-lib-1.18.2-6.2.0.jar**
- **Forge**:  **forge-1.18.2-40.1.60**
- **Modpack**: ATM7 (latest)
- **Optifine Installed**: No

## Expected Behavior
No severe TPS drops / performance drops

(Description here)

## Actual Behavior
If you have silent gear installed in some cases it will cause severe TPS performance drops if used in conjunction with other mods.
In this example we're having the create mod installed and their mixer will constantly pull the recipes (which is a bad thing imo) but it seems like silentgear is not caching the recipes because it takes a significant amount of time.
Please see spark log attached.
(Description here)

## Links/Images
https://spark.lucko.me/lnoeWCiKcS

## Steps to Reproduce the Problem

1. Have create mod installed
2. Have silent gear mod installed
3. Place a mixer with a basin outputting on a belt, and don't apply a recipe filter

**Comment by SilentChaos512** [comment]
I see it references my method `BlueprintIngedient.getItems`... I'll take a look at it after work today if I have time.
