### ISSUE TITLE
random crash (mod interaction?)

### ISSUE THREAD

**Issue by LlubNek** [SilentChaos512/Silent-Gear#53]
Minecraft occasionally crashes at random with a silent gear tool in hand.
Might be related to console hud mod.

[crash-2019-08-27_21.05.40-client.txt](https://github.com/SilentChaos512/Silent-Gear/files/3548690/crash-2019-08-27_21.05.40-client.txt)
[latest.zip](https://github.com/SilentChaos512/Silent-Gear/files/3548692/latest.zip)

**Comment by SilentChaos512** [comment]
Looks like the Console HUD mod is doing something strange with tooltips. Not sure if that's something I can/should fix. Have you reported the issue to Console HUD as well?
