### ISSUE TITLE
[1.18.2] - Slingshot causes FPS drop when in hotbar and when opening inventory

### ISSUE THREAD

**Issue by ToxinZangoose** [SilentChaos512/Silent-Gear#532]
## Versions

- **Silent Gear**: 2.10.14
- **Silent's Gems**: 4.3.1
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.73
- **Modpack**: Custom
- **Optifine Installed**: Using Rubidium instead

## Expected Behavior
Slingshot was meant to be an alternative to a bow in my pack but it's almost unusable
with its FPS issue.

## Actual Behavior

Placing the slingshot in my hotbar or opening my inventory with it inside caused FPS to drop, enough to cause latency on inputs.

## Steps to Reproduce the Problem

1. Craft a slingshot with iron arms and an osmium handle plus a string cord.
2. Hold the completed tool in your hotbar or inventory to see this happen.
3.

**Comment by SilentChaos512** [comment]
What about without Rubidium installed? Some rendering and "performance" mods can cause performance issues like this.

**Comment by ToxinZangoose** [comment]
Removed rubidium and it appears to have fixed the issue. Thank you for the response and suggestion!

**Comment by SilentChaos512** [comment]
Good to hear. There's probably nothing else I can do about this, so I'll go ahead and close the issue.
