### ISSUE TITLE
Silent Gear Doesn't mine other Mods

### ISSUE THREAD

**Issue by Klouver-github** [SilentChaos512/Silent-Gear#535]
## Versions

- **Silent Gear**: 2.10.14
- **Silent's Gems**: N/A 
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.76
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Create a Tool with compatible resources
2. MIne (example: AllTheModium) with a Iron Obsidian Pickaxe
3. No raw Ore given unless you use a diamond or different modded pickaxe

**Comment by SilentChaos512** [comment]
Possibly the same issue as #544?

**Comment by osirisgothra** [comment]
I noticed (havent verified in the newest version) that when starting ATM8, there is nickel (alltheores) that reads harvest level 1 
like this:
![image](https://user-images.githubusercontent.com/4777106/233811266-141f836b-4667-408a-a6e2-800403c6d6da.png)

When trying to mine nickel, it very oddly does not work like you would expect:
![image](https://user-images.githubusercontent.com/4777106/233811294-f7426aa5-bc03-41a5-9f55-9cffac299408.png)
And of course when you try to mine it anyway, it drops nothing, as the tip suggests.

I'll see if any updated version allows for this, not sure if it matters that the materials are zinc (also from alltheores), but then again it says right in the tip that it is level 1/iron. I assume its an inter-mod compatibility thing. If I figure a way through or around I'll post back.
