### ISSUE TITLE
Fluffy plant has problems with texture transparency

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/Silent-Gear#537]
version silent-gear-1.19.2-3.0.1.jar 
![fluffy](https://user-images.githubusercontent.com/96169906/191994492-287d03d4-56e9-4cca-a739-ab80e89ce2da.png)
See screenshot

**Comment by f0kx** [comment]
i also have this bug only for information!

**Comment by YuRaNnNzZZ** [comment]
This issue affects all blocks with transparent textures from the mod.
![2022-09-28_06-22-22_4ba837d6-0d65-4ddb-90b2-771d931c3039](https://user-images.githubusercontent.com/5104603/192680281-c0f30c1e-cd28-4498-849e-8fd9d7fa4e5f.png)

**Comment by YuRaNnNzZZ** [comment]
It can be fixed by putting `"render_type": "cutout"` or `"render_type": "translucent"` in the model's JSON file.
![2022-09-28_06-54-04_2629d375-bffc-473b-a2a5-28732966fc42](https://user-images.githubusercontent.com/5104603/192684456-078dc47f-5c4b-4fd5-b0ce-77712805d088.png)

**Comment by uhloin** [comment]
Hmm... could you be more specific? I changed files in .jar:
\assets\silentgear\models\block\fluffy_plant0.json ... fluffy_plant3.json
Insert line   
"render_type": "translucent", 
after 
"parent": "minecraft:block/crop",
Restart minecraft but picture is not changed as yours.

**Comment by SilentChaos512** [comment]
It's something I need to fix. I figured the transparency flag moved to the model JSON. Thanks for confirming that @YuRaNnNzZZ.

**Comment by YuRaNnNzZZ** [comment]
There are still blocks present that are affected by this issue (1.19.2-3.0.4)
![2022-10-08_19-07-10_a68e4672-7640-41c5-9f05-50c854afffe2](https://user-images.githubusercontent.com/5104603/194716846-6eaede65-aca5-4503-ae75-e038c274a5ef.png)
![2022-10-08_19-21-24_8aa9ad7c-9b0a-4c9c-b4da-00698d2c6932](https://user-images.githubusercontent.com/5104603/194717385-ddaeec74-8d1f-42ec-98f5-d0d64f09814d.png)
