### ISSUE TITLE
Vanilla Materials Don't Work With Parts or Repair Kits

### ISSUE THREAD

**Issue by Shultzy96** [SilentChaos512/Silent-Gear#539]
## Versions

- **Silent Gear**: 2.10.15
- **Silent's Gems**: 4.3.1 
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.80
- **Modpack**: The PI Pack
- **Optifine Installed**: No 

## Expected Behavior

To be able to build tools and gear from the Silent Gear mod. At the very least using Vanilla materials.

## Actual Behavior

All Vanilla materials are labeled as "Empty Tags" as well as most modded materials. Cobblestone doesn't even work. I'm able to convert existing Vanilla tools into Silent Gear ones but with no ability to repair them.

## Links/Images

Images:
![2022-10-04_15 22 05](https://user-images.githubusercontent.com/45430651/193920182-2d8cb572-3bc7-4d3f-8dbb-4706eecf22ba.png)
![Pickaxe-Head-Issue](https://user-images.githubusercontent.com/45430651/193920185-027b5a52-d3f3-422a-a64e-2f8c0bb9a863.PNG)
![Repair-Kit-Issue](https://user-images.githubusercontent.com/45430651/193920187-e99f4e2b-6c16-4424-a5b7-785a6e0cf20c.PNG)

no crash report only issue within the game.

## Steps to Reproduce the Problem

1. Load into world
2. Attempt to craft a Silent Gear tool
3. Repeat

**Comment by SilentChaos512** [comment]
Something in your mod pack must be breaking item tags somehow. There's nothing I can do about that.

**Comment by Shultzy96** [comment]
what are the tags that need to be assigned to the silent gear stuff. I can assign the tags manually for everything. Like what tags is Silent Gear looking for so I can add that tag to all the materials it uses.

**Comment by SilentChaos512** [comment]
Most of the tags are added by Forge. Everything works out-of-the-box normally. Like the tag for iron ingots is `forge:ingots/iron`. All mods use it.

**Comment by Shultzy96** [comment]
Well thanks for the help. Love the work you've done with Silent Gear and the Silent Lib!

**Comment by Devostar** [comment]
Hey @Shultzy96,

I'm playing the same pack, care to share your method of fixing said issue?

Also @SilentChaos512 I see the tags in this case, but its not recognizing them as crafting materials.
![image](https://user-images.githubusercontent.com/7561011/195425922-6f8080fd-8e34-4d5d-b75a-ec694ccdfefc.png)
![image](https://user-images.githubusercontent.com/7561011/195426105-1db672d2-aa0b-49b8-9c54-0a53f11433b6.png)

How would i go on fixing the item tags?
Thanks in advance and sorry for commenting in a closed issue.

**Comment by Shultzy96** [comment]
@Devostar I'm working on a fix to let the tags in the pack cooperate. Hoping to have it fixed soon. Right now Tinkers Construct is the only other option for modular tools. As this issue is closed on the Silent Gear github, please move any issues with the pack to the CurseForge page here: https://www.curseforge.com/minecraft/modpacks/the-pi-pack

Thanks,
Shultzy
