### ISSUE TITLE
Bort in world generation

### ISSUE THREAD

**Issue by RuffertoNGroo** [SilentChaos512/Silent-Gear#541]
- **Silent Gear**: 3.0.4
- **Silent's Gems**: 4.4.0
- **Silent Lib**: 7.0.3
- **Forge**: 43.1.28
- **Modpack**: N/A 
- **Optifine Installed**: No

## Expected Behavior

Bort ore generates within 20 levels above bedrock

## Actual Behavior
No bort ore appears in any level.  Over 10k blocks excavated with 3x3 hammer.

Bort ore, both deepslate and stone versions, is in JEI, but not encountered.

Is there a configuration, or can one be added for bort generation?

**Comment by SilentChaos512** [comment]
It was generating last time I checked...

World generation is handled by data files now. The placed feature file is [here](https://github.com/SilentChaos512/Silent-Gear/blob/1.19.x/src/generated/resources/data/silentgear/worldgen/placed_feature/bort_ore.json). It should allow up to 6 veins per chunk between Y -60 and 10 with the current settings.

**Comment by RuffertoNGroo** [comment]
Looking in the config files, is there an effect or reason why netherrack and end stone have forge: as their type tag for crimson iron and azure silver, versus bort with minecraft:stone_ore_replaceables ?

**Comment by SilentChaos512** [comment]
Minecraft has no tag for end stone. For the netherrack tag, it's to separate the blackstone version of the ore.

**Comment by Paraxdq** [comment]
I can confirm, that there is no bort ore spawning. Playing ATM 8 - 0.1.5.

**Comment by RuffertoNGroo** [comment]
I am using other ore generating mods, namely Mekanism and Immersive Engineering.  Biome-wise, I'm using Biomes o' plenty.

**Comment by RuffertoNGroo** [comment]
Tested with Silent gems, gear, scaling health, JEI, journeymap, and wthit (waila fork).  Went down to z: -29 and cored to x: -1200 with a wide plate hammer.  Saw most overworld gems and all ores, no bort.
