### ISSUE TITLE
Harvest Levels do not work higher than 4

### ISSUE THREAD

**Issue by jsabol** [SilentChaos512/Silent-Gear#544]
## Versions

- **Silent Gear**: 1.18.2-2.10.16
- **Silent's Gems**:  N/A
- **Silent Lib**: 1.18.2-6.2.0
- **Forge**: 1802.3.6-build.140
- **Modpack**: All The Mods 7 0.4.32
- **Optifine Installed**: No

## Expected Behavior
I created a datapack to add new materials based on the allthemods ores (allthemodium, vibranium, unobtainium). I expect to be able to set a `harvest_level` of 5, 6, and 7 and harvest ATM ores with my Silent Gear tools according to those levels.

## Actual Behavior
The tools I added with my datapack (harvest level 5, 6, 7) do not register as able to mine the associated ores (allthemodium, vibranium, unobtainium). The One Probe shows that the tools will not work, and as you would expect, the ores take a long time to break and do not drop anything.

## Links/Images

- My datapack I was working on creating: [SGear-Allthemodium.zip](https://github.com/SilentChaos512/Silent-Gear/files/9847389/SGear-Allthemodium.zip)
- [Image where you can see my allthemodium paxel cannot mine vibranium](https://user-images.githubusercontent.com/7842360/197413672-d56dada4-98db-44cd-9030-998d96f987f4.png)
- Code where the ATM modpack sets up the 5, 6, and 7th level tiers at: [ToolTiers.java](https://github.com/AllTheMods/AllTheModium/blob/1.18/src/main/java/com/thevortex/allthemodium/material/ToolTiers.java#L30)
- In my investigation, I noticed that [GearHelper.java uses this switch in getTier](https://github.com/SilentChaos512/Silent-Gear/blob/1.18.x/src/main/java/net/silentchaos512/gear/util/GearHelper.java#L442) when checking if a block is breakable, which only returns vanilla tiers.

## Steps to Reproduce the Problem

1. Download the [SGear-Allthemodium.zip](https://github.com/SilentChaos512/Silent-Gear/files/9847389/SGear-Allthemodium.zip) and install as a resource pack and datapack
2. Make an allthemodium, vibranium, and unobtainium paxel.
3. Attempt to break vibranium ore with any of the three tools. It will not work. Attempt to break the unobtainium ore with vibranium or unobtainium. It will not work.

**Comment by LuminaSapphira** [comment]
Harvest levels higher than 4 are discarded and capped at 4 (vanilla netherite). A short-term fix could be to do a lookup in the ToolSortingRegistry from Forge based on the harvest level int and return that tier rather than only selecting from the vanilla tiers. A longer term solution might be to register tool tiers to the ToolSortingRegistry (I think this can be done during datapack loading). For every harvest level above 4, register a new tier. (Ideally, check to see if a tier is already registered and use that instead, there is no support for same level tiers.)

Relevant code:
https://github.com/SilentChaos512/Silent-Gear/blob/d2169a21f45fc4c60b18ba7507ddf5b553398a75/src/main/java/net/silentchaos512/gear/util/GearHelper.java#L441-L470

**Comment by osirisgothra** [comment]
I can understand a 4 cap but cannot understand why lower than 4 on some mods just do not work... I am guessing inter-compatible something needs to be manually added

**Comment by SilentChaos512** [comment]
I think the only proper solution to this is to replace harvest levels with tool tiers. Numerical levels just don't work correctly anymore outside of the vanilla game (and most mods, technically...) This could be an incredibly complex change to make.

**Comment by SilentChaos512** [comment]
This issue should be resolved in version 3.6.0 and higher (Minecraft 1.20.1). Materials can now specify any `Tier` defined by vanilla or a mod. This replaces the harvest level stat. There are no plans to backport the changes to earlier versions at this time.

Code changes here: https://github.com/SilentChaos512/Silent-Gear/compare/59e581ab7267...156eadd70543
