### ISSUE TITLE
Ranom server connection bug "Red Card"

### ISSUE THREAD

**Issue by Zelioth** [SilentChaos512/Silent-Gear#545]
- **Silent Gear**: 3.0.4
- **Silent's Gems**: 4.4.0
- **Silent Lib**: 7.0.3
- **Forge**: 43.1.47
- **Modpack**: Friends United
- **Optifine Installed**: No

## Expected Behavior
To no cause issue when connecting to server from client. 

(Description here)

For some odd reason when updating my client I am attempting to connect to my server with the exact same mods it gives this error 
"internal exception : java.lang.illegalstateException: unknown trait SilentGear:Red_Card"

It does not allow me to connect to the server and the logs do not give anymore info. once you press "Back to server list" you have to restart client in order to reconnect but this is happening everytime. 

## Links/Images
![Screenshot 2022-10-27 202958](https://user-images.githubusercontent.com/77481431/198439882-96791ae9-bafc-4e9c-a797-51be86b36baa.jpg)
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/9884389/latest.log)

**Comment by SilentChaos512** [comment]
Hard to say why exactly this is happening, but I think I know a way to fix it.
