### ISSUE TITLE
[1.19.2] Bort ore does not generate

### ISSUE THREAD

**Issue by Draskh** [SilentChaos512/Silent-Gear#548]
## Versions

- **Silent Gear**: 3.0.5
- **Silent's Gems**: 4.4.0
- **Silent Lib**: 7.0.3
- **Forge**: 43.1.43

## Expected Behavior
Bort Ore to be found in the overworld. I checked with Digital Miner, No Bort ore anywhere.

**Comment by SilentChaos512** [comment]
Duplicate of #541
