### ISSUE TITLE
Crash when generating a world.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#55]
## Versions

- **Silent Gear**: SilentGear-1.14.4-1.3.10+59.jar
- **Silent's Gems**: SilentGems-1.14.4-3.3.10+67.ja
- **Silent Lib**: SilentLib-1.14.4-4.3.1+39.jar
- **Forge**: 28.0.93
- **Modpack**: [TNP Limitless](https://www.curseforge.com/minecraft/modpacks/tnp-limitless)
- **Minecraft version**: 1.14.4

## Expected Behavior

- I'm creating a world, expecting it to work without issues.

## Actual Behavior

-  I'm creating a world but instead it gets stuck at 100% and freezes, MC stops responding. And results in a crash.

## Links/Images

- Crashreport: https://paste.ee/p/TDgfg
- Screenshot of frozen mc: [Imgur](https://i.imgur.com/eMAuBG8.png)

## Steps to Reproduce the Problem

1. Load up pack (MC)
2. Create a world
3. Wait, and it gets stuck at 100% generated.

**Comment by SilentChaos512** [comment]
Update Silent Lib to 4.3.2. It fixes the crash caused by the name changes in Forge 92+.

**Comment by Gbergz** [comment]
Oh yeah, that fixes it! Thank you.
