### ISSUE TITLE
Lost textures for fragments

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/Silent-Gear#551]
Minecraft 1.19.2
forge-1.19.2-43.1.47-installer.jar
silent-lib-1.19.2-7.0.3.jar
silent-gear-1.19.2-3.0.5.jar

The fragments which Salvager produced has not textures for example "Blaze Rod Fragment", "End Rod Fragment" and other.

**Comment by LupusTheFallen** [comment]
Can confirm, also happens in silent-gear-1.19.2-3.1.5.jar. Using JEI and looking up "fragment" shows the item with missing texture.
Maybe add something like a nugget or small chunk of material instead of just using no texture.

**Comment by SilentChaos512** [comment]
Will be fixed in version 3.2.2 by bf1c2f3bbfe93808dbb9e775b8b94ce83c113138.
