### ISSUE TITLE
SG crafted shield does not move as vanilla

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/Silent-Gear#556]
Looks like blocking animation (on right click) is broken for crafted SG shield (I used end rod and springaline shards).

**Comment by SilentChaos512** [comment]
Please follow the issue template next time...

But I'm assuming you mean the Minecraft 1.19.2 version. None of the animations are working currently.

**Comment by uhloin** [comment]
Yes, 1.19.2
Anyway thank you for very interesting and perspective mod. All these issues I reported are not critical and not ruin good impression.
