### ISSUE TITLE
Grader/Starlight charger does not work

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/Silent-Gear#557]
Minecraft 1.19 Forge
silent-lib-1.19.2-7.0.3.jar 
silent-gear-1.19.2-3.0.6.jar 
silents-gems-1.19.2-4.4.0.jar 

Material Grader and Starlight Changer allow to insert gems, consume catalyst but give zero effect.

Diamond adorement gives +1 Armor
MAX grade, Starcharged III gives the same +1 Armor
If they do nothing then should not allow insert gems.

**Comment by SilentChaos512** [comment]
I think you are misunderstanding how the stat modifiers work. Grade and charging bonuses don't apply to everything. They mostly just affect the main material stats. Not adornment bonuses.

**Comment by uhloin** [comment]
May be from point of view internal code or java class structure member like "double headArmor = 4" is different from thing "int adorementArmor = 1", but from point of view of player both are about armor and some numbers. For RPG purposes they shoud work in similar way. Adorement bonuses are invisible in material info until make ring/bracelet and you cannot get back your gem with grades/charges.
