### ISSUE TITLE
Potion Effect Trait appears to be missing from git and mod

### ISSUE THREAD

**Issue by Starwhip** [SilentChaos512/Silent-Gear#559]
## Versions

- **Silent Gear**: 3.0.8
- **Silent Lib**: 7.0.3
- **Forge**: 43.1.57
- **Optifine Installed**: No

## Expected Behavior
Adding the silentgear:potion_effect_trait listed in the wiki to an armor would allow for a potion effect to be applied as a trait.

## Actual Behavior
Log throws this error:
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Invalid or unsupported trait type silentgear:potion_effect_trait

**The git source at https://github.com/SilentChaos512/Silent-Gear/tree/1.19.x/src/main/java/net/silentchaos512/gear/gear/trait does not list a potion effect trait.**

**Comment by Starwhip** [comment]
Actually I am not sure this is a bug per se- potion effect trait is in the extended traits list, but not the normal one. The **silentgear:wielder_effect** trait seems to have the functionality required.

**Comment by SilentChaos512** [comment]
`silentgear:wielder_effect` is the one you want. Some trait types were renamed for consistency. Sorry for the confusion.
