### ISSUE TITLE
Silent Gear crash on loading screen

### ISSUE THREAD

**Issue by zadzial** [SilentChaos512/Silent-Gear#56]
## Versions

- SilentGear-1.14.4-1.3.10+58, 59 & 60
- SilentGems-1.14.4-3.3.11+71
- SilentLib-1.14.4-4.3.1+39
- **Forge**: forge-1.14.4-28.0.102 (tried 93+)

*also having issues with Xaeros_Minimap_1.18_Forge_1.14.4, but still happens when Silent Gear is used when the minimap is not present - see crash report. 
* may be an issue with StorageDrawers-1.14.4-6.0.0/1 - see third attachment, which occurred when I tried using Silent Gear 56. This issue did not happen when Silent Gear was removed, and Storage Drawers was the most recent addition to the mods folder over all. However, it worked well together for over 24 hours before the initial crash. Storage Drawers remains functional, if a little buggy, but Silent Gear will not work with or without Silent Drawers in the mod folder.

## Expected Behavior
Minecraft works!

- (Description)

## Actual Behavior
At first I was in a world and the game crashed - see attachment 1 (crash-2019-09-10_16.14.53-server.txt). If memory serves I was simply transferring items from the furnace to a crate. I don't know if it helps, but I was not currently using any SG modded tools, nor were any present in the game world. trying to reload has not worked since while Silent Gear has been in the mod list. 

Minecraft loads as normal until a world is selected. It does not matter which world is selected.
When loading with Silent Gear (58+) in the mods folder, Minecraft loads to 100% on the loading screen, then hangs indefinitely. Simply hangs until Windows decides it's had enough and tells me it's not responding. I include the latest crash report as well.

At first I tried updating forge from 91 to 101, then backtracked to 93 and when 102 came out tried that. Note that the minimap will not work with forge over 91, and now Silent Gems requires 93+ the minimap will remain off my list until it is updated. Sadly, the change of Forge version mattered not at all.

I removed all mods and slowly introduced more until the effect was replicated, starting with Silent Lib (as the most important!) - which worked, then the most recently updated (Silent Mechanisms, which also worked) and then Silent Gear. It was after this I discovered the clash with Xaeros Minimap and Forge 92+, as it occurred later in the startup than Silent Gears crash. Finally when checking earlier SilentGear versions I discovered the issue with Storage Drawers. 

Also note that when Storage Drawers is removed and attempting to load with Silent Gear 56 and Forge 93-102, The error message is "Silent's Gems 3 has failed to load correctly. net/silentchaos512/gear/api/even/GearNamePrefixesEvent"
but no crash report generated.

[crash-2019-09-11_07.21.30-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/3597904/crash-2019-09-11_07.21.30-server.txt)
[crash-2019-09-10_16.14.53-server.txt](https://github.com/SilentChaos512/Silent-Gear/files/3597905/crash-2019-09-10_16.14.53-server.txt)
[crash-2019-09-11_08.18.04-client.txt](https://github.com/SilentChaos512/Silent-Gear/files/3597954/crash-2019-09-11_08.18.04-client.txt)

## Steps to Reproduce the Problem

1. Load minecraft with forge (93+) while Silent Gear 58+ is in the mod folder
2. Silent Gear and Storage Drawers appear incompatible. Silent Gear remains problematic even after removal of Storage Drawers, this is a separate issue.

Hope this helps in some way.

**Comment by SilentChaos512** [comment]
First, you should try updating your mods. In particular, you need Silent Lib 4.3.2 if you are using Forge 92 or later. Recent version of Gems also require an event added in Gear 1.3.9, so you need to use at least that version.

**Comment by zadzial** [comment]
Awesome! Thankyou!

 

I have no idea how I managed to miss the library update. That was the clincher. Saved again.

 

Thanks,

Ben
