### ISSUE TITLE
Really strange crash with BYG when Silent Gear & SilentLib is removed

### ISSUE THREAD

**Issue by Lilygabe** [SilentChaos512/Silent-Gear#561]
## Versions
1.18.2

- **Silent Gear**: 2.10.16
- **Silent's Gems**: N/A
- **Silent Lib**: 6.2.0
- **Forge**: 40.1.84
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Silent gear is removed from modlist, all data from it is deleted and the game runs normally.

## Actual Behavior

Minecraft crashes, and a long crash report is thrown, detailing how BYG doesn't find data from a Silent Gear villager [?]

## Links/Images

- [(Link)](https://pastebin.com/2Jp6C4Jx)

## Steps to Reproduce the Problem

1. Install BYG, SilentGear and SilentLib (I am not sure if other mods are involved, though);
2. Open, play, and create a new world
3. Exit Minecraft
4. remove SilentGear and SilentLib

**Comment by SilentChaos512** [comment]
Your log says the value is being used in a BYG config file. So I'm guessing  the best solution would be to either modify or delete the file(s) in question.

**Comment by uhloin** [comment]
This is bug of BYG which owner of BYG do not want to fix. He said me it is intended behaviour. After add/remove of mods you must manually clear BYG cashe i.e. folder config/byg and restart game.

**Comment by SilentChaos512** [comment]
Fair enough. Either way, there's nothing I can do about it, so I'll consider this issue closed.
