### ISSUE TITLE
Stone Torch Lighting Bug

### ISSUE THREAD

**Issue by bryce-hoehn** [SilentChaos512/Silent-Gear#565]
Hello, I'm using the stone torches from this mod in ATM8 and have been having this weird lighting bug: 
![image](https://user-images.githubusercontent.com/1351017/208265229-19c5764e-13c1-489a-91e5-8504c2a9d4cb.png)

It does not seem to affect vanilla torches or any other lighting sources that I've encountered so far.

**Comment by SilentChaos512** [comment]
Duplicate of #537. I keep forgetting to fix that one...
