### ISSUE TITLE
Very High Render Thread time/% from SilentGear getItemColor / GearData.getBlendedColor()

### ISSUE THREAD

**Issue by sleepingrainbow** [SilentChaos512/Silent-Gear#566]
## Versions
- **Silent Gear**: 3.1.0
- **Silent's Gems**: NA
- **Silent Lib**: 7.03
- **Forge**: 43.1.55
- **Modpack**: All the mods 8
- **Optifine Installed**: No  (but rubidium and oculus are)

## Description
examining profiler results from sparkc (mods view) to try to figure out my framerate loss, i discovered silent gear is using a huge percentage of the render time/render thread %, mostly from net.silentchaos512.gear.util.GearData.getBlendedColor() its using up to 18% of the render thread just walking around a little and swapping between 2 silentgear tools in my hotbar that have varied material parts (this is with shaders turned off btw). Here's the full profiler report from the worst I observed it. 

## Links/Images
https://spark.lucko.me/tOgwUFaqGt

**Comment by SilentChaos512** [comment]
I see... The color values used to be cached before Forge nuked everything the original model system was built on before 1.19. The values definitely are being calculated constantly now. I'll figure out a way to cache them again.

**Comment by taiyoko** [comment]
Having this issue as well on Silent Gear 3.2.5/Silent Lib 7.0.3 as included in ATM8

https://spark.lucko.me/ozCJIcH8y3

**Comment by pascalklassen** [comment]
Thank god you found this one out. I was looking for my FPS Issues for days now, and I just found out, that my fps drop from 130+ to 30~ ish FPS when my hotbar is full of SG tools^^

**Comment by Pocky-l** [comment]
@SilentChaos512 Please fix the problem...

**Comment by Pocky-l** [comment]
@taiyoko @pascalklassen @sleepingrainbow 
I have partially fixed the FPS issue. Please message me on Discord if you need my fix.
Pocky#2858

**Comment by ghost** [comment]
Having this issue as well. I remove silentgear tools from my hot bar and FPS jumps from 30 to 150. Found it out using spark

**Comment by ghost** [comment]
![image](https://github.com/SilentChaos512/Silent-Gear/assets/83978069/4c73b64f-5af5-4468-9d77-94b929aa978b)

**Comment by SilentChaos512** [comment]
I have a potential improvement done. Before changing anything, I tested and Minecraft reported 850 FPS (uncapped) with nothing in my hotbar, and around 280 with a full hotbar of random gear items. After creating a color value cache, it drops to 480 instead. Hopefully that will yield a noticeable improvement on most systems, but I have no other hardware to test it on right now.
