### ISSUE TITLE
Giving errors with kubejs

### ISSUE THREAD

**Issue by Diversion98** [SilentChaos512/Silent-Gear#572]
## Versions

- **Silent Gear**: 3.1.2+ (3.1.2 works fine but 3.1.3 and 3.1.4 has this issue)
- **Silent's Gems**: N/A
- **Silent Lib**: 7.0.3
- **Forge**: 43.2.3
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/mhg-cities
- **Optifine Installed**: No

## Expected Behavior
Not give KubeJS errors

Hi,

I'm the developer of MHG: Cities! (link above) and i have come across a weird issue and I allready talked with the people from KubeJS about this.
Since Silent Gear 3.1.3, My scripts give 4 errors: https://pastebin.com/qEiq6gZ6.
After some investigation with the KubeJS team, these are my findings:

Erroring script 1:
script: https://pastebin.com/TdTJBMse
errors in debug.log: https://pastebin.com/PmF10MtJ
kubejs log: https://pastebin.com/966bCcys

Erroing script 2:
script: https://pastebin.com/LQyHAeTL
errors in debug.log: https://pastebin.com/xucp5K7v
kubejs log: https://pastebin.com/32jVE8Zp

One of the members said:
seems that when kubejs checks the output, silent tries to create a tool item and fails cause its too early in the load progress to have the stats ready

## Steps to Reproduce the Problem

1. install kubejs and silent gear 3.1.2+ 
2. use my scripts
3. see 4 errors ingame

**Comment by SilentChaos512** [comment]
Your kubejs logs point to the recent gear model changes being the cause. Should be an easy enough fix.
