### ISSUE TITLE
No vanilla flowers when bone mealing grass blocks

### ISSUE THREAD

**Issue by Diversion98** [SilentChaos512/Silent-Gear#573]
## Versions

Silent Gear: 3.1.1+ (only tested 3.1.2, 3.1.3, 3.1.4, 3.1.5)
Silent's Gems: N/A
Silent Lib: 7.0.3
Forge: 43.2.3
Modpack: https://www.curseforge.com/minecraft/modpacks/mhg-cities
Optifine Installed: No

## Expected Behavior
Get Vanilla minecraft flowers when bone mealing grass blocks

## Actual Behavior
If you bone meal grass blocks (tested several vanilla minecraft biomes), you only get tall grass and Wild Flax Plant.
If I disable Silent Gear and run the pack again, Poppy's, dandelions,... do spawn with bone meal

## Steps to Reproduce the Problem

1. Install any of the versions above, maybe earlier versions as well
2. Bone Meal grass blocks

**Comment by SilentChaos512** [comment]
Duplicate of #540.

**Comment by Diversion98** [comment]
yup, didnt scroll down enough, sorry
