### ISSUE TITLE
crashes when config file for silent gear is opened

### ISSUE THREAD

**Issue by iNunez1** [SilentChaos512/Silent-Gear#574]
## Versions

- **Silent Gear**: x.x.x
- **Silent's Gems**: x.x.x 
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Closing this as no information is provided. Follow the template and provide a crash report file.
