### ISSUE TITLE
Throwing Trident on Server [ATM8]

### ISSUE THREAD

**Issue by ThisIsNotMe1612** [SilentChaos512/Silent-Gear#575]
## Versions
- **Silent Gear**: silent-gear-1.19.2-3.1.2
- **Silent's Gems**: N/A
- **Silent Lib**: silent-lib-1.19.2-7.0.3
- **Forge**: 43.1.55
- **Modpack**: Allthemods 8 Version 1.0.7
- **Optifine Installed**: No

## Expected Behavior
When holding right-click with a silent-gear trident in the main hand and then releasing the trident should be thrown as a projectile weapon, like its vanilla counter part.

## Actual Behavior
In a singleplayer world the trident acts as expected.
When playing on a dedicated server the trident gets "raised" but on release of the mouse button the trident returns to its usual spot on the screen and an error message is generated in the server logs.

Sadly i dont have the ressources to check if this can be reproduced with just Silent Gear installed.

## Links/Images
Generated Error Message:
https://pastebin.com/41FEDhi5

## Steps to Reproduce the Problem
1. Play on a dedicated server
2. Craft a trident from Silent Gear
3. Attempt to throw it

**Comment by Xplodin** [comment]
Cant throw trident on atm10 (1.21.1)
