### ISSUE TITLE
Netherite ingot doesn't have armor value.

### ISSUE THREAD

**Issue by KRWCLASSIC** [SilentChaos512/Silent-Gear#582]
## Versions

- **Silent Gear**: 2.6.30
- **Silent's Gems**: 3.7.16
- **Silent Lib**: 4.9.6
- **Forge**: 1.16.5 36.2.35
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior
Netherite ingot should have armor value

## Actual Behavior
Netherite ingot doesn't have armor value = can't use it in things like armor crafting and alloy making

## Links/Images
- https://i.imgur.com/cGbAEJ8.png
- https://i.imgur.com/7KwZO6G.png

## Steps to Reproduce the Problem

1. Take nethrite ingot
2. Hold ctrl
3. Look there is no armor value but other armor-related things like armor toughness

**Comment by SilentChaos512** [comment]
Not a bug. Netherite's stat modifiers are set so that netherite coated diamond gear will perfectly match vanilla netherite stats.
