### ISSUE TITLE
Getting NaN/NaNx durability/armor durability on alloys and being unable to use them further crafting

### ISSUE THREAD

**Issue by Wr1nGl** [SilentChaos512/Silent-Gear#585]
## Versions

- **Silent Gear**: 1.16.5-2.6.30
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.2.39
- **Modpack**: ATM6 1.8.28
- **Optifine Installed**: Yes

## Expected Behavior

Inf/infx to appear on durability/armor or clamped maxint(or any other number).

## Actual Behavior

getting nan/nanx on durability/armor durability and being unable to use the alloy in the crafting further

## Links/Images

- https://prnt.sc/4rwHOeElgM1a (sorry, no idea how to make it show directly)

## Steps to Reproduce the Problem

1. get uru metal
2. max grade uru metal ingot and unob-vib alloy ingot (from atm modpack, not sg creation)
3. apply starcharged 5000 to both
4. combine them in metal alloyer

**Comment by SilentChaos512** [comment]
Since this is an older version of the mod, and so far outside of intended levels for starcharging, I don't see any point in fixing this.
