### ISSUE TITLE
"Tier 3 Starlight charger P 100%" hud notification

### ISSUE THREAD

**Issue by Kyuketsuki57** [SilentChaos512/Silent-Gear#589]
1.19.2 Versions

- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: All the Mods 8
- **Optifine Installed**: No 

## Expected Behavior

Starlight charger to give notification "Tier 3 Starlight charger P 100%" when full and then the notification to disappear when I remove the charger

## Actual Behavior

The notification will not remove or change since I broke the charger, have replaced charger and notification is not updated and has stayed the same 

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by Kyuketsuki57** [comment]
Sorry if I didn't fill the bug report out correct not done one before, if there is an option somewhere in the config for me to just turn off the hud notifications that would be great

**Comment by SilentChaos512** [comment]
What notification are you talking about? Silent Gear does not add anything like that. You might want to contact ATM instead.

**Comment by Kyuketsuki57** [comment]
I'll try ATM instead thanks for the response, 
![PXL_20230224_145222714](https://user-images.githubusercontent.com/126243082/221209174-d13c26af-85b0-48ff-a0a2-800dd11d32e5.jpg)
This is the notification btw.

Ps love the mod :)
