### ISSUE TITLE
Tooltip Crash when Reloading Datapacks

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#59]
## Versions

- **Silent Gear**:  v1.3.11+60
- **Silent's Gems**: v3.3.13+72
- **Silent Lib**:  v4.3.2+42
- **Forge**: v28.0.102-1.14.4
- **Modpack**: Custom

## Expected Behavior

- Reloading datapacks after adding a gem to the new tag system for ore dictionary shouldn't crash the game.

## Actual Behavior

- The game crashes after adding Agate from [GemsPlusPlus](https://www.curseforge.com/minecraft/mc-mods/gemsplusplus) to the tag system for agate while in-game, the gem did not previously have this tag. Reloading the datapack using /reload caused it to crash since the agate gem from GemsPlusPlus did not have a tooltip marking it as a part that can be used by Silent Gear.

## Links/Images

- [Crash Report](https://gist.github.com/WenXin20/9956da714760b34cc314b6d9c7cb8efd)
- Datapack Used: [forge.zip](https://github.com/SilentChaos512/Silent-Gear/files/3603680/forge.zip)

## Steps to Reproduce the Problem

1. Install Datapack
2. Refresh the datapack by using /reload
3. Crash

**Comment by SilentChaos512** [comment]
Might be fixed in latest version. I didn't mean to upload to Curse, so the version number didn't get updated correctly. Full version is 1.3.11+64. It's version 1.4.0 in changelog.

**Comment by WenXin20** [comment]
Yep, this is fixed. Thanks!
