### ISSUE TITLE
Server stops when we place a part analyzer

### ISSUE THREAD

**Issue by ValgarBaldr** [SilentChaos512/Silent-Gear#60]
Here goes the crash: https://pastebin.com/6VwXP9H3

I would like to have some help with this, because i restarted the world already because we lose the grade traits and when everything was ok just this brokes my server. I had issues with other mods aswell, but we are so immerse in the gamestyle of Silent's mods that i really want to fix this somehow.

**Comment by SilentChaos512** [comment]
Uploaded a new version of Silent Lib (4.3.3) which should resolve this. Please let me know if this fixes the issue. If not, I will need an updated crash report.
