### ISSUE TITLE
When i break tools i get weird bugged error sign items

### ISSUE THREAD

**Issue by Thisguyneedshelp** [SilentChaos512/Silent-Gear#601]
## Versions
1.19.2
- **Silent Gear**: 3.2.5
- **Silent's Gems**: 4.4.2 
- **Silent Lib**: 7.0.3
- **Forge**: 43.2.4
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Preferably not drop unbreakable invisible blocks
(Description here)

## Actual Behavior
Does, that.
(Description here)

## Links/Images

![Screenshot 2023-05-09 193927](https://github.com/SilentChaos512/Silent-Gear/assets/97699212/55404569-6155-4cbb-8328-abd75a45c60c)

- (Link)

## Steps to Reproduce the Problem

1.break tools
2.broken tool turns into that
3.

**Comment by Thisguyneedshelp** [comment]
i did not put the mod list and forgot until now, my bad heres the list from a curseforge profile file:///C:/Users/David/AppData/Local/Temp/Temp1_DecapodDanSMP.zip/modlist.html ... i have no idea if you can actually access that but im just gonna hope so cause i dont have any other easy way to send the list

**Comment by SilentChaos512** [comment]
This has to be an interaction with some other mod in your pack. There's nothing I can do to help with that. Silent Gear tools are not programmed to drop anything at all when they break. You'll just have to do some digging to find the offending mod.
