### ISSUE TITLE
[1.20.1] Crossbow Held In Wrong Way (Obscures Vision)

### ISSUE THREAD

**Issue by Zedrimar** [SilentChaos512/Silent-Gear#610]
## Versions

- **Silent Gear**: 3.5.0
- **Silent's Gems**: 4.6.0
- **Silent Lib**: 8.0.0
- **Forge**: 47.0.19
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Held like standard crossbow

## Actual Behavior
Item is held vertical like a bow

## Links/Images
<img width="1920" alt="image" src="https://github.com/SilentChaos512/Silent-Gear/assets/8153290/db4cfc6d-83db-4fd8-81de-ff10272395f8">

## Steps to Reproduce the Problem

1. Make a crossbow (using parts)
2. Put item in hand
3. .....Profit?

**Comment by renandadalte** [comment]
Same issue here, tested with only Silent Gear 1.19.2-3.2.6, Silent Lib 1.19.2-7.0.3 and REI (to cheat the crossbow).

**Comment by Eqlipse** [comment]
This still seems to be an issue in the 1.20 version as well. Completely obscures visibility, effectively making the crossbow useless for longer-range engagements.
