### ISSUE TITLE
Bow doesn't draw back

### ISSUE THREAD

**Issue by ChrisRoad** [SilentChaos512/Silent-Gear#613]
## Versions
1.19.2

- **Silent Gear**: 3.2.6
- **Silent's Gems**: x.x.x 
- **Silent Lib**: 7.0.3
- **Forge**: 43.2.14
- **Modpack**: All The Mods 8
- **Optifine Installed**: Yes

## Expected Behavior
The bow draws back, showing the arrow and changing the model.

## Actual Behavior
The model stays the same as when held normally, does not show arrow.

![2023-07-09_17 25 04](https://github.com/SilentChaos512/Silent-Gear/assets/139061743/b16f546e-324a-496e-aaa0-ed1b03b2133c)
(this is fully drawn)

## Steps to Reproduce the Problem
1/2/3) Make a silent gear bow and shoot with it using either vanilla or silent gear arrows

**Comment by ChrisRoad** [comment]
still wondering why this is happening, and if its just my client or an actual mod issue.

**Comment by Naireem-sudo** [comment]
Yeah, same issue here with ATM8
