### ISSUE TITLE
1.18 Version stopped work with ice and fire materials

### ISSUE THREAD

**Issue by Rafd4** [SilentChaos512/Silent-Gear#624]
after ice and fire comes to 1.18 all materials from ice and fire cant graded or mixed with "allowLegacyMaterialMixing" to true, Dragonsteel ignots doesnt show anymore grade possibilities etc. and cannot craft coating with dragon blood. this is some bug or this 2 mods stopped working together

on Version 1.16.5 all working perfect

**Comment by SilentChaos512** [comment]
It was another mod that added support for these material, not Silent Gear.
