### ISSUE TITLE
Loot not generating

### ISSUE THREAD

**Issue by LuminaSapphira** [SilentChaos512/Silent-Gear#625]
## Versions

- **Silent Gear**: de21fff
- **Silent's Gems**: N/A
- **Silent Lib**: 8.0.0
- **Forge**: 47.0.3
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Opening a chest with one of several nether-based loot tables may yield some Silent Gear items

## Actual Behavior
No Silent Gear loot is generated

## Links/Images
N/a

## Steps to Reproduce the Problem

1. Run command `/setblock ~ ~ ~ chest{LootTable:"minecraft:chests/bastion_other"}`
2. Open chest
3. Observe there is no Silent Gear loot
4. Repeat

---

In earlier versions, there seemed to be an event hook that injected loot into certain loot table. The event hook was removed, but there doesn't seem to be a replacement. `LootTableInjectorLootModifier` seems like it was intended to replace it, but it is not registered, nor referenced in `forge:loot_modifiers/global_loot_modifiers`. I tested out a local fix that consisted of registering the modifier in `SgLoot`, creating the JSON file, and appending the modifier ID to global_loot_modifiers, that seems to work fine. The modifier is applied to all loot tables, but it ends up retrieving an empty loot table for tables without injections, and so adds no items. This could probably be optimized, but eh. I can submit a PR if desired.

**Comment by uhloin** [comment]
Hit same issue, cannot get netherwood saplings as result (MC 1.20.1)

**Comment by Medivha** [comment]
i can assume that this also affects spider/cave spider with Fine_silk drops?! Because i don't get any  after killing hundreds of them(me as a player and not with a machine)

**Comment by SilentChaos512** [comment]
I can't remember if that issue is the same thing or not, but it is something that needs to get fixed.
