### ISSUE TITLE
What's wrong with my code

### ISSUE THREAD

**Issue by sova444** [SilentChaos512/Silent-Gear#629]
{
  "type": "silentgear:standard",
  "simple": true,
  "availability": {
    "tier": 4,
    "categories": [
      "gem"
    ],
    "visible": true,
    "gear_blacklist": [],
    "can_salvage": true
  },
  "crafting_items": {
    "main": {
      "tag": "minecraft:nether_star"
    }
  },
  "name": {
    "text": "Nether star"
  },
  "stats": {
    "tip": {
      "harvest_speed": {
        "mul2": 0.25
       },
      "melee_damage": {
        "mul2": 0.25
       }
    }
  },
  "traits": {
    "tip": [
      {
        "name": "silentgear:indestructible",
        "level": 1
      }
    ]
  },
  "model": {
    "tip/all": [
      {
        "texture": "silentgear:main_generic_hc",
        "color": "#FFFFFF"
      },
      {
        "texture": "silentgear:_highlight"
      }
    ],
    "tip/fragment": [
      {
        "texture": "silentgear:metal",
        "color": "#FFFFFF"
      }
    ]
  }
}

**Comment by SilentChaos512** [comment]
For help with data packs, try asking on my Discord server: https://discord.gg/Adyk9zHnUn
