### ISSUE TITLE
Hammer not mining in 3x3 in survival but doing it in creative

### ISSUE THREAD

**Issue by SeaFoxKitsune** [SilentChaos512/Silent-Gear#630]
## Versions 
1.20.1-3.5.1

- **Silent Gear**: 1.20.1-3.5.1
- **Silent's Gems**: 1.20.1-4.6.0
- **Silent Lib**: 1.20.1-8.0.0
- **Forge**: 47.1.3
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

I expect my hammer to work as intended by mining in 3x3

## Actual Behavior

The hammer is working as a normal pickaxe in any kind of stone for some reason in survival, but when testing in creative it does work and pick the 3x3 zone

## Links/Images

Can't provide a video rn but if really needed i'll try to upload one to show the bug

## Steps to Reproduce the Problem

1. Download this modpack that i'm using that i made myself and i can provide the download link of all the mods in it via drive:
https://drive.google.com/file/d/1exBW_ghdnL82Yo3rpqialZV5UPY81rQ2/view?usp=drive_link
2. Download Forge version 47.1.3:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.1.3/forge-1.20.1-47.1.3-installer.jar
3. Try using a hammer

**Comment by SilentChaos512** [comment]
This is most likely a mod interaction issue. If you are able to identify the mod that causes this, please let me know.

**Comment by SeaFoxKitsune** [comment]
Okay, i have found the interaction issue, seems to come from HT's treechop 0.18.3 version. I'm gonna test now if with previous versions of that mod the conflict is still there. Will let you know once i test it

**Comment by SeaFoxKitsune** [comment]
Seems to be a problem related to that specific version. Since with 0.18.2 works as intended. Thanks for your help
