### ISSUE TITLE
netherwood sapplings do not grow 

### ISSUE THREAD

**Issue by ZenithAp45** [SilentChaos512/Silent-Gear#636]
## Versions

- **Silent Gear**: 3.5.1
- **Silent's Gems**: N/A
- **Silent Lib**: 8.0.0
- **Forge**: 47.1.46
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Netherwood saplings should grow into Netherwood trees

## Actual Behavior

Netherwood saplings never grow into Netherwood trees.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.Plant Netherwood sapling
2.Wait several minecraft days (I've waited at least 10)
3.Netherwood saplings never grow into netherwood trees.

**Comment by ForgetMyBelief** [comment]
Having the same issue here.  Put a bunch of saplings around and none of them seemed to grow.  Used a stack of bonemeal on one and it also didn't grow.

**Comment by uhloin** [comment]
Also cannot grow it with bonemeal or bonemeal-like magic spell from Ars Nouveau.

**Comment by BarrieREloaded** [comment]
Same issue here. It is possible for the sapling to grow from stage=0 to stage=1, but it could not generate the tree. (no entries in debug.log)

Also there is no netherwood_tree.json inside the folder
/data/silentgear/worldgen/placed_feature
(just ["azure_silver_ore.json", "bort_ore.json", "crimson_iron_ore.json", "wild_flax.json", "wild_fluffy.json"])

I use the Botany Trees mod as a workaround for now. It has support for the netherwood sapling and allows to generate the following items inside a Botany Pot [<item:silentgear:netherwood_log>, <item:silentgear:netherwood_stick>, <item:silentgear:nether_banana>, <item:silentgear:netherwood_sapling>].

**Comment by Kerbin-Fiber** [comment]
Issue also occurs to me, but with the added problem of not even generating in the nether or as loot in chests

**Comment by HydrogenC** [comment]
Same to me.
