### ISSUE TITLE
Tag #forge:cobblestone Support

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silent-Gear#64]
## Versions

- **Silent Gear**:  1.3.11+65
- **Silent's Gems**: 3.4.1+64
- **Silent Lib**:  4.4.0+44
- **Forge**: 28.1.1
- **Modpack**: Custom

## Expected Behavior

- Other mod cobblestone should be able to craft and repair stone tools

## Actual Behavior

- Despite having the recipe for the main parts for tools as `#forge:cobblestone`, this does not seem to work.
- Both crafting and repairing with modded cobblestone doesn't work.
- Tested with Underground Biomes and Embellishcraft cobblestones, which all contain the tag `#forge:cobblestone`
- Other modded material types do work correctly

## Steps to Reproduce the Problem

1. Obtain a blueprint
2. Craft with UBC cobblestone or any modded cobblestone.
3. Trying repairing the tool with UBC cobblestone.

**Comment by SilentChaos512** [comment]
Did you add the mod cobblestones to the `forge:cobblestone` tag? Neither UB nor EC have their cobblestone blocks correctly tagged. That or they only tagged the blocks and not the items. The items need to be tagged for recipes to recognize them.

**Comment by WenXin20** [comment]
That might be the case then. It's probably only the blocks that have the tags. 
I'll check later to be sure.

**Comment by WenXin20** [comment]
Yep, that was the case. The item version of cobblestone are missing the `#forge:cobblestone` tag. Adding the tag through a custom data pack fixed it. I also went ahead and reported this to those mods.
