### ISSUE TITLE
silentgear:prospector_hammer_targets, forge:ores

### ISSUE THREAD

**Issue by Sultia** [SilentChaos512/Silent-Gear#644]
## Versions

- **Silent Gear**: 3.5.2
- **Silent's Gems**: N/A 
- **Silent Lib**: 8.0.0
- **Forge**: 47.2.17
- **Modpack**: Orbit Cycle 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)
No tag error being thrown from forge
## Actual Behavior

(Description here)
Tag error being thrown on load

line 2146 on latest log
## Links/Images

N/A
- (Link)

## Steps to Reproduce the Problem

1. load mod along side all other mods in pack

[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/13637440/latest.log)

**Comment by Sultia** [comment]
All other Tier of divination rods also have same issue.

**Comment by SilentChaos512** [comment]
Your log has this line in it (line 2141):

`[09:02:41] [Worker-ResourceReload-23/ERROR]: Couldn't load tag forge:ores as it is missing following references: #forge:ores/citrin (from knightsnmages-0.0.3-neo.jar), 
	#forge:ores/scarlet (from knightsnmages-0.0.3-neo.jar), 
	#forge:ores/moonlight (from knightsnmages-0.0.3-neo.jar)`

I would check with this `knightsnmages` mod.
