### ISSUE TITLE
Hammer only mines one 

### ISSUE THREAD

**Issue by EvolutionDragon** [SilentChaos512/Silent-Gear#645]
3.5.2 Versions

- **Silent Gear**: 3.5.2.
- **Silent's Gems**: 4.6.0.
- **Silent Lib**: 8.0.0.
- **Forge**: 47.2.0.
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Break a block with hammer and mine a 3x3)

## Actual Behavior

(After making stone hammer I mined a block only to see it mine one block instead of nine not knowing the problem I made a creative world to test thing I made bronze hammer in it worked just fine so I change them game mode to survival still the creative world with the bronze hammer and it only mine one block)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
See #630. This issue is caused by a mod conflict. Nothing I can do to fix it on my end.

**Comment by EvolutionDragon** [comment]
Ok thanks for the help
