### ISSUE TITLE
Please add a config to control the stats of gear and materials.

### ISSUE THREAD

**Issue by kiase** [SilentChaos512/Silent-Gear#647]
## What Should Be Added or Changed?

- I hope that all stat values of the material(Durability, armor durability, projectile speed...etc) and the weight of the gear, like to -50% durability of the hammer, can be modified through config or datapack.

## Why Should This Be Done?

- For cases where gear balance adjustment is necessary for various reasons (balance with other modes, custom stat material)

**Comment by SilentChaos512** [comment]
This can already be done. See the `silentgear_parts`, `silentgear_materials`, and `silentgear_traits` folders here: https://github.com/SilentChaos512/Silent-Gear/tree/1.20.x/src/generated/resources/data/silentgear. The parts (`hammer_head` for instance) control the gear modifiers.
