### ISSUE TITLE
Daggers and Spears not working as intented.

### ISSUE THREAD

**Issue by 660bryan** [SilentChaos512/Silent-Gear#65]
Instead of decreasing/increasing attack distance, it decreases/increases block breaking distance.

**Comment by SilentChaos512** [comment]
I'm assuming 1.14.4 since you gave no information. Please follow the template next time.

I'll probably have to ask Forge about this. They're the ones who add the reach distance modifier.

**Comment by krokots** [comment]
I confirm this, spears reach is only increased for blocks, but not for entities.
Using 
SilentGear-1.14.4-1.4.6+72.jar
SilentLib-1.14.4-4.4.0+44
1.14.4-forge-28.2.0

**Comment by SilentChaos512** [comment]
Fixed by c592edece7a97d40b1c7d47da100950e330e9a81 and 6dcaebe8d84347fb04cacf7706d3ed0a03534dc4
