### ISSUE TITLE
Hoe does not boost the speed when mining blocks that require Hoe

### ISSUE THREAD

**Issue by psml-imeji** [SilentChaos512/Silent-Gear#655]
## Versions

- **Silent Gear**: 3.5.3
- **Silent's Gems**: N/A 
- **Silent Lib**: 8.0.0
- **Forge**: 47.2.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Silent Hoes can boost the speed when mining blocks that require Hoe.

## Actual Behavior

Hoe does not boost the speed when mining blocks that require Hoe.
For example, a Nether Wart Block can be mined by Hoe fast, but using the Silent Hoe does not boost the speed and just like mining it with hand.
The vanilla Hoes works correctly.

## Links/Images

- None

## Steps to Reproduce the Problem

1. Craft a Silent Hoe and place a Nether Wart Block
2. Mine the Nether Wart Block with Silent Hoe
3. Compare the speed with when mining it with a vanilla Hoe and by hand

**Comment by Auseawesome** [comment]
Can confirm for latest version. Maybe mattocks should also provide this harvest bonus?
