### ISSUE TITLE
Add a dedicated crafting table to reduce recipe clutter

### ISSUE THREAD

**Issue by moonfather1** [SilentChaos512/Silent-Gear#656]
## What Should Be Added or Changed?
A crafting station. Basically a crafting table for gear parts.

## Why Should This Be Done?
Because crafting recipes are drowning in the sea of SG recipes. If i find a material (some ingot for example) and press U to find uses in jei/emi/rei, i need to dredge through a dense jungle of recipes for SG parts.

If they were moved to a separate recipe type (derived from crafting recipe and in any way identical), they would be in a separate tab in jei/rei/emi and I would be able to go through crafting recipes without irritation.

please and thank you.

**Comment by Beethoven-n** [comment]
the Gear Crafting recipe tag should be made more obvious somehow. JEI solves this by just having all the gear recipes seperate from the rest of the game's recipes.

**Comment by Auseawesome** [comment]
That isn't JEI solving it, there's specific compat within the mod files.
If i remember correctly, there used to be a specific craftign station but it got removed for simplicity.
I haven't had any issues with having crafting recipes drowned out, which are you using JEI, REI or EMI?
Also might want to send a screenshot

**Comment by SilentChaos512** [comment]
All of the recipes are already placed in their own tab in JEI. I can't speak for the other mods. Are those even for 1.20.x? I typically don't add features to older versions.

**Comment by Auseawesome** [comment]
Yes REI can be got on 1.20.1 and I can confirm it works fine, I am using it in my pack
EMI is on 1.20.1 but I cannot vouch for how well it works as I don't use it myself
