### ISSUE TITLE
"A temporary compatibility patch" still doesn't work

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/Silent-Gear#660]
## Versions

- **Silent Gear**: https://www.curseforge.com/minecraft/mc-mods/silent-gear/files/5196597
- **Silent's Gems**: N/A
- **Silent Lib**: silent-lib-1.20.1-8.0.0.jar
- **Forge**: 47.1.100
- **Modpack**: N/A
- **Optifine Installed**: No

## Actual Behavior
Error (about data packs) on world loading
Like this: https://i.ibb.co/3RnfZxY/a.png

[silent.log](https://github.com/SilentChaos512/Silent-Gear/files/14671909/silent.log)

**Comment by SilentChaos512** [comment]
I think I see what the problem is. I will fix it tonight.

**Comment by uhloin** [comment]
Thank you for fast problem solving. Now Harvest Level presents even on the sword or chestplate ;-)
