### ISSUE TITLE
Game crashes when i press the singleplayer button

### ISSUE THREAD

**Issue by dopa2077** [SilentChaos512/Silent-Gear#661]
## Versions

- **Silent Gear**: 1.20.1-3.6.0
- **Silent's Gems**: 1.20.1-4.7.0
- **Silent Lib**: 1.20.1-8.0.0
- **Forge**: 47.2.21
- **Modpack**: private
- **Optifine Installed**: Disgusting mod... (NO!)

## Expected Behavior

- me press button --- games goes "creating new world"

## Actual Behavior

- When i press the "Singleplayer" button the game crashes.

## Links/Images

- https://pastebin.com/raw/fKAgBW4c

## Steps to Reproduce the Problem

1. Lunch the game
2. Press singleplayer button
3. *game shits itself*

**Comment by SilentChaos512** [comment]
You need to update to Silent Gear 3.6.3. Version 3.6.0-.2 all crash if you have any mods or data packs that aren't updated for 3.6.0. The latest version adds a patch that will allow older material files to load again without changes.
