### ISSUE TITLE
Crash on Worldgen

### ISSUE THREAD

**Issue by ModifiedMC** [SilentChaos512/Silent-Gear#662]
## Versions

- **Silent Gear**:  v3.6.0
- **Silent's Gems**:  v4.7.0
- **Silent Lib**: 8.0.0
- **Forge**: 47.2.17
- **Modpack**: N/A <-- version is not publicly available -->
- **Optifine Installed**: No

## Expected Behavior

Make world, no crash <3

## Actual Behavior

Make world, get crash </3

## Steps to Reproduce the Problem

1. Create single player world
2. Let world Generate
3. Crash.

Not sure if this is due to the breaking changes to the harvest level stat as I Do also have SilentGear Compat installed (Although its not mentioned in crash report), or something with the recent ModernFix Update, but It doesnt happen with previous versions (Silentlib - same version, SilentGems - v 4.6.0, SilentGear - v3.5.4 )

[crash-2024-03-22_19.19.00-client.txt](https://github.com/SilentChaos512/Silent-Gear/files/14729316/crash-2024-03-22_19.19.00-client.txt)

**Comment by SilentChaos512** [comment]
You need to update to 3.6.3. Please see #661.
