### ISSUE TITLE
Datapack issue

### ISSUE THREAD

**Issue by Sythgirla** [SilentChaos512/Silent-Gear#664]
## Versions

- **Silent Gear**: 3.2.6
- **Silent's Gems**: 4.2.2
- **Silent Lib**: 7.0.3
- **Forge**: 43.3.5
- **Modpack**: RobaCraft (the modpack isn't updated properly because of CurseForge's manual review, and thus we play on a different pack put on the official Discord server, but here is the pack on CurseForge: https://www.curseforge.com/minecraft/modpacks/robadoin-robacraft-1-0)
- **Optifine Installed**: Embeddium/Oculus

## Expected Behavior
I was making a datapack to implement more materials into the RobaCraft server, namely for Blue Skies, Aether, Twilight Forest, among others. I had done this before about a year ago for only Neptunium (Aquaculture 2) which worked fine back then.

## Actual Behavior
Instead of getting the materials that I wanted, it breaks and does 1 of 3 things:
- It becomes an SGear Material, as desired.
- It doesn't become an SGear Material, even if put in the datapack
- It crashes the entire game when hovering over the item, or holding CRTL over the item 

With my current datapack, 9 materials work as intended, albeit with color problems*, and 6 do not. What's worse is some other materials (such as wood, sticks, wool, and even Tyrian Steel) become unusable in Silent Gear crafting, showing no [SGear Material] when hovering over it nor when holding CRTL.

*Honestly, it's irrelevant currently, but it should still work considering it's in the appropriate folder. I might be able to fix it myself but, as stated, irrelevant currently.

## Links/Images
Unloaded SGear Material item:
(https://i.imgur.com/e1eo119.png)
Working Datapack Material Item:
(https://i.imgur.com/sywJ4Lc.png)
Working Datapack Material Item 2:
(https://i.imgur.com/NpuxpuO.png)

Logs:
When /reload or /datapack enable:
https://pastebin.com/fm590zCx
debug.log, latest.log and Prism Launcher log:
https://file.io/oPeHomdZfJFO

## Steps to Reproduce the Problem

1. Code data files
2. Make datapack with data files
3. Load up world
4. /reload or /datapack enable
5. Problem

**Comment by SilentChaos512** [comment]
From the first log file: `java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Found multiple op keys in stat modifier object`

One of your material JSON files must have an error in the stats somewhere. Unfortunately I can't tell you which one.

**Comment by Sythgirla** [comment]
Thank you for the quick reaction, I fixed it and it works fine now, thank you for the help!
