### ISSUE TITLE
Config settings resetting

### ISSUE THREAD

**Issue by krazzykid2006** [SilentChaos512/Silent-Gear#67]
## Versions

- **Silent Gear**: 1.14.4-1.4.2+67.jar
- **Silent's Gems**: N/A
- **Silent Lib**: 1.14.4-4.4.0+44.jar
- **Forge**: 28.1.1
- **Modpack**: N/A

## Expected Behavior

Maintain settings.

## Actual Behavior
Most of the config file settings remain but certain ones reset back to default every time I start the game, preventing me from actually using the changes.

The two that are for sure resetting to default are the quick repair and anvil repair effectiveness settings.
For example, if I change the quick repair effectiveness from the default 0.35 to anything else (let's change it to 0.5 for this example) then I start the game and check the config file again, it will now be reset back to the 0.35 default value. This means the game is never using my changes for these two settings and is always using default. 
- (Description)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Modify the silentgear-common.toml file to change either the quick repair effectiveness value or the anvil repair effectiveness value. Save the file.
2. Launch the game.
3. Open the silentgear-common.toml file again and see that the values are set back to default.

So far it appears as those two settings are the only ones affected. Other settings seem to be keeping their changes. 
I just wanted to point it out in case this isn't known already

**Comment by SilentChaos512** [comment]
Seems to be working as intended. Valid values are 0.0 to 1.0. I could raise the upper limit, if that's the issue?

**Comment by krazzykid2006** [comment]
> 
> 
> Seems to be working as intended. Valid values are 0.0 to 1.0. I could raise the upper limit, if that's the issue?

How is it working as intended when it doesn't work at all? It can't be changed at all. 
If valid values are 0.0 to 1.0 then why can't I change it from the default value at all? It resets to default every time. 
Again, it's impossible to change it at all, even if I am within those valid values. 

0.5 is within the valid values according to you, but I can't set it to 0.5
I can't set it to anything except the default values.

**Comment by SilentChaos512** [comment]
Could I get a log file from you, please? Not really sure what's going on here, because it works for me.
