### ISSUE TITLE
Crash report: Tipped Item/Tool Info?

### ISSUE THREAD

**Issue by lowresgames** [SilentChaos512/Silent-Gear#68]
## Versions

- **Silent Gear**: ~1.14.3~ 1.4.2
- **Silent's Gems**: ~1.6.4~ 3.4.4
- **Silent Lib**: ~1.9~ 4.4.0
- **Forge**: 28.1.19
- **Modpack**: Custom

## Expected Behavior
-Scrolling through my hotbar to select  another tool

## Actual Behavior
- Game crashes as I scroll through/over a tipped tool from Silent's Tools

## Links/Images
-https://gist.github.com/lowresgames/e1ffc945393887fe45af521c537ac9a6

## Steps to Reproduce the Problem

1.Made stone tools with template
2.Added tips/wraps to upgrade
3.Crash when scrolling through hotbar

**Comment by SilentChaos512** [comment]
Would have appreciated _actual_ version numbers instead of made up ones. Corrected using what was in the crash report.

Looks like the same issue as #53. Something to do with Console HUD.

**Comment by SilentChaos512** [comment]
Please reopen with an updated crash report if the issue still exists in the latest version.
