### ISSUE TITLE
(1.20.4)(NeoForged)(Silent Gear 3.7.0) Crash with Silent Geaer on NeoForge Server 

### ISSUE THREAD

**Issue by Sniffity** [SilentChaos512/Silent-Gear#684]
## Versions

- **Silent Gear**:  3.7.0
- **Silent's Gems**: N/A
- **Silent Lib**: 9.1.2
- **Forge**: NeoForged 1.20.4-237
- **Modpack**: Na
- **Optifine Installed**: No

## Expected Behavior
No crash occuring.

## Actual Behavior
Server crashes on loading. This only happens on a Neoforged Server, not a single player game. Crash report attached.
I understand this is not the latest version, but I still figured you'd be interested in the issue. I was planning on submitting a PR; but unfortunately my dev environment is not working properly -_-. At any rate, it seems like a simple issue of handling event classes.

## Links/Images 
Crash Report attached.
https://pastebin.com/UnqHC9et

## Steps to Reproduce the Problem
1 - Launch a NeoForged 1.20.4-237 **server** with SilentGear and SilentLib, crash occurs.

**Comment by SilentChaos512** [comment]
Should be an easy fix. I'll look into it when I get time.

**Comment by SilentChaos512** [comment]
This required a Silent Lib update as well, so be sure to update both mods once they become available for download.
