### ISSUE TITLE
silentlib does not get installed 

### ISSUE THREAD

**Issue by aient** [SilentChaos512/Silent-Gear#687]
## Versions

- **Silent Gear**: x.x.x
- **Silent's Gems**: x.x.x 
- **Silent Lib**: x.x.x
- **Forge**: x.x.x
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

(Description here)

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Closing this, as no useful information was provided. Were you expecting Silent Lib to somehow be downloaded automatically? Depending on what client you are using, you will likely need to download it yourself.
