### ISSUE TITLE
Placing Silent's Gems Legacy Tools/Weapons on bottom rows of Crafting Station mod causes a crash

### ISSUE THREAD

**Issue by shipfridge** [SilentChaos512/Silent-Gear#688]
## Versions
- **Silent Gear**: 0.6.7
- **Silent's Gems**: 2.8.22 
- **Silent Lib**: 3.0.14
- **Forge**: 14.23.5.2860
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Placing Silent's Gems Legacy Tools/Weapons on the bottom rows of [Crafting Station](https://www.curseforge.com/minecraft/mc-mods/crafting-station) shouldn't cause a crash

## Actual Behavior

Placing said item(s) on any of the bottom rows causes a crash

## Links/Images

https://mclo.gs/MFiyJtH
https://mclo.gs/4hLXynL
https://mclo.gs/un5KTiK

## Steps to Reproduce the Problem

1. Install [Crafting Station](https://www.curseforge.com/minecraft/mc-mods/crafting-station) and Silent's mods
2. Load up a new map, craft the Crafting Station and a Paxel/Machete/Katana
3. Place the crafted Legacy Item on any of the three bottom rows of the Crafting Station to cause said crash

**Comment by SilentChaos512** [comment]
Sorry, but Minecraft 1.12.2 hasn't been supported for years.
