### ISSUE TITLE
Hammer Functionality (Glass)

### ISSUE THREAD

**Issue by Graymayne** [SilentChaos512/Silent-Gear#69]
## Versions

- **Silent Gear**: SilentGear-1.14.4-1.4.3+68.jar
- **Silent's Gems**: SilentGems-1.14.4-3.4.4+77.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: forge-1.14.4-28.1.10.jar
- **Modpack**: Self Modified Minecraft
- **Optifine Installed**: Negative 

## Expected Behavior
Break glass, glass panels, and glowstone in a 3x3 pattern.

## Actual Behavior
Only the targeted glass item breaks. In the case of glowstone, any netherrack blocks will break, but not other glowstone.

## Other Information
I used two variants of the hammer, the first was made in survival with an agate gem. It did return the "glowstone block" however, only the single block and if any netherrack blocks were in the 3x3 area, those as well.

I later converted to survival and tested post supercharging with silk touch enchant option (not agate gem; didn't think to test prior to this report; however I doubt its a material vs product issue). Can still go into my world (Oct 11, 2019) and pull up materials for second hammer if needed.

**Comment by Zentraxius** [comment]
I'm having a similar issue, hammer is basically a much more expensive version of oreexcavations shape mining, breaks stone but none of the ores uncovered, spent a fair bit of time making a killer enchanted crimson steel/kyanite/silver rod hammer to discover it's not working? Version 1.15.2 / latest version of mod
