### ISSUE TITLE
[1.21.1][Neoforge] Imcopatibility with EMI 

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#690]
## Versions
- **Silent Gear**: 4.0.0
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.65
- **Optifine Installed**: No 

## Expected Behavior
EMI show appear
With Silent Gear installed, 

## Actual Behavior
EMI does not load 

## Links/Images
This does not happen if Silent is not installed
![image](https://github.com/user-attachments/assets/36eac5ea-0304-4384-b87f-a43e20bb2e6e)

One of the errors that keep appearing in the log keeps showing Caelus API as an issue with EMI.
[Thread-20/ERROR] [EMI/]: [EMI] Critical error occured during reload: java.lang.NoClassDefFoundError: top/theillusivec4/caelus/api/CaelusApi

[latest.log](https://github.com/user-attachments/files/17252576/latest.log)

## Steps to Reproduce the Problem
Install Silent Gear with EMI and JEI
Open the inventory menu

**Comment by SilentChaos512** [comment]
It should be fixed in version 4.0.1. Thanks for the report.
