### ISSUE TITLE
[1.21.1][Neoforge] Crash when converting vanilla armor to SG armor

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#693]
## Versions
- **Silent Gear**: 4.0.1
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.65
- **Optifine Installed**: No 

## Expected Behavior
THe game should not crash

## Actual Behavior
I converted the armor into SG armor, I got an achievement message, and then the game crashed

## Links/Images
- https://pastebin.com/S5HAYZH0

## Steps to Reproduce the Problem
convert iron vanilla armors into SG armor on your inventory.

**Comment by SilentChaos512** [comment]
This will be fixed in the next update. I corrected the boots and leggings conversion recipes to produce valid items. I also added some checks to prevent invalid items from crashing the game.
