### ISSUE TITLE
Better Combat Not Functioning with 4.0.2 gear

### ISSUE THREAD

**Issue by Freedomlink** [SilentChaos512/Silent-Gear#694]
## Versions

- Silent Gear: 4.0.2
- Silent Lib: 10.3.0
- Neo-Forge: 21.1.65
- Optifine: No

## Expected Behavior
With installation alongside Better Combat (version 2.0.3) it would work as previous versions have in that weapons would behave by namesake due to Fallback_compatability.json

## Actual Behavior
neither weapons or tools from silent gear work with better combat while vanilla weapons and tools still function as per mod

## Links/Images

![2024-10-05_15 33 32](https://github.com/user-attachments/assets/548b1a1f-401b-4dca-a168-56f88b3c8da9)
![2024-10-05_15 33 45](https://github.com/user-attachments/assets/515334fc-c581-4fcd-88a0-96ccce82aa53)
![2024-10-05_15 33 50](https://github.com/user-attachments/assets/2ef2c946-f6e6-44d2-b98f-c3cde11de4af)

How to make the issue happen?

1. acquire Silent Gear weapon
2. Use said weapon
3. compare to vanilla sword, axe, or trident

**Comment by v3xed-v0id** [comment]
I hope this gets fixed, i love both of these mods and it would be a shame if i had to choose between one or the other. Thanks for making the bug report.

**Comment by SilentChaos512** [comment]
I'm not familiar with Better Combat. What exactly is not working here?

**Comment by v3xed-v0id** [comment]
> I'm not familiar with Better Combat. What exactly is not working here?

Essentially, better combat overhauls the combat system, it adds new attack animations and attack patterns etc, by default any axe or sword from modded or vanilla should automatically be supported by the mod (regardless of if it is explicitly supported, assuming the mod is using default vanilla values to determine if their weapon is axe or sword etc.)

i am assuming that the swords and axes may not have vanilla values to determine if it is sword or axe, given that the weapons arent using the better combat animations

i think adding support for the spears and daggers to better combat would be cool too tho

**Comment by v3xed-v0id** [comment]
Tho adding support for daggers and spears shouldnt be too hard i dont think, many different mods add support and i believe that better combat has animations for spears and daggers and the rest of the animations/attack patterns for all the weapons in silent gear already in the mod, i think it would just need to be configured on your end, however for the swords and axes specifically it seems this is an issue with vanilla values not being set correctly

**Comment by SilentChaos512** [comment]
I added support for all items that Better Combat has a preset that makes sense for it. Basically everything but shovels, hoes, and mattocks. I had to flip all the spear textures to make it work, but that's no big deal. It will be included in the next update.

**Comment by v3xed-v0id** [comment]
> I added support for all items that Better Combat has a preset that makes sense for it. Basically everything but shovels, hoes, and mattocks. I had to flip all the spear textures to make it work, but that's no big deal. It will be included in the next update.

Thank you very much <3 i appreciate you fixing this. Have a nice day/night!

**Comment by sadtomato521** [comment]
Is there a way to manually remove SG pickaxes from acting like BC's weapon?

**Comment by SilentChaos512** [comment]
I'm not sure. Maybe you could override [this file](https://github.com/SilentChaos512/Silent-Gear/blob/8275d01a766e0a898311761aafd95213b435ea11/src/main/resources/data/silentgear/weapon_attributes/pickaxe.json) with a data pack to change it to an empty JSON (`{}`)? Worth a try.

**Comment by sadtomato521** [comment]
Worked like a charm, thanks
