### ISSUE TITLE
[1.21.x] Weird chafting output on tools 

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#695]
## Versions
- **Silent Gear**: 4.0.2
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.65
- **Optifine Installed**: No

## Expected Behavior
The picks should merge into one

## Actual Behavior
they give off a weird output.
I have two iron picks with wooden handle. There is nothing else to them, they are identical. 

## Links/Images
![image](https://github.com/user-attachments/assets/a72ed8c6-ad97-4930-81a1-49ea06fa8e54)

## Steps to Reproduce the Problem
add two identical tools to the crafting greed

**Comment by SilentChaos512** [comment]
Next update will disable crafting grid repairs, like in previous versions of the mod.
