### ISSUE TITLE
[1.21.x] Crash when looking at material tooltip

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#696]
## Versions
- **Silent Gear**: 4.0.2
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.65
- **Optifine Installed**: No

## Expected Behavior
I should see the material tooltip stats as I hover through the items

## Actual Behavior
the game crashed when I hovered over one of the items

## Links/Images
https://pastebin.com/kkPw8nE9

## Steps to Reproduce the Problem
Hover the mouse through the materials while pressing ctrl to toggle the material stats.

**Comment by SilentChaos512** [comment]
Does a particular material cause this crash?

**Comment by SilentChaos512** [comment]
Seems that sheet metal can cause this crash
