### ISSUE TITLE
[Bug] Making a vanilla crafting bench rewards Blueprints! advancement

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#7]
### Versions

Minecraft Version: 1.12.2
Silent Gear Version: 0.1.1-38
Silent Lib Version: 3.0.1-145

### Expected behavior

- Make a vanilla crafting bench and close the inventory/crafting window to get the Blueprints! advancement and one each of the Pickaxe, Axe, and Shovel blueprints but they are invisible to start with. You have to reload the world to see them.

### Actual behaviour

- Making a vanilla crafting bench should not award this advancement. It states you should make a pickaxe blueprint to complete it.

### Steps to reproduce the problem

1. Make vanilla crafting bench
2. Close the crafting/inventory window
3. Get Blueprints! advancement and three basic blueprints that are invisible in inventory
4. Save and quit to menu
5. Re-load the same world
6. See the free blueprints in your inventory

**Comment by SilentChaos512** [comment]
This is... sort of intended, but could be handled much better. The root advancement unlocks when you get a crafting table and rewards some blueprints to the player, which unlocks the blueprints advancement. Not sure why the blueprints are often invisible (I have seen that), must be a vanilla bug.
