### ISSUE TITLE
[1.21.1] [ATM10] Crash when trying to hopper into Material Grader

### ISSUE THREAD

**Issue by Tenebrean** [SilentChaos512/Silent-Gear#701]
## Versions

- **Silent Gear**: 4.0.2
- **Silent's Gems**: N/A
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.65
- **Modpack**: All the Mods 10 v0.64
- **Optifine Installed**: No

## Expected Behavior
Hopper to push Netherite ingots and Graading Dust (used the basic one) into the Grader to grade ingots for use in tools/armor

## Actual Behavior
Server crashes into a boot loop

## Links/Images
Don't have crash logs as I am not owner/Staff on server. Just word of an admin that its pointing to there.

- (Link)

## Steps to Reproduce the Problem

1. Make a Material Grader
2. Place Hopper pointed into the Grader (was on left side (Don't know if it matters side but detail))
3. Put materials into hopper.

**Comment by SilentChaos512** [comment]
Seems the side does matter. It can crash if the hopper feeds into the side, but not the top.
