### ISSUE TITLE
[1.21] Sickle spawning Dirt Blocks when clicking on grass

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#703]
## Versions
Silent Gear: 4.0.2
Silent's Gems: N/A
Silent Lib: 10.3.0
NeoForge: 21.1.66
Optifine Installed: No

This is more a question to know if is a mod feature or a bug. But when I right-click on a grass block with a Sickle, it spawns a bunch of dirtblocks. 
here is a video showing it
https://github.com/user-attachments/assets/1d31d49a-b6b0-4b09-b2ee-aa04bbd07e2f

**Comment by SilentChaos512** [comment]
That is definitely a bug.
