### ISSUE TITLE
[1.21] Blocks sometimes not dropping between silent gear and FTB ultimine

### ISSUE THREAD

**Issue by jinkhya** [SilentChaos512/Silent-Gear#704]
## Versions

- **Silent Gear**: 4.0.2
- **Silent's Gems**: N/A 
- **Silent Lib**: 10.3.0
- **Forge**: Neoforge 21.1.62
- **Modpack**: ATM10 
- **Optifine Installed**: No 

## Expected Behavior

To always have the blocks drop when you veinmine them with ftb ultimine :)

## Actual Behavior

Sometimes blocks stop dropping when mined with silent gear and ftb ultimine. I managed to find the error in my log when it happened, reported in this post : 
https://github.com/AllTheMods/ATM-10/issues/707#issuecomment-2400259518

## Links/Images

If you want the full log and not just what I wrote on atm10 github, here it is :
- https://gist.github.com/jinkhya/05577eb5c4ca5325799fa275c0c99a7b

## Steps to Reproduce the Problem

Not sure how to reproduce, it's not a consistent bug sadly. If you need anything else, or need me to test something, feel free to ask. Also if this issue is on ftb ultimine side I can report it there, just lemme know.

Best regards,
Jin

**Comment by SilentChaos512** [comment]
I encountered this on my personal server last weekend, and I'm working on it now. It's trying to load a client config value on the server. I should have a fix for it soon.

**Comment by jinkhya** [comment]
Awesome !  Thank you :D

**Comment by SilentChaos512** [comment]
Should be fixed in 4.0.3

**Comment by Caphaldor** [comment]
Seems fixed for me, tested in ATM 10.
