### ISSUE TITLE
[1.21.1] Alloy Forge only accepts 3 items

### ISSUE THREAD

**Issue by DerCommander323** [SilentChaos512/Silent-Gear#705]
## Versions
- **Silent Gear**: 4.0.3
- **Silent's Gems**: No
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.57
- **Modpack**: Custom, pretty small
- **Optifine Installed**: Ew no

The 4th slot of the Alloy Forge does not seem to be usable. I can't put any item in it, hovering over it also does not highlight it, and even a hopper doesn't fill it.

Here, I'm trying to craft Tyrian Steel, but no matter the order, the 4th ingredient won't go in.
![image](https://github.com/user-attachments/assets/0319c5a3-4fea-4225-9d89-f01f26932718)

**Comment by SilentChaos512** [comment]
Confirmed, it seems the fourth input slot is completely missing

**Comment by Cezar-22** [comment]
Same issue here, I can't craft tyrian steel and only 3 slots of the alloy forge are functional. How is this issue closed? Tyrian steel is the reason while silent gear progression system is so good.

**Comment by DerCommander323** [comment]
The issue was closed because the bug was fixed. You just need to wait for the next release
