### ISSUE TITLE
[Bug] Tip[ Upgrades do not increase harvest level

### ISSUE THREAD

**Issue by Caeldeth** [SilentChaos512/Silent-Gear#716]
## Versions

- **Silent Gear**: silent-gear-1.21.1-neoforge-4.0.4
- **Silent's Gems**: N/A
- **Silent Lib**: silent-lib-1.21-neoforge-10.3.0
- **Forge**: 21.1.68
- **Modpack**: [All the Mods 10](https://github.com/AllTheMods/ATM-10)
- **Optifine Installed**: No 

## Expected Behavior
Tip upgrades do not upgrade harvesting level on Silent Gear tools.  E.g., add a diamond tip to a tool with a stone pickaxe head, and the harvest tier remains at stone.  This contradicts the newly added quest description:
```
"Tip Upgrade Blueprint
For when you don't find 3 diamonds

The Tip Upgrade is used to increase the mining level of a tool.  For example if you have an iron pickaxe, with 1 diamond, you can make a Diamond Tip Upgrade and place it on your pickaxe.  This will allow it to mine Obsidian, as well as give it a stat boost.
```

## Actual Behavior
Harvest level remains at stone despite adding a tip upgrade.

(Description here)

## Links/Images
![tool screenshot 1](https://github.com/user-attachments/assets/8135aca6-6533-4c97-9f65-4d0d1e857631)

## Steps to Reproduce the Problem

1. Create tip upgrade (Emerald)
2. Apply to pickaxe with stone pickaxe head
3. Attempt to mine diamond and fail

**Comment by Caeldeth** [comment]
Requested to be added here as part of [ATM 10 bug report](https://github.com/AllTheMods/ATM-10/issues/755).

**Comment by patscades** [comment]
### ATM 10 1.21.1 v1.3

> 1-Osmium paxel with diamond pick can't mine obsidian
> 2-iron pick with emerald/diamond can't mine obsidian
> 3-can't repair iron pickaxe with nickel even tho they are the same harvest tier

Edit1- Salvager doesnt return base itens (tested iron, nickel and osmium)

## As seen on the ss, i discovered these bugs by trial and error lol.


![Screenshot 2024-10-20 032021](https://github.com/user-attachments/assets/7475c85d-6350-40e7-93f6-6702f4c74b39)
