### ISSUE TITLE
[1.21.1] Hammer crushing recipes do not exist

### ISSUE THREAD

**Issue by DerCommander323** [SilentChaos512/Silent-Gear#719]
## Versions
- **Silent Gear**: 4.0.4
- **Silent Lib**: 10.3.0
- **Forge**: 21.1.61
- **Modpack**: Small custom modpack
- **Optifine Installed**: No, Embeddium

I hope I'm not just doing it wrong, but according to the recipe jsons, this should work:
![image](https://github.com/user-attachments/assets/8aa7c4ba-b004-4343-ad34-34b2769ae683)

Logs: https://mclo.gs/WndrlwG

## Steps to Reproduce the Problem

1. Make hammer
2. Put in crafting table with shulker shell
3. Observe

**Comment by DerCommander323** [comment]
Confirmed with just SGear and NeoForge 21.1.69

**Comment by SilentChaos512** [comment]
Any crushing recipes should have moved to the stone anvil. But they might be missing JEI or EMI support.

**Comment by DerCommander323** [comment]
Oh yes, my bad. The recipes do indeed work, they just don't show.
