### ISSUE TITLE
Lumberaxe Unavaible

### ISSUE THREAD

**Issue by Xaikii** [SilentChaos512/Silent-Gear#72]
## Versions

- **Silent Gear**: 1.12.2-0.6.7+76
- **Silent's Gems**: N/A
- **Silent Lib**:1.12.2-3.0.13+167
- **Forge**: 14.23.5.2847
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

According to the Changelog a Lumberaxe should be added

## Actual Behavior

No Lumberaxe avaible (even created new Instances/fresh install)

## Links/Images

- https://imgur.com/a/4x6LjRD

## Steps to Reproduce the Problem

1. Create New Instance
2. Install Silent gear + Silent Lib
3. Start Game

**Comment by SilentChaos512** [comment]
You were looking at the 1.14 changelog. 1.12 is mostly just getting small bugfixes.

**Comment by Xaikii** [comment]
so this is one of the wonderful cases when Twitch Launcher shows Mod Updates without even having the proper Version? Ugh sometimes I really hate that launcher...
well sry my bad then
