### ISSUE TITLE
[1.21.1] Alloy Forge ignores output count

### ISSUE THREAD

**Issue by DerCommander323** [SilentChaos512/Silent-Gear#723]
## Versions
- **Silent Gear**: 4.0.4
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.61
- **Modpack**: Small custom modpack
- **Optifine Installed**: No, Embeddium

As the title suggests, no matter what the recipe states, the Alloy Forge only outputs one output item per recipe when crafting.

**Comment by SilentChaos512** [comment]
It seems to be working normally for me. Can you give a specific example/combination that does this?

**Comment by DerCommander323** [comment]
Huh, that's extremely weird... I'm able to consistently reproduce it with just SGear 4.0.5, SLib 10.3.0 and NeoForge 21.1.69.

Here's the log, I'm not seeing anything related to the Forge though: https://mclo.gs/Y5jKEO2

Exhibit A, Crimson Steel (should output 3):
![image](https://github.com/user-attachments/assets/a050a330-7f27-469d-b4a2-244b7cc78da2)

Exhibit B, Tyrian Steel, should be 4:
![image](https://github.com/user-attachments/assets/88fa4377-99ea-4b5f-a866-52b730934fc7)

Normal Alloying outputs the appropriate amount, i.e. mixing 2 ingots outputs 2 of the alloy ingots

**Comment by SilentChaos512** [comment]
I see, I was testing the generic alloy recipes. Crimson steel and tyrian steel recipes are definitely broken.
