### ISSUE TITLE
Obsidian harvest level is worse than iron and can't mine redstone

### ISSUE THREAD

**Issue by metalim** [SilentChaos512/Silent-Gear#725]
## Versions

- **Silent Gear**: 4.0.4
- **Silent's Gems**: N/A
- **Silent Lib**: 10.3.0
- **Neoforge**: 21.1.68
- **Modpack**: ATM 1.0
- **Optifine Installed**: No

## Expected Behavior
Obisidan paxel could mine redstone and diamond in older versions.

## Actual Behavior
Now it can't

## Links/Images

![image](https://github.com/user-attachments/assets/5e32e637-684a-4ea5-987e-cf5a9b19c5c7)
![image](https://github.com/user-attachments/assets/649c8074-3f3d-406b-8d7e-9f687522c028)
![image](https://github.com/user-attachments/assets/5206cd72-99f1-4808-9679-74e6054ab285)

## Steps to Reproduce the Problem

Try it in ATM10 1.0

**Comment by SilentChaos512** [comment]
This is intended, obsidian was nerfed.

**Comment by metalim** [comment]
oof.
Ok, will track tip harvest level upgrade issue here: https://github.com/SilentChaos512/Silent-Gear/issues/716

**Comment by Schrimpes** [comment]
It's unfortunate that it was nerfed, but I find it illogical that a pickaxe can't mine the material it was made of. Why should you mine now obsidian with a diamond pickaxe to make a pickaxe that can no longer do that?
which even only has a mining level of stone

**Comment by SilentChaos512** [comment]
It's also illogical for such a brittle material to be so tough to mine, but that's Minecraft. I don't want obsidian to be a powerful material. Even if it takes time to get it, it's too common. I could increase the harvest tier, but that would make me want to reduce the durability even more.

Of course, the material could always be overridden with a data pack. You can make it as powerful or as weak as you like.
