### ISSUE TITLE
MaterialMixing silent gear 1.21.1 neoforge how do i enable it?

### ISSUE THREAD

**Issue by PernalongaPirata** [SilentChaos512/Silent-Gear#727]
I don't know if it's because I don't add it or not or if it won't include "MaterialMixing" if it already exists in 1.21.1 of neoforge, how do I enable it because it doesn't appear in the old versions folder?

**Comment by SilentChaos512** [comment]
Legacy material mixing was removed. The Super Mixer is the closest thing now. It has no recipe, so you will need to add a recipe yourself. Or just cheat one in, whatever works for you.
