### ISSUE TITLE
Gem parts cannot be crafted, as such gem setting is completely useless

### ISSUE THREAD

**Issue by AshleighTheCutie** [SilentChaos512/Silent-Gear#728]
## Versions

- **Silent Gear**: 4.0.6
- **Silent's Gems**: 10.3.0
- **Silent Lib**: 5.0.2
- **(Neo)Forge**: 21.1.69
- **Modpack**: Added into Direwolf20 1.21
- **Optifine Installed**: No, modern replacements are however.

## Expected Behavior

When I combine one gem and one Jeweler's Tools, I expect to have one gem part I can add to a tool or other item.

## Actual Behavior

Nothing is crafted at all, as there is no item on the output of the table.

## Links/Images

- https://homesrv.ashleighhost.net/br/silgear_bug_01.mkv

## Steps to Reproduce the Problem

1. Attempt to craft a gem part
2. ???
3. Profit

**Comment by SilentChaos512** [comment]
You forgot the bort. You need one for every setting you craft.

**Comment by AshleighTheCutie** [comment]
You need to update the wiki on here then.

EDIT: https://github.com/SilentChaos512/Silent-Gear/wiki/Starter-Guide

**Comment by SilentChaos512** [comment]
Wiki has been updated with an new version of the starter guide (https://github.com/SilentChaos512/Silent-Gear/wiki/Starter-Guide-(Silent-Gear-4)). The old page has been left alone.
