### ISSUE TITLE
Crash with Gear Mod Kit when removing Netherite coating

### ISSUE THREAD

**Issue by AbsorbingSafe11** [SilentChaos512/Silent-Gear#729]
## Versions

- **Silent Gear**: silent-gear-1.21.1-neoforge-4.0.6
- **Silent's Gems**: silentgems-1.21.1-neoforge-5.0.2
- **Silent Lib**: silent-lib-1.21-neoforge-10.3.0
- **Forge**: Neoforge 21.1.71
- **Modpack** Limitless 8 (with a few mods added for testing)
- **Optifine Installed**: No

## Expected Behavior
The Netherite coating would be returned as a toolpart item and the tool would no longer have the coating 

## Actual Behavior
Game crashed the moment both the tool with the coating and the Gear mod Kit set to coating removal were in the 2x2 player crafting area

## Links/Images

- (Link)
https://pastebin.com/e0WHiFvv

## Steps to Reproduce the Problem

1. Attach Netherite coating to tool
2. Get a Gear Mod Tool Kit and set it to the Coating option
3. Place both the Gear Mod Toolkit and the Tool with Netherite in a crafting grid

**Comment by AbsorbingSafe11** [comment]
I am not very good at reporting bugs, so sorry in advance for any mistakes
Also, when i spoke to the modpack dev it was mentioned that the crash may have been caused by Fastworkbench and/or Polymorph
Additionally, while this issue does cause a crash there doesn't seem to be lingering effects to the world save (probably because I used the player crafting grid)

**Comment by SilentChaos512** [comment]
Based on the crash report, it's likely an issue with the mod kit item itself, and not related to any other mod.
