### ISSUE TITLE
crash when making a world

### ISSUE THREAD

**Issue by VaporeonScripts** [SilentChaos512/Silent-Gear#731]
## Versions

- **Silent Gear**: latest possible for neoforge 1.21.1
- **Silent's Gems**: latest possible for neoforge 1.21.1
- **Silent Lib**: latest possible for NeoForge 1.21.1
- **NeoForge**: .72
- **Modpack**: NeoTech-Reborn
- **Optifine Installed**: no lmao

## Expected Behavior
to not crash

## Actual Behavior
crash when making a world
## Links/Images
https://mclo.gs/zbxDwg5

install silent gear

**Comment by AbsorbingSafe11** [comment]
So i don't know if the crash report showed, but I think this was caused by Silent Gems materials not having the new level hints for mining levels (as I got a similar crash)

**Comment by SilentChaos512** [comment]
Looks like I need to update the material files in Silent's Gems.

**Comment by VaporeonScripts** [comment]
so what should i do? im trying to use the latest version before the one that got released today

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/612b9aee-998a-4c73-b107-6e1e23faf4a1)
downgrading works,waiting for an update

**Comment by SilentChaos512** [comment]
Copy that. I'll fix it when I get home from work this evening.

**Comment by SilentChaos512** [comment]
Silent Gear 4.0.8 should fix the crash, but I'll go ahead and make an update for Gems too.
