### ISSUE TITLE
Other items and blocks show up as valid tool material components in multiplayer

### ISSUE THREAD

**Issue by L0neGamer** [SilentChaos512/Silent-Gear#74]
## Versions

- **Silent Gear**: 1.14.4-1.4.3+68 
- **Silent's Gems**: N/A
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.60
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
That only assigned materials show up with Silent Gear statistics underneath them, so that you can have a look for relevant materials using either JEI or using the Crafting Station.

## Actual Behavior
On first logging into to a minecraft server, the items that represent upgrades and various or materials are replaced by random other items, from Mystical Agriculture essences to RFTools machines to even the Crafting Station from Silent Gear. Additionally, searching "tier 2" in JEI will reveal the same mismatched items as can be found in the crafting station.

On rejoining the same server, the issue seems to vanish.

## Links/Images
Example of incorrect items being assigned to materials; Gold essence (Mystical agriculture) seems to be refined iron.  
Usually, it is a variety of incorrect values, but in the case I recorded it is mostly Mystical Agriculture.

![silentGearerror](https://user-images.githubusercontent.com/10566848/67464530-646ed800-f63b-11e9-8841-217868e67f4a.gif)

## Steps to Reproduce the Problem

1. Start game and join multiplayer server
2. Either search "tier 2" in JEI, or open Crafting Station materials UI
3. Observe that the incorrect materials both have stats and are labelled as the correct material in the Crafting Station materials UI

**Comment by Vaelzan** [comment]
You can temporarily fix this by disconnecting and then reconnecting to the server - the first time you connect after loading the game, it will assign the parts to the wrong items, but upon subsequent connections it will be correct. Hope this helps in tracking down the bug.

**Comment by Vaelzan** [comment]
Out of interest, did you add additional mods or remove mods after creating the world? I think this is when the problem started showing up for me, it seemed fine until changing mods around. I can't confirm this, as I haven't tried to reproduce it yet.

**Comment by L0neGamer** [comment]
So originally the world was created using the Valhelsia pack, but several mods have been added since the creation of the server.

**Comment by SilentChaos512** [comment]
I found a very similar issue on the Adventure of Halk server, related issue here: https://github.com/SilentChaos512/SilentGems/issues/418.

If you can find a specific mod that seems to trigger this, please share what it is. I'm not sure what's causing this issue.

**Comment by SilentChaos512** [comment]
One possible cause is PattysMoreStuff based on [this comment](https://www.curseforge.com/minecraft/mc-mods/silents-gems#c712). Haven't tested it, so not sure if that's accurate.

**Comment by L0neGamer** [comment]
The pack I'm using doesn't contain that mod. I would test, however that would require manually enabling and disabling a bunch of mods on both a client and a server

**Comment by Nachtflame** [comment]
I also had similar issue in my single player (scrambled tags) - Looks through my testing as if *Instant Unify v1.0.2* is the culprit (rolling it back to 1.0.1 fixes for me).  Can anyone confirm?

**Comment by Vaelzan** [comment]
I'm pretty confident that it isn't any one mod causing it, but rather changing or adding  _any_ mod that adds new items after the world was initially created. My world doesn't have any of the mods mentioned so far, being almost pure Valhelsia modpack (with some custom data packs to add Silent Part compatibility with other mods).

**Comment by Vaelzan** [comment]
The only thing that comes to mind without really diving deep into the code is that the traits and parts are synced with the client _before_ the Forge registry is synced - perhaps the part sync message needs to be sent later in the connection process? That would maybe explain why it works after reconnecting to the same server.

**Comment by SilentChaos512** [comment]
That might be the issue. Seems like Forge should send mod login packets after registries. Before login packets were available to mods, I was sending the packets at the first opportunity after that, which was a bit late for JEI.

I could try sending a second packet to update the crafting items for all parts. The example recipes in JEI would still be bugged, but that would still be a big improvement if it works.
