### ISSUE TITLE
Armors have incorrect armor toughness value

### ISSUE THREAD

**Issue by YocyCraft** [SilentChaos512/Silent-Gear#742]
## Versions

- **Silent Gear**: 4.0.8
- **Silent's Gems**: N/A
- **Silent Lib**: 10.3.0
- **Forge**: Neoforge 21.1.73
- **Modpack**: ATM10 1.16 
- **Optifine Installed**: No 

## Expected Behavior

Silent gear diamond armors should have 2 armor toughness for each piece.

## Actual Behavior

Silent gear diamond armors have 8 armor toughness for each piece (32 armor toughness for full set).

## Steps to Reproduce the Problem

1. Take a full set diamond armors of silent gear
2. Equip them and now player has 32 armor toughness

**Comment by uhloin** [comment]
1. Create a vanilla diamond chestplate with tough. +2.
2. Convert it to SG diamond chestplate and tough. is raised to+8.
