### ISSUE TITLE
Can't craft template boards

### ISSUE THREAD

**Issue by MrBootlooper** [SilentChaos512/Silent-Gear#744]
## Versions

- **Silent Gear**: 4.0.8
- **Silent's Gems**: 5.0.2 
- **Silent Lib**: 10.3.0
- **Forge**: 21.1.73 (Neoforge)
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

template boards crafted

## Actual Behavior

crafting result box shows empty

## Links/Images

- https://imgur.com/JG8NykJ

## Steps to Reproduce the Problem

1. Craft dagger
2. Get wood logs
3. Attempt to craft template boards using recipe on mod description

**Comment by SilentChaos512** [comment]
Template boards are crafted on the stone anvil now. Same thing as all recipes that previously used a hammer.
