### ISSUE TITLE
Mattock can't plow mycelium dirt

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#759]
When using a mattock, you can plow dirt, glass blocks, and other dirt variants, but mycelium is excluded from this for some reason.
Could you add mycelium to the list of plowable blocks? 
![image](https://github.com/user-attachments/assets/663edd0f-9f7c-4b83-ab1c-4a5be3b0ecf6)

**Comment by SilentChaos512** [comment]
Which mod adds plowing mycelium? Or is that a vanilla feature now?

**Comment by ffuentesm** [comment]
What? You can't normally till mycelium in vanilla? I thought that was a vanilla version.
