### ISSUE TITLE
`ores_in_ground` tag uses wrong format

### ISSUE THREAD

**Issue by rlnt** [SilentChaos512/Silent-Gear#760]
## Versions

- **Silent Gear**: 4.0.9
- **Silent's Gems**: N/A
- **Silent Lib**: N/A
- **NeoForge**: 21.1.90
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

The `c:ores_in_ground` tag should use the naming convention of the respective block it refers to.

## Actual Behavior

Your [data gen](https://github.com/SilentChaos512/Silent-Gear/blob/1.21.x/src/main/java/net/silentchaos512/gear/setup/SgTags.java#L46) uses `endstone` instead of `end_stone`.

The block itself has the id `minecraft:end_stone`. The underscore should be preserved within the tag. This is important to keep a consistent format among all mods.

**Comment by TelepathicGrunt** [comment]
Basically, use registry name of the block, not the lang name as lang can be changed by resoucepack and is not as consistent as registry name. We also dont want server logic to need to query the translated name to get tags either
