### ISSUE TITLE
Ability to change the activation key for properties and construction

### ISSUE THREAD

**Issue by ffuentesm** [SilentChaos512/Silent-Gear#761]
## What Should Be Added or Changed?
add a config file to change the left control and left alt to other keys when triggering the gear tooltips. 

## Why Should This Be Done?
Some mods cause compatibility issues and cause the use of those keys problematic. 
Mainly tag mods that expand the tooltips causing UI issues. 
![image](https://github.com/user-attachments/assets/37866c67-c910-47e8-ba11-dff247d53ea4)

**Comment by SilentChaos512** [comment]
The keybindings should already be configurable in the Controls menu. Are they missing? If so, please provide the mod version and the name of your mod pack (if public).

**Comment by ffuentesm** [comment]
There are no key options on the control menu. 
![image](https://github.com/user-attachments/assets/3d624512-e515-4f60-aadd-2db53740d4bf)
![image](https://github.com/user-attachments/assets/3742f8fa-fcf3-4ea1-8a80-8b580550f93f)
![image](https://github.com/user-attachments/assets/2d23cf00-1f45-49e3-8759-6ce6d5ffc6ad)

I am using Neoforge 1.21.1 
silent-gear-1.21.1-neoforge-4.0.9
silent-lib-1.21-neoforge-10.3.0
The mod I used as an example is Better Tags-1.21.1-NEO-1.5

**Comment by SilentChaos512** [comment]
Confirmed, keybindings are missing. May not be getting registered correctly.

**Comment by ffuentesm** [comment]
The changes allow us to see the keys on the configuration menu, but they do not work with the new keys even after changing.
![image](https://github.com/user-attachments/assets/2e656c30-28f3-48ae-aaf3-1f4ffc137832)

They are still using the old key settings.
![image](https://github.com/user-attachments/assets/9cb0baf5-73de-4639-ac42-c7ef4c36fbc0)

I am pressing left alt, and the wrong menu is triggering
![image](https://github.com/user-attachments/assets/2c53c4e2-66a9-45a9-b063-50a36823fdb0)

**Comment by SilentChaos512** [comment]
Well, they were working when I tested it... I'll check it again when I have time.
