### ISSUE TITLE
[1.14.4] Flaxseeds ONLY drop Flaxseeds and not the Fiber

### ISSUE THREAD

**Issue by Boomflex** [SilentChaos512/Silent-Gear#77]
## Versions

- **Silent Gear**: 1.4.4+70
- **Silent's Gems**: N?A
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.87
- **Modpack**: Just Not Enough Mods (https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods)
- **Optifine Installed**: No 

## Expected Behavior

Harvesting fully grown crops to receive the Flax Fiber

## Actual Behavior

Right clicking/left clicking just gets the seeds, not fiber.

## Links/Images

https://gfycat.com/PertinentBrownAkitainu

## Steps to Reproduce the Problem

1. Find fully grown plant
2. Punch it
3. No fiber
4. No profit

**Comment by SilentChaos512** [comment]
Wild plants only drop seeds. You need to plant them to get fibers.
