### ISSUE TITLE
Crafted Armor does not gain stats when installed with Mine and Slash. 1.14

### ISSUE THREAD

**Issue by AzureDoom** [SilentChaos512/Silent-Gear#79]
## Versions
- **Silent Gear**: 1.4.4
- **Forge**: 28.1.87
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/world-of-dragons-a-new-age
- **Optifine Installed**: No 

## Expected Behavior
When making armor, that armor would get the mine and slash stats.

## Actual Behavior
Armor does not gain stats.

Noticed you did not have them in your autocompat (great to see someone using it as well!) so I went ahead and a PR for you. Just creating this issue so it's listed and can be closed.

**Comment by WenXin20** [comment]
In version 1.4.5+71 of Silent Gear, only chestplates are getting stats with Mine and Slash. Helmets, boots, & leggings don't get any stats.
