### ISSUE TITLE
Hammer is picky...

### ISSUE THREAD

**Issue by Dragnier** [SilentChaos512/Silent-Gear#8]
### Versions

Minecraft Version: 1.12.2
Silent Gear Version: 0.1.1-38
Silent Lib Version: 3.0.1-145

### Expected behavior

- Hammer should break a 3x3 of blocks that are similar

### Actual behaviour

- While the Hammer will break mixtures of Smooth Stone, Diorite, etc, the Hammer does not break mixtures of non-smooth stone types nor modded types, at the same time. If 4 of the 9 blocks are cobble and the other 5 are smooth stone, the hammer will only break one type, not both. In a similar vein, modded stone types like Rustic Slate are not recognized at all and the hammer only breaks one block like a pick would. I have not tested, but the Excavator may have the same issue with dirt types and the spoon upgrade on a hammer will most likely present the same thing as well.

### Steps to reproduce the problem

1. Make Hammer
2. Look at a 3x3 of mixed block types that break with a pick type tool
3. Check the selector outline of the hammer area to be broken to see it does not mine a full 3x3 unless all 9 blocks are the same non-smooth stone type.

**Comment by Dragnier** [comment]
To be fair, I'm fine with it not mining ores and such in the 3x3 area; skipping the ores makes sense. but it would be much more useful to make tunnels with if it didn't differentiate between stone types.

**Comment by SilentChaos512** [comment]
I do agree the current block matching system is lacking. I'll look into improving it.

**Comment by SilentChaos512** [comment]
Should be working much better in 0.1.3. Ores still match by block, others just check the harvest level.
