### ISSUE TITLE
[FORGE-1.14.4] Netty Epoll Server IO #3/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.silentchaos512.gear.api.parts.MaterialGrade$Argument@4c963e4f (class net.silentchaos512.gear.api.parts.MaterialGrade$Argument)

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/Silent-Gear#80]
## Versions

- **Silent Gear**: SilentGear-1.14.4-1.4.5+71.jar
- **Silent's Gems**: SilentGems-1.14.4-3.4.6+79
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44
- **Forge**: 28.1.96
- **Modpack**: http://puu.sh/EKU4n/774c3469f8.zip
- **Optifine Installed**: No

## Expected Behavior
To play still on my server without any hassle

(Description here)

## Actual Behavior
Relogged into server and getting crazy java io exceptions

(Description here)

## Links/Images
Server:
http://puu.sh/EKU3b/0b29e0b1c5.log
http://puu.sh/EKU3B/486aa13061.log
Client:
http://puu.sh/EKU43/969e3c37f1.log

- (Link)

## Steps to Reproduce the Problem

1. Import twitch instance play on server for awhile and come back after a restart
2. Try to log in again and get spammed with all the servers java io exceptions
3. play no more because you cant log in :(

**Comment by SDUBZ** [comment]
a little extra info http://puu.sh/EKZz5/f5d793d466.png @SilentChaos512

**Comment by SilentChaos512** [comment]
I've seen the `MaterialGrade$Argument` warnings before. I don't believe they cause any issues. Might be the `Received empty payload on channel fml:handshake` line near the end of the second server log. Not really sure what to tell you about that though. Any idea if this happens with just Silent Gear and Lib installed?

**Comment by SDUBZ** [comment]
well the big problem is it cant deserialize some of your objects, causing a empty handshake
this is only happening on dedicated server though
can i ask what affects the player data from your mods ?
because i noticed if i delete my player data it fixes it but then next time you rejoin it happens again

**Comment by SDUBZ** [comment]
its gotta be 
Registered serializer 'silentgear:highlight'
20:50:15.195
Registered serializer 'silentgear:grip'
20:50:15.195
Registered serializer 'silentgear:binding'
20:50:15.195
Registered serializer 'silentgear:tip'
20:50:15.195
Registered serializer 'silentgems:gear_soul'
20:50:15.195
Registered serializer 'silentgear:main'
20:50:15.195
Registered serializer 'silentgear:bowstring'
20:50:15.195
Registered serializer 'silentgear:misc_upgrade'
20:50:15.195
Registered serializer 'silentgear:rod'

later after nearly loading in 
Received empty payload on channel fml:handshake
20:50:37.610
Could not deserialize minecraft:
20:50:37.611
Could not deserialize minecraft:
20:50:37.615
Could not deserialize minecraft:
20:50:37.615
Could not deserialize minecraft:
20:50:37.618
Could not deserialize minecraft:
20:50:37.619
Could not deserialize minecraft:

**Comment by SilentChaos512** [comment]
Could I get a copy of your player data file then? If deleting it fixes the the issue, that file may have a hint of what's going wrong. The "Could not deserialize minecraft:" could be anything that's trying to save/load invalid ID strings.

**Comment by SDUBZ** [comment]
yeah sure here you go @SilentChaos512 http://puu.sh/EM7d1/2c2d264ba6.dat hope you find out what it is

**Comment by SDUBZ** [comment]
bump

**Comment by SilentChaos512** [comment]
Confirmed that one, maybe two of the "Could not deserialize minecraft:" are mine. But Forge also has this same problem with some of its commands. Whatever is causing your issue is unrelated. I couldn't find anything in your player.dat file either, although I don't know what I'm looking for. Your best bet might be to backup your world and start throwing out mods. Or check for mod updates if you haven't recently.

**Comment by SilentChaos512** [comment]
Pushing a small update which will fix the warnings. I doubt it will fix your issue however. I have no idea what else to try here.

**Comment by SDUBZ** [comment]
the only thing i think that could be a a issue is the adding of extra inventory slots, also the soul gear
can it be disabled

**Comment by SilentChaos512** [comment]
I typically don't add any way to disable items. I can remove the logging message about saving them, if that's what you mean.

**Comment by SDUBZ** [comment]
nah its ok man i disabled your mods to see if the client not connecting was your mods fault but still cant connect after
