### ISSUE TITLE
[1.14.4] Crash when hovering Silent's Gear items.

### ISSUE THREAD

**Issue by Boomflex** [SilentChaos512/Silent-Gear#81]
Silent Gear: 1.4.5+71
Silent Lib: 4.4.0+44
Silent's Mechanisms: 0.6.9+42

https://github.com/Boomflex/JustNotEnoughMods/issues/5

**Comment by SilentChaos512** [comment]
Seems this may be caused by an item having a trait that was removed? Not sure how that could happen, but some simple null checks should fix the crash.
