### ISSUE TITLE
[1.14.4] Lumberaxe Server Crash. "Exception in server tick loop"

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silent-Gear#84]
## Versions

- **Silent Gear**: 1.4.6+72
- **Silent's Gems**: 3.4.8+8
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.107
- **Modpack**: [TNP Limitless](https://www.curseforge.com/minecraft/modpacks/tnp-limitless)
- **Optifine Installed**: Nope!

## Expected Behavior
Not crashing.

## Actual Behavior
Lumber Axe crashes the server.

## Links/Images 
Crash-Report:
https://gist.github.com/Gbergz/265b46326e33ab2c229108b89abbe7ba

## Steps to Reproduce the Problem
I've got no idea, one of my players crashed it.

**Comment by SilentChaos512** [comment]
How big was that tree?

**Comment by Gbergz** [comment]
No idea actually. It was one of the players on our server doing it. 
Sorry!
