### ISSUE TITLE
[1.15.2] Flax crops rendered incorrectly

### ISSUE THREAD

**Issue by MelanX** [SilentChaos512/Silent-Gear#86]
## Versions

- **Silent Gear**: 1.5.0+74
- **Silent Lib**: 4.6.0+48
- **Forge**: 31.1.0
- **Modpack**: Just Not Enough Mods 2
- **Optifine Installed**: No

## Expected Behavior

Flax crop will rendered without black stuff

## Actual Behavior

Looks like this:
![image](https://user-images.githubusercontent.com/26039509/74108866-73dc4780-4b7e-11ea-997b-41c355330781.png)
Newly planted:
![image](https://user-images.githubusercontent.com/26039509/74108880-99695100-4b7e-11ea-8189-859ccaf819f6.png)

## Steps to Reproduce the Problem

1. Find a (wild) flax crop

**Comment by SilentChaos512** [comment]
Fixed by eb237c4f7ea46d2be523108f34361cffe39ee85a
