### ISSUE TITLE
Miscellaneous additions [enhancement 1.14+]

### ISSUE THREAD

**Issue by abdmoh123** [SilentChaos512/Silent-Gear#88]
## What Should Be Added or Changed?

- [x] 1) Adding block of crimson iron/steel
- [ ] 2) Maybe a crimson golem that rarely spawns in nether fortresses (or a custom structure)
- [x] 3) Add more nether wood blocks (e.g. fence, stripped log, trapdoor etc.)
- [x] 4) Add golden nether banana, making it the best food source in the game.
- [ ] 5) Change the armor textures
- [ ] 6) Adding crimson lantern

## Why Should This Be Done?

1) Make it consistent with vanilla minecraft (all minerals have block forms). Can be used for building
or storage purposes.
2) This will make crimson iron (and steel) renewable (similar to iron farms).
3) Great for nether building (especially with 1.16 coming soon).
4) More uses for nether banana
5) To make it match the current vanilla armor textures
6) Lantern

**Comment by SilentChaos512** [comment]
I just wanted to say those are all fantastic ideas :)

**Comment by abdmoh123** [comment]
thanks

**Comment by WenXin20** [comment]
The netherwood texture could also be updated to use a texture based off of the newer Jungle Log texture.

**Comment by abdmoh123** [comment]
yeah and make the inside of the log the same colour as the planks

**Comment by SilentChaos512** [comment]
Making the golden nether banana give:
- 10 minutes fire resistance
- 5 minutes resistance I
- 10 seconds of regeneration I
Recipe requires 8 gold ingots.
Any feedback is welcome.
