### ISSUE TITLE
Added functionality with Quark Colored Runes

### ISSUE THREAD

**Issue by renadi** [SilentChaos512/Silent-Gear#9]
Applying Quarks colored runes in an anvil does not change the glow color on my silent gear tools when testing

### Versions

Minecraft Version: 1.12.2
Silent Gear Version: 0.1.2-41
Silent Lib Version: 3.0.3-148

### Expected behavior

Runes change enchantment color of tools when applied in an anvil

### Actual behaviour

Enchantment glow appears to still be white

### Steps to reproduce the problem

1. Enchant a tool
2. Apply quark colored rune in vanilla anvil
3...
4. Profit?

**Comment by SilentChaos512** [comment]
I had no idea that's what the runes did. I should be able to get and use the rune color easily enough. I have to completely override the enchanted effect because the vanilla code doesn't work properly for items with multiple layers, so I'm guessing that's why Quark can't do its thing.

**Comment by SilentChaos512** [comment]
All Quark runes should be supported in 0.1.3, even the rainbow rune.
