### ISSUE TITLE
1.15.2-(forge 31.1.1) java.lang.IllegalStateException: No renderer registered for silentgear:slingshot_projectile

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/Silent-Gear#90]
forge 31.1.1
SilentGear-1.15.2-1.5.1+76
SilentGems-1.15.2-3.5.0+83
SilentLib-1.15.2-4.6.0+48

thought i would let you this is erroring out
logs:
[latest.log](https://github.com/SilentChaos512/Silent-Gear/files/4203513/latest.log)

**Comment by SilentChaos512** [comment]
Ha, I forgot the slingshot projectiles are getting registered at all. I should try to finish the slingshots.
