### ISSUE TITLE
[1.15.2] Readding Mine and Slash integration

### ISSUE THREAD

**Issue by AzureDoom** [SilentChaos512/Silent-Gear#92]
Just posting this here that Mine and Slash is out for 1.15.2 and your 1.14.4 support code will transfer right over as nothing changed API wise that I could find when I updated the autocompability mod.

**Comment by RobertSkalko** [comment]
Maybe, but in the next update which should be 3.1.0 in a few weeks, i'll turn them into datapacks. You can still register them in code but i'd advise just generating them as data. The old ConfigItem class has a method to turn them to the new system, and the new one has a toJson method. So generating the jsons should be very easy.
