### ISSUE TITLE
1.15.2, Need Chargability stat display on Gear with Gems Installed.

### ISSUE THREAD

**Issue by Dehaku** [SilentChaos512/Silent-Gear#95]
## What Should Be Added or Changed?

When combining Silent Gems with Silent Gear, you can mix gems for (assumedly) various Chargability scores on gear, but it's not display in the readout.

## Why Should This Be Done?

More accurate tuning of gear, especially since the Super Charger has a pretty significant impact.

**Comment by SilentChaos512** [comment]
I don't follow. Chargeablility only affects the part stats, so it's not displayed on gear items.

**Comment by Dehaku** [comment]
You are correct good sir, and I am a derp.
